### ISSUE TITLE
disable logging

### ISSUE THREAD

**Issue by apropos** [AuthorizeNet/sdk-php#103]
Is there a way to turn off logging without modifying the authorizenet/authorizenet/lib/net/authorize/util/Log.php file?  It seems strange that logging is hard coded into the source.

**Comment by ashtru** [comment]
No, there is no method. Are you facing any issues because of the automatic
logging?

**Comment by ramittal** [comment]
Try not setting the logfile name (AUTHORIZENET_LOG_FILE), As far as I remember that would, the logging happens only when this property is set,

**Comment by apropos** [comment]
The class file is used to define the constant. I'll have to modify the class file to disable logging, and remember to disable it again when source is updated. It would be better if logging can be toggled with a method call.

Having a log file with sensitive data that grows to no end doesn't seem very secure. With the way my website is setup, log file is directly accessible by going to http://url/phplog unless I add an entry to .htaccess. If someone uses this and doesn't pay attention, the log file may become public and used to find the secret key.

**Comment by ashtru** [comment]
Trannsaction key is masked by default.The log will only show "xxxx". I am sure you will find so in your logs. 
For masking the API Login ID you can add another tag similar to `cardCode` for `name` viz.
```
{
    "sensitiveTags": [
        {
            "tagName": "name",
            "pattern": "",
            "replacement": "",
            "disableMask": false
        },
```
 in your local AuthorizedNetSensitiveTagsConfig.json (it should be in your root folder, same as where phplog is), as given in the instructions [here](https://github.com/AuthorizeNet/sdk-php/blob/master/README.md#customizing-sensitive-tags.)

Please respond if you find any confusion in doing so.

This should be a temporary solution to your problem. Also, I will certainly look into adding methods for enabling/disabling logging and setting the log level. Thank you for your detailed explaination of the requirement.

**Comment by ashtru** [comment]
Instead of editing the json config in [sdk](https://github.com/AuthorizeNet/sdk-php/blob/master/lib/net/authorize/util/AuthorizedNetSensitiveTagsConfig.json), it will be better that you copy it into the same folder where phplog is (or wherever you are calling the api from), and then edit it to add the mask for `name`.

**Comment by brianmc** [comment]
Hi guys, obviously the logging is masked but I think @apropos makes a good point.  We should look into having logging off by default and easily turned on with a simple property.

**Comment by apropos** [comment]
It seems that abstract class AuthorizeNetRequest writes to AUTHORIZENET_LOG_FILE but other classes that use LogFactory writes to phplog via `define ("ANET_LOG_FILE","phplog");` in Log class;

I've updated AuthorizeNetRequest to use LogFactory and updated Log class to read from AUTHORIZENET_LOG_FILE if defined.  It will not generate a log if AUTHORIZENET_LOG_FILE is not defined.

[pull request](https://github.com/AuthorizeNet/sdk-php/commit/ce348787337c7a6f9213a484681d155d4218ab8a)

**Comment by brianmc** [comment]
Hi @apropos, we've enhanced our logging in the latest release 1.8.7, based on your feedback.  Take a look and let us know what you think.  Thanks again for your support.

**Comment by ashtru** [comment]
Not to mention, thank you @apropos for the PR.

**Comment by apropos** [comment]
You're welcome and thank you maintainers.
