### ISSUE TITLE
Call to date_default_timezone_set breaks applications using the sdk

### ISSUE THREAD

**Issue by peterlozano** [AuthorizeNet/sdk-php#115]
See: https://github.com/AuthorizeNet/sdk-php/blob/master/lib/net/authorize/api/controller/base/ApiOperationBase.php#L51

This call resets the timezone to UTC, which overrides the configured php timezone or whatever timezone the application may have set.

Any call to "new Datetime()" made after any operation with authorize.net will generate an UTC time.

**Comment by ramittal** [comment]
Thanks Peter for reporting the bug. A fix has been merged into the future branch "https://github.com/AuthorizeNet/sdk-php/pull/116" and will be included in the next release.

**Comment by brianmc** [comment]
Included in the March release : https://github.com/AuthorizeNet/sdk-php/releases/tag/1.8.8

Thanks for reporting this issue.
