### ISSUE TITLE
Has TLS 1.2 authentication been coded yet?

### ISSUE THREAD

**Issue by madiganr** [AuthorizeNet/sdk-php#127]
Sorry, I'm a bit of a git-hub and Authorize.net sdk-php noob.I'm just looking for information, and didn't know where to post this.

I saw an email indicating Authorize.net is abandoning TLS 1.0 and you can see some preperatory information: [https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Authorize-Net-begins-TLS-1-0-Remediation-for-PCI-DSS-compliance/ba-p/51326](https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Authorize-Net-begins-TLS-1-0-Remediation-for-PCI-DSS-compliance/ba-p/51326).

Information on this has been a bit scattered, with nothing comprehensive found after hours of googling.

My issue is we are using the php-sdk v1.8.3.3 and don't know if it will cause issues with the new TLS requirements. I need to know if I ought to take action and update to the latest version to address this.

Any help is greatly appreciated. Thanks!

**Comment by ashtru** [comment]
Can you please execute following php code and provide us the  TLS version of the request. 
For running this code, save it as a file TLSTest.php anywhere in your system, followed by
 `php TLSTest.php` in the command prompt.  Also please provide us the versions of php, curl and openssl being used.
```
<?php 
$ch = curl_init('https://www.howsmyssl.com/a/check');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$data = curl_exec($ch);
curl_close($ch);

$json = json_decode($data);
echo $json->tls_version;
?>
```

**Comment by mstrom** [comment]
@ashtru I run this php file in my system and it tells me that I have TLS 1.2 
But for some reason authorizenet/lib/net/authorize/util/HttpClient.php use TLS 1.0 when trying to make a request to api servers

**Comment by ashtru** [comment]
Thanks for the update @mstrom 
Glad to see you resolved it, I am closing this issue.
