### ISSUE TITLE
ask - get customer profile by email?

### ISSUE THREAD

**Issue by kelaskakap** [AuthorizeNet/sdk-php#128]
Hi,
is there any way to get customer profile by email address?

thank you.

**Comment by brianmc** [comment]
There is not right now, we recommend that merchants use our customer profile ID in their systems and then retrieve the customer profile directly via that index.  So for example, you would find the customer by email on your system and then call [GetCustomerProfile](http://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-profile).

Having said that we're planning for some major updates to our search functionality and this would be one clear candidate for our customer search feature.  Feel free to open an [Idea](https://community.developer.authorize.net/t5/Ideas/idb-p/ideas) for this one @kelaskakap

**Comment by kelaskakap** [comment]
@brianmc thank you. I'm working a case on my project, where we import users information from excel sheet to our database, we add a field to save customer profile id but we don't have it in the sheet. the available information from sheet just username, email, etc.
