### ISSUE TITLE
Missing CCV/CSC processing

### ISSUE THREAD

**Issue by le717** [AuthorizeNet/sdk-php#129]
I am trying to update an ancient version of the PHP SDK (I have no idea what version it is, it's so old) at work to the newest SDK, partially to take advantage of the new sandbox mode. However, I cannot find a method to set a credit card's CCV/CSC, neither in this SDK or the other language SDKs. A CCV is required for our e-commerce site. To me, this feels like a major oversight in designing the new SDKs, especially when the SDK I am currently using has that ability.

Are there any plans to add CCV support, and if so, is there an ETA on the feature being implemented?

**Comment by brianmc** [comment]
Hi @le717 

The card verification code goes by many acronyms (ccv, cvv, csc, etc), based on card association so we use the field name CardCode to represent it.

You are entirely correct that we did not include this in our sample code so I can understand the confusion.  Apologies for that and here is our updated sample with card code for charging a card:  https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-credit-card.php  

Thank-you for the feedback,

Brian

**Comment by le717** [comment]
Thank you very much! I knew it had to be around there somewhere. I doubted it was not actually implemented but went the safe route and assumed such. Thank you so much for a quick reply. This will be good news at work. :smiley:
