### ISSUE TITLE
Setting Tax

### ISSUE THREAD

**Issue by smash120** [AuthorizeNet/sdk-php#133]
I am new to authorize.net and I am having a little problem. When I set the tax amount using `$transactionRequestType->setTax($tax);` I get the following error

> Catchable fatal error: Argument 1 passed to net\authorize\api\contract\v1\TransactionRequestType::setTax() must be an instance of net\authorize\api\contract\v1\ExtendedAmountType, double given, called in /var/www/html/Authorize.net_sample_code/PaymentTransactions/charge-credit-card.php on line 75 and defined in /var/www/html/Authorize.net_sample_code/vendor/authorizenet/authorizenet/lib/net/authorize/api/contract/v1/TransactionRequestType.php on line 463 
I then instantiate it  
`$extendedAmountType = new AnetAPI\ExtendedAmountType();`
`$tax = $extendedAmountType->setTax($tax);`

When I use this I get the following error

> Fatal error: Call to undefined method net\authorize\api\contract\v1\ExtendedAmountType::setTax() in /var/www/html/Authorize.net_sample_code/PaymentTransactions/charge-credit-card.php on line 30 

If the method does not exist in ExtendedDataType.php how am I suppose to set the tax amount? Am I suppose to create the method myself or is it located in a different file?

**Comment by sunnyrajrathod** [comment]
$tax variable is supposed to be of type ExtendedAmountType, which can be done like this:
$tax = new AnetAPI\ExtendedAmountType(); 
Then
$transactionRequestType->setTax($tax); should work.

**Comment by smash120** [comment]
I made the changes and I no longer am getting that error but now I am getting 
Charge Credit Card ERROR : Invalid response.

**Comment by smash120** [comment]
Thanks @sunnyrajrathod
