### ISSUE TITLE
file_puts_content error

### ISSUE THREAD

**Issue by smash120** [AuthorizeNet/sdk-php#134]
When I run the sample code I get
 Warning: file_put_contents(phplog): failed to open stream: Permission denied in /var/www/html/Authorize.net_sample_code/vendor/authorizenet/authorizenet/lib/net/authorize/util/Log.php on line 268

I changed permissions for Log.php and the folder and still I get that error. Where is it writing the log file to?

**Comment by ashtru** [comment]
It writes to a file named 'phplog' in the same folder where your sample code is running probably /var/www/html/Authorize.net_sample_code/.

Changing permission of Log.php won't have any effect.

**Comment by ashtru** [comment]
If you don't want to see the logs, simply remove the statement `define("AUTHORIZENET_LOG_FILE", "phplog");`

**Comment by smash120** [comment]
@ashtru what's in the log? is it important information or is it application info.

**Comment by ashtru** [comment]
It has the XML request and responses.

**Comment by smash120** [comment]
Thanks for the help. Much appreciated.
