### ISSUE TITLE
Package goetas/xsd-reader has been abandoned.

### ISSUE THREAD

**Issue by martyolson** [AuthorizeNet/sdk-php#137]
We're getting this warning in our projects that use Authorize.net. Will there be an update soon?

`Package goetas/xsd-reader is abandoned, you should avoid using it. Use goetas-webservices/xsd-reader instead.`

Thanks!

**Comment by brianmc** [comment]
We're working on an update.

**Comment by dweinerATL** [comment]
Any ETA on the update?

**Comment by aleksandardragojlovic** [comment]
We are having the same issue. Please provide ETA.

**Comment by keithlogan94** [comment]
I am also having this same issue.  Is there a quick fix for this, for the moment?

**Comment by KalebClark** [comment]
I am having same issue.

**Comment by optimerawifi** [comment]
Same issue here, ETA?

**Comment by hdptrd** [comment]
Change the goetas/xsd2php version on composer.json to this:
`"goetas/xsd2php": "2.0.x-dev#fdc2ab0bb3f2b3ab796ca567cf8c0f3446a7ea3a"`
works for me

**Comment by brianmc** [comment]
Updated all the goetas components to the new Goetas-WebServices versions plus updated dependency to xsd2php-runtime which is lighter weight.  See the new version 1.8.9 and latest composer.json in master.
