### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by AACGitHub** [AuthorizeNet/sdk-php#140]
Ran into an undefined version error when running composer, composer defaulted to 1.0.0 and failed.

Added     "version": "1.8.8" to the require section of the json.

All good.  Didn't see this referenced in the issues list.

Also received the xsd2php warning about the reader - and ran into the issues with the Handler libs.

Found quick responses in the issues section - thanks for that.  New to this SDK, the quick responses and hotfixes are very much appreciated.  Have a swell one.

**Comment by ashtru** [comment]
Thank you @AACGitHub  for your effort, we are constantly looking to improve our response time. We will close this issue, as soon as we verify that we are able to use a stable version of xsd2php.
