### ISSUE TITLE
Documentation says Composer has a MITM issue but that has been fixed.

### ISSUE THREAD

**Issue by gauthierm** [AuthorizeNet/sdk-php#144]
Composer requires HTTPS by default. Documentation should be updated to recommend developers use the default `secure-http` setting and the manually overriding this could allow a MITM.

**Comment by gauthierm** [comment]
See https://getcomposer.org/doc/06-config.md#secure-http

**Comment by brianmc** [comment]
Thanks @gauthierm, really appreciate the heads up on this change, it was long overdue but very welcome!
