### ISSUE TITLE
Documentation lists incorrect dependencies

### ISSUE THREAD

**Issue by gauthierm** [AuthorizeNet/sdk-php#145]
Currently listed as
```
"require": {
  "php": ">=5.2.0",
  "ext-curl": "*",
  "authorizenet/authorizenet": "1.8.8",
  "jms/serializer": "xsd2php-dev as 0.18.0"
},
"require-dev": {
  "goetas/xsd2php": "2.*@dev",
  "goetas/xsd-reader": "2.*@dev"
},
```
but `xsd2php` and `xsd-reader` were moved to regular dependencies and not dev dependencies in 1.8.6

**Comment by gauthierm** [comment]
You shouldn't need to explicitly list dependencies in your project. Composer will install the dependencies `authorizenet` declares.

**Comment by brianmc** [comment]
Apologies, we had an out of date readme with incorrect composer section. We have updated the readme https://github.com/AuthorizeNet/sdk-php you can also see a sample composer.json on our sample code repo here: https://github.com/AuthorizeNet/sample-code-php/blob/master/composer.json 
This repo has CI enabled so it should be run for correctness every night.

Thanks for the feedback and appreciate the patience as we try to streamline the dependency chain.

Brian
