### ISSUE TITLE
Can stock jms/serializer be used

### ISSUE THREAD

**Issue by gauthierm** [AuthorizeNet/sdk-php#146]
Currently, a custom repo with a custom release name is required in your project json.

`jms/serializer-0.18.0` was skipped and `jms/serializer-1.0.0` was released. The current stable release (1.1.0) is years newer than the custom repo+branch recommended by authorize.net. Is the branch still required or has the original bug fix been merged into master?

If the branch is still required, perhaps it should be forked into a separate package as it doesn't seem like it will be merged. This will make authorizenet much easier to install and allow people to use a recent version of `jms/serializer` if they want/need it for another dependency.

**Comment by brianmc** [comment]
Thanks @gauthierm it looked like JMS Serializer was not going to take the merge but now it seems like that project has picked up again and did take the change.  There has been no new release as yet but as soon as they do we'll definitely go with that.  I'm going to keep this issue open until then.

Brian

**Comment by jeremiahsmall** [comment]
Or if you can't count on the original library to tag the version you need, please have goetas tag that branch and register it on packagist.

**Comment by maxolasersquad** [comment]
Which commit at schmittjoh/serializer has the fix needed?

**Comment by maxolasersquad** [comment]
Since https://github.com/schmittjoh/serializer/pull/222 was rejected, can this library provide a work around that doesn't require the patch? This library requiring the other version of the serializer breaks my applications dependency chain since it needs the newer version of the jms-serializer.

**Comment by goetas** [comment]
this new release https://github.com/goetas/xsd2php/releases/tag/2.1.0 should be interesting for you

**Comment by ABM-Dan** [comment]
Symfony just updated their own serializer component, you might want to consider that too.

**Comment by goetas** [comment]
@ABM-Dan as discussed in  https://github.com/symfony/symfony/issues/19330 with the author of sf serializer, it looks that is not yet ready to handle complex xml datastructure  yet

**Comment by goetas** [comment]
Just wanted to let you know that today I have released https://github.com/goetas-webservices/soap-client that includes a pure php  soap client implementation that might be used by authorize.net to communicate with soap web services. the project uses a official release of jms serializer and have the latest xsd2php package

**Comment by taiidani** [comment]
Any news on Authorizenet including a non-dev version of `jms/serializer`?

**Comment by chsriniv9** [comment]
Closing this issue, feel free to reopen in case of any queries.
_Closing note:_ Issues related to _goetas_ repositories moving to _goetas-webservices_, have been resolved. As such jms-serializer version concluded by `composer update ` will work. Use the latest version of the PHP SDK.
