### ISSUE TITLE
goetas/xsd2php 2.0.0 is released, no need to depend on a dev branch

### ISSUE THREAD

**Issue by gauthierm** [AuthorizeNet/sdk-php#147]
The authorizenet dependencies list the 2.x dev branch as a requirement. Since 2.0.0 was released it would be better to require a stable version number than a dev version.

**Comment by brianmc** [comment]
Thanks @gauthierm, we've moved to the new lighter weight xsd2php-runtime https://github.com/goetas-webservices/xsd2php-runtime.  See 1.8.9 or latest composer.json in master.
