### ISSUE TITLE
GoetasWebservices\Xsd\XsdToPhpRuntime\Jms\Handler\BaseTypesHandler does not exist.

### ISSUE THREAD

**Issue by KalebClark** [AuthorizeNet/sdk-php#148]
I am getting this error when I try to run a CC transaction on sandbox.

I checked the xsd2php module and cannot find the BaseTypesHandler class. I have even tried upgrading to his goetaswebservices version and cannot get past the dependencies. 

Has this been seen before, and is there something I can do to get past this?

Thank you,
-Kaleb Clark

**Comment by optimerawifi** [comment]
Having the same issue, cannot update our checkout currently.

**Comment by brianmc** [comment]
Looking at this right now.

**Comment by brianmc** [comment]
Have you got the very latest master with this commit?  https://github.com/AuthorizeNet/sdk-php/commit/d63a785803647e4d137a56cecb7c150e15c32fef

**Comment by optimerawifi** [comment]
This did it for me thanks @brianmc !

**Comment by brianmc** [comment]
Updated all the goetas components to the new Goetas-WebServices versions plus updated dependency to xsd2php-runtime which is lighter weight.

**Comment by KalebClark** [comment]
Thanks for taking a look at this. I have added the following authorize.net package:

        "authorizenet/authorizenet": "dev-master#d63a785803647e4d137a56cecb7c150e15c32fef",

And now I am getting the following message:
-------------------
 Problem 1
    - Installation request for authorizenet/authorizenet dev-master#d63a785803647e4d137a56cecb7c150e15c32fef -> satisfiable by authorizenet/authorizenet[dev-master].
    - authorizenet/authorizenet dev-master requires jms/serializer serializer-master-dev as 1.0 -> no matching package found.
------------------
I have tried many different versions of serializer, and left it out to let this package install, but no luck any way.

Any ideas?

Thanks again,
-Kaleb Clark

**Comment by optimerawifi** [comment]
@KalebClark  You using the latest master?

**Comment by KalebClark** [comment]
of authorize, or serializer?
