### ISSUE TITLE
Question: TLS? GET/POST

### ISSUE THREAD

**Issue by rsanche** [AuthorizeNet/sdk-php#150]
A customer of mine received this email from Authorize.Net:

During a system scan, we noticed that your website or payment solution is using the HTTP GET method when submitting your transaction requests to https://secure.authorize.net/gateway/transact.dll. 

Because HTTP GET methods do not adhere to current TLS protection requirements, Authorize.Net will not allow HTTP GET methods for transaction requests as of July 30, 2016. We recommend that you immediately update your code to use the HTTP POST method instead. 

Any transaction request submitted using HTTP GET after July 30th will be rejected. 

Do you guys have any plan to fix this issue? Thanks

**Comment by ashtru** [comment]
Thank you for raising this issue, we are verifying this issue. Meanwhile, can you please provide us the versions of php, curl and openssl being used?

**Comment by rsanche** [comment]
PHP Version 5.5.34
cURL 7.19.7
OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by ashtru** [comment]
Can you execute following php code and provide us the  TLS version of the request. Also provide the version of sdk-php you are using.
For running this code, save it as a file TLSTest.php anywhere in your system, followed by
 `php TLSTest.php` in the command prompt.
```
<?php 
$ch = curl_init('https://www.howsmyssl.com/a/check');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$data = curl_exec($ch);
curl_close($ch);

$json = json_decode($data);
echo $json->tls_version;
?>
```

**Comment by rsanche** [comment]
This is the result: TLS 1.0

I'm not sure which version of sdk-php we are using but I can see in our SVN that it was added on 2014-11-21.

**Comment by ashtru** [comment]
No code changes are required. For upgrading to TLS 1.2, your PHP, openssl, and curl versions might need to be upgraded as stated in the [Authorize.Net Developer Forum](https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Authorize-Net-begins-TLS-1-0-Remediation-for-PCI-DSS-compliance/ba-p/51326).

**Comment by brianmc** [comment]
Just closing this out. Additional note GET was not shut off on July 30th due to concerns over merchant impact.  Please watch out for future advice notices.  Thanks.
