### ISSUE TITLE
Class 'GoetasWebservices\Xsd\XsdToPhpRuntime\Jms\Handler\BaseTypesHandler' not found

### ISSUE THREAD

**Issue by nirvaat** [AuthorizeNet/sdk-php#158]
I am getting this error when trying to submit the data to Authorize.net:
Fatal error: Class 'GoetasWebservices\Xsd\XsdToPhpRuntime\Jms\Handler\BaseTypesHandler' not found in /home/.../lib/authorizenet/lib/net/authorize/api/controller/base/ApiOperationBase.php on line 82

I have installed the library using composer with following JSON:

> {
>     "name": "authorizenet/authorizenet",
>     "type": "library",
>     "description": "Official PHP SDK for Authorize.Net",
>     "keywords": ["authorizenet", "authorize.net", "payment", "ecommerce"],
>     "license": "proprietary",
>     "homepage": "http://developer.authorize.net",
>     "require": {
>         "php": "~5.3",
>         "ext-curl": "*",
>         "ext-json": "*",
>         "ext-simplexml": "*",
>         "ext-xmlwriter": "*",
> 	"goetas/xsd2php": "2.0.x-dev#fdc2ab0bb3f2b3ab796ca567cf8c0f3446a7ea3a",
>         "goetas/xsd-reader": "2.*@dev",
>         "jms/serializer": "xsd2php-dev as 0.18.0"
>     },
>     "require-dev": {
>         "phpunit/phpunit": "~4.0",
>         "phpmd/phpmd": "~2.0"
>     },
>     "suggest": {
>         "phpdocumentor/phpdocumentor": "For generating API documentation"
>     },
>     "autoload": {
>         "classmap": ["lib"]
>     },
>     "autoload-dev": {
>         "classmap": ["tests"]
>     },
>     "repositories": [{
>         "type": "vcs",
>         "url": "https://github.com/goetas/serializer.git"
>     }]    
> }
>

**Comment by ashtru** [comment]
Have you tried using the latest [composer.json](https://github.com/AuthorizeNet/sdk-php/blob/master/composer.json), after we recently fixed #148?

**Comment by nirvaat** [comment]
Earlier I have used the json mentioned in the #148. I just updated the JSON and updated, but now I am getting another error: Class 'Doctrine\Instantiator\Instantiator' not found in C:\wamp\www\...\vendor\jms\serializer\src\JMS\Serializer\Construction\UnserializeObjectConstructor.php on line 42

I am using the new JSON you referenced in above message.

**Comment by nirvaat** [comment]
Does anyone has any update about this issue? OR is it only me facing this problem?

**Comment by ashtru** [comment]
Can you please chekcout a fresh sdk and add symfony/yaml to dependency as given in this [PR] (https://github.com/AuthorizeNet/sdk-php/pull/157/commits/3f0ac55abf8ed2321e9df478cc7b52d8a35c811b). Now run `composer update`. Please update us if you still get the same issue, as we are still unable to reproduce it.

**Comment by nirvaat** [comment]
I tried updating the Composer.json, as suggested in the pull request. But it did not has any effect. I even tried adding the doctrine/instantiator in the require packages, but no success. The same error is still there - Class 'Doctrine\Instantiator\Instantiator' not found in C:\wamp\www...\vendor\jms\serializer\src\JMS\Serializer\Construction\UnserializeObjectConstructor.php on line 42

my composer.json file is:

> {
>     "name": "authorizenet/authorizenet",
>     "type": "library",
>     "description": "Official PHP SDK for Authorize.Net",
>     "keywords": ["authorizenet", "authorize.net", "payment", "ecommerce"],
>     "license": "proprietary",
>     "homepage": "http://developer.authorize.net",
>     "require": {
>         "php": ">=5.5",
>         "ext-curl": "*",
>         "ext-json": "*",
>         "ext-simplexml": "*",
>         "ext-xmlwriter": "*",
> 		"goetas/xsd2php": "^2.0", 
>         "doctrine/instantiator": "~1.0.3",
> 		"goetas-webservices/xsd2php-runtime":"^0.2",
>         "goetas-webservices/xsd-reader": "^0.1",
>         "jms/serializer": "serializer-master-dev as 1.0",
>         "symfony/yaml": "^3.1"
>     },
>     "require-dev": {
>         "phpunit/phpunit": "~4.0",
>         "phpmd/phpmd": "~2.0"
>     },
>     "autoload": {
>         "classmap": ["lib"]
>     },
>     "autoload-dev": {
>         "classmap": ["tests"]
>     },
>     "repositories": [{
>         "type": "vcs",
>         "url": "https://github.com/goetas/serializer.git"
>     }]    
> }
>

**Comment by maxolasersquad** [comment]
I added the following to composer.json's require section, which fixed it.
```
    "authorizenet/authorizenet": "^1.8",
    "goetas/xsd2php": "2.0.x-dev#fdc2ab0bb3f2b3ab796ca567cf8c0f3446a7ea3a",
    "goetas/xsd-reader": "2.*@dev"
```

**Comment by wootzero** [comment]
I'm having the same  'BaseTypesHandler not found' error. I have php 5.4 and if I checkout a fresh sdk I cannot do 'composer update' because the new Goetas package needs php 5.5

Any help on getting this SDK working with PHP 5.4 will be greatly appreciated!

**Comment by ashtru** [comment]
Thanks for rasing the issue @wootzero. We can look into making this work for PHP 5.4. Meanwhile, you can follow the fix given by @maxolasersquad. Please update if you have further issues.

**Comment by ashtru** [comment]
@wootzero It is highly recommended to use a newer version of php. Not only Goetas and other dependencies have moved to higher versions, but also we anticipate a TLS 1.2 upgrade by our APIs in near future. TLS upgrade is mandated by PCI compliance.
 Another option for using it with php 5.4, is to use an older version of the sdk.
For this, you need **not clone** the sdk. 
You simply need 
a) A composer.json that references an older version of the sdk, e.g.
 ```
{

  "require": {
  "php": ">=5.2.0",
  "ext-curl": "*",
  "authorizenet/authorizenet": "1.8.1",
  "jms/serializer": "xsd2php-dev as 0.18.0"
},
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/goetas/serializer.git"
    }]

}
```
b) You php code with `require 'vendor/autoload.php';`as its first line , as in this [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/67e0dd09b20663888b93f42020ddf67e6721366f/PaymentTransactions/charge-credit-card.php)

**Comment by goetas** [comment]
this new release https://github.com/goetas/xsd2php/releases/tag/2.1.0 should be interesting for you

**Comment by ashtru** [comment]
Anyone getting the error  `Class 'Doctrine\Instantiator\Instantiator' not found ` was using `autoload.php` instead of the composer generated `vendor/autoload.php`

The autoload.php is a custom autoloader for users not using composer. If you are using composer, you can use the vendor/autoload.php.
