### ISSUE TITLE
AuthorizeNetSIM error when $_POST array contains keys with strlen <= 2

### ISSUE THREAD

**Issue by benhamelin** [AuthorizeNet/sdk-php#159]
Line 36 of AuthorizeNetSIM.php fails when trying to set "$this>false = " some value. variable $name is false at this point when substr function returns false on keys with string length 2 or less.

**Comment by ashtru** [comment]
Thanks for raising the issue @benhamelin . All the keys that we usually include in the POST parameters are standard fields accepted by Transact. So, they would be fields like x_amount, x_email, etc.

**Comment by benhamelin** [comment]
Understood, but you also include copies of form fields from the originating site, posted back. Depending on the framework being used to build that original form, there is the potential for this error to occur. A simple test on the key length would solve this problem.

**Comment by ashtru** [comment]
This issue occurs if you are using the old classes like AuthorizeNetAIM , AuthorizeNetCIM, etc.. Those classes will be deprecated soon. AIM, ARB, CIM, Reporting and SIM have been replaced by AuthorizeNet::API.

For AIM, refer examples in https://github.com/AuthorizeNet/sample-code-php/tree/master/PaymentTransactions

For CIM, refer examples in https://github.com/AuthorizeNet/sample-code-php/tree/master/CustomerProfiles

Reopen this issue in case of queries.
