### ISSUE TITLE
Can't create many customer payment profile and after that purchase with multiple payment profile

### ISSUE THREAD

**Issue by abgaryanharutyun** [AuthorizeNet/sdk-php#162]
Hi everyone can give me one suggestion about multiple credit card purchase with create customer payment profile for example i have 3 credit card info with amount and i want after save this tree profile charge but i lost amount after create profile... if we use CreateCustomerPaymentProfileRequest and save multiple payment profiles, is it going to save with the same order as we send the data, e.g.
if we have
````
request => [
    CC Info 1,
    CC Info 2,
    CC Info 3
]
```
and the response is
```
response => [
    Payment Profile Id1,
    Payment Profile Id2,
    Payment Profile Id3
],
```
can we say that 
```
Payment Profile Id1 is for CC info 1,
Payment Profile Id2 is for CC Info 2,
Payment Profile Id3 is for CC Info 3
```

**Comment by ashtru** [comment]
If you use CreateCustomerPaymentProfileRequest , you can only create individual payment profiles.

If you use CreateCustomerProfile to create multiple payment profiles, the payment profile IDs are returned in the same order as they were in the request.  See the description of customerPaymentProfileIdList in the Response tab for [CreateCustomerProfile](http://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-profile) in the API Reference

**Comment by abgaryanharutyun** [comment]
thanks @ashtru
