### ISSUE TITLE
Is there a way to change the currency code?

### ISSUE THREAD

**Issue by rsanche** [AuthorizeNet/sdk-php#175]
Is there a reason why the field "currency_code" is not in `$_all_aim_fields` ?

Do I need to set `$verify_x_fields = false;` and then on my AuthorizeNetAIM object do `->currency_code = 'XXX';`

I also need to set the currency code in the payment profile. Is there any way to do that?

Thank you

From the [AIM_guide.pdf](http://www.authorize.net/content/dam/authorize/documents/AIM_guide.pdf) the documentation:
x_currency_code: Optional
Value: USD, CAD, or GBP.
Format: 3-character string.
Notes: The default currency is selected by the merchant’s gateway and/or payment
processor.

**Comment by brianmc** [comment]
You shouldn't need to explicitly set currency code it will always be whatever your merchant/gateway account is set to.
