### ISSUE TITLE
Get Fatal error

### ISSUE THREAD

**Issue by LawanyaD** [AuthorizeNet/sdk-php#178]
I need to use refund functionality but it displays an error as,

Fatal error: Class 'SampleCode\Constants' not found in /opt/lampp/htdocs/authorize/PaymentTransactions/refund-transaction.php on line 76

**Comment by ashtru** [comment]
When you are using the code from [refund-transaction](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/refund-transaction.php) sample code , replace the sample-code-constants with your values, or the ones used in the sample code [constants](https://github.com/AuthorizeNet/sample-code-php/blob/master/constants/Constants.php) definition.

**Comment by LawanyaD** [comment]
After fix my error it displays,

"No data received

ERR_EMPTY_RESPONSE"

What I do...

**Comment by LawanyaD** [comment]
Fatal error: Class 'CreditCardSimpleType' not found in /opt/lampp/htdocs/authorize/PaymentTransactions/CreditCardType.php on line 12

This error also happend :(

**Comment by LawanyaD** [comment]
How to solve this issue,
Fatal error: Class 'JMS\Serializer\Annotation\Type' not found in /opt/lampp/htdocs/authorize/PaymentTransactions/SensitiveDataConfigType.php on line 7

**Comment by Izodn** [comment]
There can be many reasons behind that error. Are you sure the JMS namespace is loaded in your application?

**Comment by LawanyaD** [comment]
*Fatal error*: Class 'PHPUnit_Framework_Assert' not found in
*/opt/lampp/lib/php/PHPUnit/Framework/TestCase.php* on line *99*

**Comment by ashtru** [comment]
For the first issue(Annotation\Type), please check if you have the following folder with some files and folders inside it: 
<path-to-sdk>/vendor/jms/serializer/src/JMS/Serializer
Or if this error is fixed, how did you fix it?

When are you getting the PHPUnit error? Are you trying to run a unit test not in the SDK?
In any case, you need to have PHPUnit installed, and it should be the same version as the one in <path-to-sdk>/vendor/phpunit/phpunit/phpunit.

**Comment by LawanyaD** [comment]
Ok ,  I fixed that isssue Now it displays an error as,
Fatal error: Class 'goetas\Xsd\XsdToPhp\Jms\Handler\BaseTypesHandler' not found

**Comment by chsriniv9** [comment]
Issues related to _goetas_ repositories moving to _goetas-webservices_, have been resolved. Use the latest version of the PHP SDK.

Closing this issue, feel free to reopen in case of any queries.
