### ISSUE TITLE
can't find that function

### ISSUE THREAD

**Issue by LawanyaD** [AuthorizeNet/sdk-php#179]
Fatal error: Class 'SerializedName' not found in

**Comment by Izodn** [comment]
They're going to need a lot more information than that. Can you please provide the snippet of code that this is in reference to? The full error message from PHP would also be helpful.

**Comment by LawanyaD** [comment]
Fatal error: Class 'PHPUnit_Framework_Assert' not found in /opt/lampp/lib/php/PHPUnit/Framework/TestCase.php on line 99

**Comment by ashtru** [comment]
How did you solve the SerializerName issue?

When are you getting the PHPUnit error? Are you trying to run a unit test not in the SDK?
If you have PHPUnit already installed, please share the unit test you are trying to run.

I would also see if the appropriate autoload.php is included in the unit test file as you can see in the difference between Controller_Test(https://github.com/AuthorizeNet/sdk-php/blob/master/tests/Controller_Test.php#L4) and another [test](https://github.com/AuthorizeNet/sdk-php/blob/master/tests/net/authorize/api/controller/ApiCoreTestBase.php#L7) in a different location.

**Comment by LawanyaD** [comment]
No I just update composer.json in terminal

**Comment by LawanyaD** [comment]
Now I got this type of issue soplease give some idea,

Fatal error: Class 'goetas\Xsd\XsdToPhp\Jms\Handler\BaseTypesHandler' not found

**Comment by ashtru** [comment]
Closing this issue as goetas/xsd2php is migrated to goetas-webservices/xsd2php now. If your issue is not resolved, feel free to reopen the issue.
