### ISSUE TITLE
composer require authorizenet/authorizenet fails

### ISSUE THREAD

**Issue by dustingraham** [AuthorizeNet/sdk-php#180]
Going to: https://packagist.org/packages/authorizenet/authorizenet

Suggests running `composer require authorizenet/authorizenet`

This fails...

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for authorizenet/authorizenet ^1.9 -> satisfiable by authorizenet/authorizenet[1.9.0].
    - authorizenet/authorizenet 1.9.0 requires jms/serializer serializer-master-dev as 1.0 -> no matching package found.
```

Going to: https://packagist.org/packages/jms/serializer

Suggests `composer require jms/serializer`

Running this installs fine.

New dependency is `"jms/serializer": "^1.3"` which should probably be added to `authorizenet/authorizenet` to allow the composer require command to work.

After retrieving that dependency, trying again: `composer require authorizenet/authorizenet`

Again fails with the same "Your requirements could not be resolved to an installable set of packages." error.

**Comment by coldlamper** [comment]
I have the same issue using Composer 1.2.1 and PHP 7.0.8

**Comment by RyanThompson** [comment]
I've tried on multiple PHP versions and different configurations based on the errors and it's borked pretty bad it would seem. Is this package still supported?

**Comment by jeremib** [comment]
Following the documentation, you need to add this to your composer.json for it to work

"repositories": [{
       "type": "vcs",
       "url": "https://github.com/goetas/serializer.git"
  }]

**Comment by dustingraham** [comment]
Thanks jeremib. That's apparent from the documentation.

I opened this issue to give feedback on the typical use case of a composer package. Especially those that discover the package using packagist. Following the steps outlined there, this fails.

**Comment by brianmc** [comment]
We have greatly reduced the dependencies required and removed any need to reference a github repo in the latest version 1.9.2
