### ISSUE TITLE
How to make the SDK work for php 5.4?

### ISSUE THREAD

**Issue by AlexLomm** [AuthorizeNet/sdk-php#181]
Is there a way to make the SDK work for **php 5.4.45**? Here is the error I get when following the composer example in the docs:

```
Problem 1
    - Installation request for jms/serializer serializer-master-dev as 1.0 -> satisfiable by jms/serializer[dev-serializer-master].
    - jms/serializer dev-serializer-master requires php >=5.5.0 -> your PHP version (5.4.44) does not satisfy that requirement.
  Problem 2
    - goetas-webservices/xsd2php-runtime v0.2.2 requires php >=5.5 -> your PHP version (5.4.44) does not satisfy that requirement.
    - goetas-webservices/xsd2php-runtime v0.2.1 requires php >=5.5 -> your PHP version (5.4.44) does not satisfy that requirement.
    - goetas-webservices/xsd2php-runtime v0.2.0 requires php >=5.5 -> your PHP version (5.4.44) does not satisfy that requirement.
    - authorizenet/authorizenet 1.8.9 requires goetas-webservices/xsd2php-runtime ^0.2 -> satisfiable by goetas-webservices/xsd2php-runtime[v0.2.0, v0.2.1, v0.2.2].
    - Installation request for authorizenet/authorizenet 1.8.9 -> satisfiable by authorizenet/authorizenet[1.8.9].
```

**Comment by ashtru** [comment]
For security and performance, PHP 5.6 is the minimum version recommended. Meanwhile, you can try to test using an older version of SDK using a composer.json 
that references an older version of the sdk, e.g.
```

{

  "require": {
  "php": ">=5.2.0",
  "ext-curl": "*",
  "authorizenet/authorizenet": "1.8.1",
  "jms/serializer": "xsd2php-dev as 0.18.0"
},
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/goetas/serializer.git"
    }]

}
```

Then, you need php code with `require 'vendor/autoload.php`';as its first line , as in this [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/67e0dd09b20663888b93f42020ddf67e6721366f/PaymentTransactions/charge-credit-card.php)

**Comment by AlexLomm** [comment]
@ashtru Thank you for a fast response!

I'm aware that the best way would be to go with an up-to-date PHP version, however I'm constrained with my current project requirements, so there is nothing I can do about this.

Btw, will this code work for production code as well?

**Comment by ashtru** [comment]
I am not aware if the older SDK might work fully. But it it works for you in sandbox, you only need to change your credentials(to live credentials) and change the request URL from SANDBOX to PRODUCTION in the [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/67e0dd09b20663888b93f42020ddf67e6721366f/PaymentTransactions/charge-credit-card.php#L31)

**Comment by AlexLomm** [comment]
Thank you

**Comment by AlexLomm** [comment]
Hm, I'm doing `require 'vendor/autoload.php';`, however the following error is shown:

> Fatal error: Class 'net\authorize\api\contract\v1\MerchantAuthenticationType' not found

Can it be, that the sample code is not compatible with the older SDK?

**Comment by ashtru** [comment]
No, it does not seem to be a SDK version concern. You have to make sure that your file is in proper directory structure such that it accesses `vendor/autoload.php` inside vendor folder. Mind you, there is another `autoload.php` in root folder of the sdk, do not use that.

**Comment by AlexLomm** [comment]
Unfortunately, it seems that it's exactly an SDK version concern, because the older and the newer ones differ substantially from each other. For example, the newer one utilizes namespaces, has *net/* folder present, etc. Whereas the older one does not.

Where can I find an older api documentation?

**Comment by rajendraborse** [comment]
I am using AuthorizeNet SDK . Localhost its working,same code import on live server but given following error.

> Class 'net\authorize\api\contract\v1\MerchantAuthenticationType' not found

**Comment by rajendraborse** [comment]
It's working required vendor/autoload.php file path not given properly.
