### ISSUE TITLE
Credit card in void/refund transactions

### ISSUE THREAD

**Issue by ABM-Dan** [AuthorizeNet/sdk-php#184]
I was checking the sample code to void a transaction, and while the request object doesn't require any credit card information, the SDK still creates and attaches a credit card to it, why the difference between those two interfaces?

**Comment by ashtru** [comment]
Thanks for pointing out. Voiding a transaction does not require a credit card. 
Fixed the [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/void-transaction.php)  to reflect the same.

**Comment by ABM-Dan** [comment]
Awesome, thank you!
