### ISSUE TITLE
goetas/xsd2php is deprecated

### ISSUE THREAD

**Issue by enumag** [AuthorizeNet/sdk-php#189]
The package goetas/xsd2php which is required by this one is deprecated. The author recommends [goetas-webservices/xsd2php](https://packagist.org/packages/goetas-webservices/xsd2php) instead.

**Comment by enumag** [comment]
This also makes this package incompatible with ocramius/proxy-manager 2.0+ which is a major issue.

**Comment by brianmc** [comment]
Done, thanks!  composer.json should be a lot cleaner now.
