### ISSUE TITLE
Issue when i uploaded the code to live server , it works fine on my local server

### ISSUE THREAD

**Issue by SafiYoussef** [AuthorizeNet/sdk-php#190]
Fatal error: Uncaught exception 'Exception' with message 'Error getting valid response from api. Check log file for error details' in /home/www/betty.socialsitedirectory.net/shoping-process/sdk-php-master/lib/net/authorize/api/controller/base/ApiOperationBase.php:126 Stack trace: #0 /home/www/betty.socialsitedirectory.net/shoping-process/sdk-php-master/lib/net/authorize/api/controller/base/ApiOperationBase.php(104): net\authorize\api\controller\base\ApiOperationBase->execute('https://api2.au...') #1 /home/www/betty.socialsitedirectory.net/shoping-process/send.php(73): net\authorize\api\controller\base\ApiOperationBase->executeWithApiResponse('https://api2.au...') #2 {main} thrown in /home/www/betty.socialsitedirectory.net/shoping-process/sdk-php-master/lib/net/authorize/api/controller/base/ApiOperationBase.php on line 126

**Comment by ashtru** [comment]
It is a networking issue as [api url](https://api.authorize.net/xml/v1/request.api) is your unreachable. Is your live server behind a firewall, or a proxy ?
Can you try a wget for the [api](https://api.authorize.net/xml/v1/request.api) from your application directory? Normally, you should be getting a page like this `{"messages":{"resultCode":"Error","message":[{"code":"E00003","text":"Root element is missing."}]}}`

**Comment by SafiYoussef** [comment]
Yes It must be the firewall that block it . thanks a lot
