### ISSUE TITLE
Email is not transmitted to server

### ISSUE THREAD

**Issue by rglissmann80204** [AuthorizeNet/sdk-php#191]
Scenario: 
 I have email as a required field in Payment Form Fields settings for the associated Authorize.net account.
Using a custom form, but using the AuthorizeNet / sdk-php, I populate the email using the CustomerAddressType.setEmail() function. 
Using the TransactionRequestType I use the setBillTo function to set the CustomerAddressType.

Problem:
My transaction is declined due to missing email. I can trace that the email value is getting populated all the way through to point of executing and the TransactionRequestType keeps the email value. So, it would seem that this is a problem at the server end of things, but I'm posting this issue in case someone can point me to what I'm missing.

Thanks!

**Comment by ashtru** [comment]
Email is not supported by APIs as part of `billTo` information, even though the SDKs have email in billTo field.  Email is instead sent as part of customer profile information for the customer.

  A solution would be to create customer profile witht the email field.
 Then create a customer payment profile(it has payment and billTo information) of above customer profile with the billTo information.

**Comment by ashtru** [comment]
You can refer the [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/create-customer-profile.php#L50) which creates a customer profile with the first customer payment profile(you cannot however have two customer profiles with same email. )
 
Then you can use the [charge customer profile sample](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php#L24) by passing the [customer profile] (https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php#L16) which has the email and [payment profile](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php#L19) with the billTo.

Feel free to respond, if you have any problems doing so.

**Comment by rglissmann80204** [comment]
Thanks for the information.
