### ISSUE TITLE
1.9.2 Fatal Error

### ISSUE THREAD

**Issue by bcolflesh** [AuthorizeNet/sdk-php#196]
[Thu Dec 08 15:09:39.398970 2016] [:error] [pid 13822] [client x:56824] PHP Warning: include(/var/www/authnet_sdk/vendor/jms/serializer/src/JMS/Serializer/Annotation/Type.php): failed to open stream: No such file or directory in /var/www/authnet_sdk/autoload.php on line 16
 
[Thu Dec 08 15:09:39.399400 2016] [:error] [pid 13822] [client x:56824] PHP Warning: include(): Failed opening '/var/www/authnet_sdk/vendor/jms/serializer/src/JMS/Serializer/Annotation/Type.php' for inclusion (include_path='.:/usr/share/php') in /var/www/authnet_sdk/autoload.php on line 16
 
[Thu Dec 08 15:09:39.399673 2016] [:error] [pid 13822] [client x:56824] PHP Fatal error: Uncaught Error: Class 'JMS\\Serializer\\Annotation\\Type' not found in /var/www/authnet_sdk/lib/net/authorize/util/SensitiveDataConfigType.php:6\nStack trace:\n#0 /var/www/authnet_sdk/autoload.php(16): include()\n#1 [internal function]: {closure}('net\\\\authorize\\\\u...')\n#2 [internal function]: spl_autoload_call('net\\\\authorize\\\\u...')\n#3 /var/www/authnet_sdk/lib/net/authorize/util/ANetSensitiveFields.php(15): class_exists('net\\\\authorize\\\\u...')\n#4 /var/www/authnet_sdk/lib/net/authorize/util/ANetSensitiveFields.php(82): net\\authorize\\util\\ANetSensitiveFields::fetchFromConfigFiles()\n#5 /var/www/authnet_sdk/lib/net/authorize/util/Log.php(365): net\\authorize\\util\\ANetSensitiveFields::getSensitiveXmlTags()\n#6 /var/www/authnet_sdk/lib/net/authorize/util/LogFactory.php(9): net\\authorize\\util\\Log->__construct()\n#7 /var/www/authnet_sdk/lib/net/authorize/api/controller/base/ApiOperationBase.php(51): net\\authorize\\util\\LogFactory::getLog('net\\\\authorize\\\\a...')\n#8 /var/www/authnet_sdk/lib/net/authorize/api/controller/GetTran in /var/www/authnet_sdk/lib/net/authorize/util/SensitiveDataConfigType.php on line 6

**Comment by ashtru** [comment]
First of all, of you are using composer, I would recommend to include /var/www/authnet_sdk/vendor/autoload.php instead of /var/www/authnet_sdk/autoload.php. If you are not, it is recommended to use composer.

Are you using the sdk for the first time?
What is the version of sdk-php you are using?if Please share your composer.json.

**Comment by bcolflesh** [comment]
I tried this again by editing the composer.json directly, instead of requiring the latest packages via command line. This page:

http://developer.authorize.net/hello_world/
 
is wrong, the URL value for the git repo must be encapsulated in quotes, or it won't pass jslint validation.
 
My test works, but the message for my fake batch number:

SUCCESS: Get Transaction List for BatchID : 4606008 No Transaction to dispaly in this Batch.

Note "display" misspelled.

**Comment by ashtru** [comment]
Thank you, @bcolflesh. We will fix this issues in the next release.
