### ISSUE TITLE
getExpirationDate method not working?

### ISSUE THREAD

**Issue by GregCatalano** [AuthorizeNet/sdk-php#197]
$request = new AnetAPI\GetCustomerPaymentProfileRequest();

using sandbox,
$response->getPaymentProfile()->getPayment()->getCreditCard()->getExpirationDate()

returns 'XXXX'

I've tested on a few customers / payment profiles. 

$response->getPaymentProfile()->getPayment()->getCreditCard()->getCardNumber()
$response->getPaymentProfile()->getPayment()->getCreditCard()->getCardType()

work fine for the same profiles.

**Comment by ashtru** [comment]
As given in the [api reference](http://developer.authorize.net/api/reference/#get-customer-profile), in the request you need to set **unmaskExpirationDate** to true.

**Comment by GregCatalano** [comment]
Thanks!
