### ISSUE TITLE
what is the link to pass in to createcontroller when not in sandbox mode?

### ISSUE THREAD

**Issue by BenGeocth** [AuthorizeNet/sdk-php#198]
developer.authorize.net never specifies, it gives xml

**Comment by ashtru** [comment]
You can use the production API endpoint` https://api2.authorize.net` as given in the [sdk constants](https://github.com/AuthorizeNet/sdk-php/blob/master/lib/net/authorize/api/constants/ANetEnvironment.php#L8).

Look at one of the [sample codes](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-credit-card.php#L39) on how to use it, where you have to replace SANDBOX with PRODUCTION.

The full production URL is `https://api.authorize.net/xml/v1/request.api` as given on the [developer reference](http://developer.authorize.net/api/reference/)

**Comment by ashtru** [comment]
It is recommended to use `https://api2.authorize.net/xml/v1/request.api`, instead of `https://api.authorize.net/xml/v1/request.api`
