### ISSUE TITLE
how to get each recurring payments details ?

### ISSUE THREAD

**Issue by sarathvsgit** [AuthorizeNet/sdk-php#200]
Hi 
      How can I get the transaction details of each recurring payments. Is there any method ?

**Comment by ashtru** [comment]
Use [GetTransactionList](https://github.com/AuthorizeNet/sample-code-php/blob/24dcfcda454ccec9d85e6fdbaca9ee1fa6f5f052/TransactionReporting/get-transaction-list.php) (using the batch id from [GetSettledBatchList](https://github.com/AuthorizeNet/sample-code-php/blob/24dcfcda454ccec9d85e6fdbaca9ee1fa6f5f052/TransactionReporting/get-settled-batch-list.php) where you can filter based on date, as recurring transactions occur on a periodic basis.)
For each transaction in the list, you can check the subscription field for that transaction:
![image](https://cloud.githubusercontent.com/assets/14973353/21674038/065d6d12-d352-11e6-8adf-16a39cec61c5.png)

So you the code after [line 38](https://github.com/AuthorizeNet/sample-code-php/blob/24dcfcda454ccec9d85e6fdbaca9ee1fa6f5f052/TransactionReporting/get-transaction-list.php#L38) can be based on something like this:
```
if($transaction->getSubscription() != null){
   $subscriptionId = $transaction->getSubscription()->getId();
   //can use this id for further subscription details
   $paymentNumber = $transaction->getSubscription()->getPayNum();
   echo "No. of times this susbcription has been charged: $paymentNumber";
}
```

**Comment by sarathvsgit** [comment]
ok thanks . Iet me try .

**Comment by ashtru** [comment]
Hi, sarathvsgit, we hope that you were able to find a solution. Please comment on this issue in case of further queries regarding it. Meanwhile, this issue will be marked as closed.

**Comment by sarathvsgit** [comment]
I tried above code . I couldn't fetch the subscriptionId  using the [GetTransactionList ](https://github.com/AuthorizeNet/sample-code-php/blob/24dcfcda454ccec9d85e6fdbaca9ee1fa6f5f052/TransactionReporting/get-transaction-list.php)

**Comment by ashtru** [comment]
Can you please post the code/request you are using for GetTransactionList?
How did you get the batchId input for it?

**Comment by sarathvsgit** [comment]
In GetTransactionList I had  added after line number 38

            if($transaction->getSubscription() != null){
   $subscriptionId = $transaction->getSubscription()->getId();
    $paymentNumber = $transaction->getSubscription()->getPayNum();
   echo "No. of times this susbcription has been charged: $paymentNumber";
     }

   
    Full code is 

 
  	  foreach ($response->getTransactions() as $transaction) {
  	  	echo "		->Transaction Id	: " . $transaction->getTransId() . "\n"; 
  	  	echo "		Submitted on (Local)	: " . date_format($transaction->getSubmitTimeLocal(), 'Y-m-d H:i:s') . "\n";
  	  	echo "		Status			: " . $transaction->getTransactionStatus() . "\n";
  	  	echo "		Settle amount		: " . number_format($transaction->getSettleAmount(), 2, '.', '') . "\n";

   
          if($transaction->getSubscription() != null){
   $subscriptionId = $transaction->getSubscription()->getId();
   //can use this id for further subscription details
   $paymentNumber = $transaction->getSubscription()->getPayNum();
   echo "No. of times this susbcription has been charged: $paymentNumber";
     }


  	  }

**Comment by ashtru** [comment]
What  was the batchId input?
Specifically, can you be sure that this batch had atleast one recurring billing transaction? Otherwise, you might have to iterate over all the batches for the month?

Also, for your above code, currently what is the output? No output?

**Comment by sarathvsgit** [comment]
I get the transaction id  ,status  and settle amount  .But I didn't get  subscriptionid  and paymentnumber etc .  as per your code 

if($transaction->getSubscription() != null){
   $subscriptionId = $transaction->getSubscription()->getId();
   //can use this id for further subscription details
   $paymentNumber = $transaction->getSubscription()->getPayNum();
   echo "No. of times this susbcription has been charged: $paymentNumber";
     }
  
we should get  payment number and subscription id etc . right ?
 
 $transaction->getSubscription  return nothing.

**Comment by ashtru** [comment]
If $transaction->getSubscription is null, that means that the transaction was not created as part of a subscription charge.
The batchId must be provided for a batch of transactions that includes subscription charges. What is the date range ( first and last settlement date), you passed in the call to GetSettledBatchList ?

**Comment by sarathvsgit** [comment]
Yes. solved. I found the issue.   Issue with the date rage. I  changed the date range and got subscription details .
