### ISSUE TITLE
I'm using php 5.217 and need assistance

### ISSUE THREAD

**Issue by nowcastingbob** [AuthorizeNet/sdk-php#201]
I have PHP 5.217. Due to site issues, upgrading isn't feasible for us.

The current diff edits at https://github.com/AuthorizeNet/sdk-php/commit/444aeb818f02cc27cf56bfe1493f531c3ba56e0c won't work for me because I don't have all those files.  I have made the alterations to all the files in the top of the lib directory, but there is no lib/net/authorize/ directory, nor is there a composer.json file. 

This just broke today.  All our subscriptions and sign ups are now shut off so we need to resolve this as soon as possible.  Help!

**Comment by rhldr** [comment]
@nowcastingbob If your integration broke today and you are using an older version of our PHP SDK, you may be able to correct the issue updating your certificates: https://github.com/AuthorizeNet/sdk-php/blob/master/lib/ssl/cert.pem

**Comment by AzizSaleh** [comment]
I also ran into this issue and updating the cert.pem seem to have solved my issue. Not sure if this is the case with you but it won't hurt to try:

https://github.com/AuthorizeNet/sdk-php/tree/master/lib/ssl

It would be nice of Authorize.net to alert their users when it is updated so they can update their code.

**Comment by nowcastingbob** [comment]
rhldr, where would I place that certificate?  I'm trying to figure this out and I found the directory where the SDK is stored, but I'm a bit technonlogically challenged.

**Comment by AzizSaleh** [comment]
@nowcastingbob That file should exist within your code base, you would need to replace it with the new version. Do a find to locate cert.pem.

**Comment by adavidw** [comment]
In the current version of the SDK, it's installed into vendor/authorizenet/authorizenet/lib/ssl/, but like Aziz says, depends on your code base.

**Comment by nowcastingbob** [comment]
It was there.  I had made a few other changes but I think I reverted it back and put it in the ssl directory where the other one was.  That doesn't appear to have resolved it.

**Comment by AzizSaleh** [comment]
@nowcastingbob As a sanity check when you open the only cerm.pem file (via notepate, vi, etc..) does it match the latest:?

https://github.com/AuthorizeNet/sdk-php/blob/master/lib/ssl/cert.pem

Also you reverted everything back to how it used to be (except for the pem file)?

I wonder if you have the version # of the SDK you are using?

**Comment by nowcastingbob** [comment]
Where would I find the version #?  I have no idea which one it would be, but it was last edited 4 1/2 years ago.  I'm checking the cert.

**Comment by nowcastingbob** [comment]
I think I'll just cut and past a new one because the ert.pem file doesn't look right when I open it.

**Comment by nowcastingbob** [comment]
That did it!  Thank you so much!!!!!!!!
