### ISSUE TITLE
Failed To Open Stream

### ISSUE THREAD

**Issue by johnmadison** [AuthorizeNet/sdk-php#202]
Here is my output from the error logging:

Message: include(/home/assnetwo/public_html/beta/pfxdemo/assets/plugins/authnet/vendor/jms/serializer/src/JMS/Serializer/Annotation/Type.php): failed to open stream: No such file or directory

I'm loading the SDK without Composer as we aren't using it on this server and don't want to open up SSH access. Is there a way to get around this? The Vendor directory doesn't exist in the version I downloaded. I'm assuming this is something that Composer deals with?

**Comment by rrcoey** [comment]
https://community.developer.authorize.net/t5/Integration-and-Testing/Is-Live-Environment-Down-Keep-Getting-quot-Error-connecting-to/m-p/56598#M31379

This appears to have fixed the problem for me.  I was using an old SDK that was working perfectly fine until about 2 weeks ago.

**Comment by ashtru** [comment]
@johnmadison, if you are still facing the issue, please try using
`require 'path_to_sdk/autoload.php'; `
 instead of
`require 'path_to_sdk/vendor/autoload.php';`

**Comment by ashtru** [comment]
@johnmadison  A clarification: The vendor folder, which has the dependency binaries, is still required for using the SDK. This can only be generated by using the composer. 
After which, you can choose to include either the composer vendor/autoload.php or the manual one autload.php.
One way would be to run the composer in a local environment, after which you can manually copy the vendor folder to your production environment.

Please let us know if this fixes your issue.

**Comment by xinthose** [comment]
Where is the vendor folder?  It's not in this repository.  I'm using Windows so I have to manually put in the require path for it.  I get the following errors: 

```
include(C:\Program Files (x86)\EleMech\WaterStations\osrc\sdk-php-master/vendor/jms/serializer/src/JMS/Serializer/Annotation/Type.php): failed to open stream: No such file or directory
include(): Failed opening 'C:\Program Files (x86)\EleMech\WaterStations\osrc\sdk-php-master/vendor/jms/serializer/src/JMS/Serializer/Annotation/Type.php' for inclusion (include_path='.;C:\php\pear')
```

**Comment by jasonglisson** [comment]
Not able to get composer on shared hosting. I'm running into this problem with lots of PHP applications now. 

Where exactly are you supposed to change:
`require 'path_to_sdk/vendor/autoload.php';`
to
`require 'path_to_sdk/autoload.php';`

**Comment by texdc** [comment]
I have the same problem with composer on shared hosts.  That said, that's not the best environment to be running financial transactions.  A small server on AWS is dirt cheap and will suit most use-cases, plus give you plenty of room to grow as needed.  (Use a reserved instance, or spot pricing, just don't pay the on-demand price for something you'll leave running continuously.)

As to your question, put `require 'path_to_sdk/autoload.php' in your `index.php` file, which should be the only php file that is publicly accessible.

**Comment by jasonglisson** [comment]
Yeah it's not really up to me where my client hosts their site. AWS isn't cost effective for them.

I'm afraid this didn't work either. It's an older Drupal 7 site so this is snowballing into all kinds of issues with Ubercart, CIM, and Composer.

**Comment by texdc** [comment]
How is a [simple server](https://calculator.s3.amazonaws.com/index.html#r=CMH&s=EC2&key=
calc-1AE185BC-7D73-4D0D-AD58-6DD1A50764C5) not cost effective, especially when security is a concern (as it should be with financial transactions)?

If you're still managing D7 sites, I feel sorry for you.  Those low-budget clients are the worst and usually complain the most while being unwilling to pay for the resources and effort of what they expect.  I've been there, done that.

I highly recommend to get them off D7 and shared hosting as quickly as possible.

**Comment by jasonglisson** [comment]
While I fully understand what you're talking about, it's not up to me to make those decisions. I work on lots of AWS sites with my full time job. This is a freelance gig with a local company that contacted me and barely worth my time and the headache moving them to another hosting or worrying about this. I've figured up AWS cost. With the videos they stream, large downloads they provide, how large their bi-lingual site is, and several dedicated IPs, it would cost them over $2k a year. They are paying $350 a year right now. They approached me for help on this one issue. 

FYI, I manage some very high profile D7 sites and several large scale government sites that were just launched on D7 because D8 doesn't have the capabilities yet. 

Unless you have anything helpful to add, I'll be moving on.
