### ISSUE TITLE
vendor dependencies

### ISSUE THREAD

**Issue by jhartman86** [AuthorizeNet/sdk-php#203]
I've been developing w/ PHP for eons and this is quite literally the most poorly authored release of anything I've ever seen. I understand you guys are trying to follow the community and where its going w/ Composer - but you've failed in absolutely the biggest way possible. Beyond that, the fact that this SDK - which is handling SENSITIVE FINANCIAL INFO - depends on external dependencies you guys have zero way of monitoring for security holes when they get downloaded by composer clients is mind boggling.

I'm skeptical, but humor me - is there any justifiable reason in hell that this SDK requires literally hundreds of file dependencies? I mean its just sending some formatted requests over regular old HTTP right? What on earth could _possibly_ force you guys to require so many external things?

I suppose it doesn't matter, I'm recommending to my customers to switch away from Authorize.net and will 100% share that message w/ any fellow developers I come across. Maybe this tirade will make you guys realize you're going to get smoked by Stripe if you don't turn it around immediately. You've wasted an astounding amount of people's time by making us try and use this.

**Edit**: I saw on the authorize.net forums somewhere that a core developer of this library said "you can use this library without composer, you just have to download the dependencies". Thats insane. The dependency tree has subtrees upon subtrees. Please at the very least put documentation up indicating that you **cannot** indeed use this without Composer.

**Comment by brianmc** [comment]
Thanks for the feedback Jon, we're hearing it and we're working on it.  I won't repeat the reasons why we moved to a generated SDK, there are plenty of threads that talk about that, clearly those benefits are being out-weighed for developers by the burden of the additional dependencies and we need to review that decision.

Our valued community in github will of course be the first to sample any upcoming changes.

Thanks again,

Brian

**Comment by nickjohnson** [comment]
I have the same concerns as @jhartman86. Once we finally got Composer to run the dependency sync, the vendor directory was more the 12MB of files... really? Is there a way to minimize this bloat a bit?

**Comment by tstizzle** [comment]
i third the comments of jhartman86.  i'm doing an implementation for a client currently, and i DO use composer.  however, **EVEN USING COMPOSER**, this sdk does not work!  the dependent library jmsserializer has parse errors in a supported php version.

is anyone actually using this library for new integrations?  it sounds like everyone involved already has code up and running from previous, more stable versions.

i attempted to get help from A.N, but their "support" system never allows me to log in after i have successfully created an account!

at this point, it appears it would require less effort to hand-hold my client in moving to a new gateway, rather than try to implement this code.

**Comment by brianmc** [comment]
We're hoping to have an alternative PHP SDK available in the coming weeks.  I realize that does not help you guys struggling with an integration right now but I do want you to know we are in no way ignoring this feedback.

**Comment by tstizzle** [comment]
thank you @brianmc.

**Comment by JoeGradecki** [comment]
Not to pile on - I have a customer moving from CyberSource and yes, I spent most of five hours trying to get the SDK to work but the JMS errors are troublesome.   Do you have an ETA on an alternative PHP SDK that actually works.   

Note, I'm not a developer noobie...I just tried to follow this link - https://developer.authorize.net/hello_world/    and used composer...

**Comment by tstizzle** [comment]
if you install the jms serializer from the jms repo on git, rather than the A.N repo, it should work.  that's what worked for me.  there are several classes missing in the A.N Serializer repo, which (of course) are called by A.N.

**Comment by jhartman86** [comment]
Note to all - closing this thread as I simply don't want to receive notifications anymore. We ended up switching to Stripe as Authorize.net felt so far in the wrong direction with regards to documentation and tooling.
