### ISSUE TITLE
Dependency Issue - JMS Serializer

### ISSUE THREAD

**Issue by iammilton82** [AuthorizeNet/sdk-php#205]
Using composer (Authnet SDK 1.9.2), implemented verbatim the sample code (with my sandbox credentials) and are getting the following error:

An uncaught Exception was encountered

Type: JMS\Serializer\Exception\XmlErrorException

Message: [FATAL] Premature end of data in tag html line 1 in (line: 8, column: 1)

Filename: path/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php

Line Number: 80

**Comment by iammilton82** [comment]
Updating with my composer file:

{
    "require": {
	    "php": "5.6.*",
        "mashape/unirest-php": "2.*",
        "dompdf/dompdf": "0.7.*"
        "ext-curl": "*",
        "authorizenet/authorizenet": "^1.9"
    }
}

**Comment by iammilton82** [comment]
Figured this out.  I created the problem mysql by trying to manually set the environment based on the API documentation.  Resolved this by using the default environment and using a conditional to set the production environment based on some of my own application conditionals:

`$response = $controller->executeWithApiResponse( $pay->environment === 'testMode' ? \net\authorize\api\constants\ANetEnvironment::SANDBOX : \net\authorize\api\constants\ANetEnvironment::PRODUCTION );`

**Comment by vita10gy** [comment]
We had this issue happen to us. We were already doing something like what @iammilton82 was.  I suspect it's temporary, but should probably be handled. Perhaps the server returns HTML pages when the service is temporarily down or something. 

Fatal Error: Uncaught JMS\Serializer\Exception\XmlErrorException: [FATAL] Premature end of data in tag HTML line 1
 in  (line: 5, column: 1) in [the root]/www/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:84
Stack trace:
#0 [the root]/www/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(127): JMS\Serializer\XmlDeserializationVisitor->prepare('<HTML><HEAD><TI...')
#1 [internal function]: JMS\Serializer\Serializer->JMS\Serializer\{closure}(Object(JMS\Serializer\XmlDeserializationVisitor))
#2 [the root]/www/vendor/phpoption/phpoption/src/PhpOption/Some.php(89): call_user_func(Object(Closure), Object(JMS\Serializer\XmlDeserializationVisitor))
#3 [the root]/www/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(131): PhpOption\Some->map(Object(Closure))
#4 [the root]/www/vendor/authorizenet/authorizenet/lib/net/authorize/api/controller/base/ApiOperationBase.php(129): JMS\Serializer\Serializer->deserialize('<HTML><HEA
File: [the root]/www/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php
Line: 84

This is using a pretty up to date install using composer. Payments in general seem to be happening successfully.

**Comment by thekingbk90** [comment]
SANDBOX or PRODUCTION is not reason!
iammilton82 are you sure this issue was resolved?

**Comment by adavidw** [comment]
Hi @thekingbk90,

User @iammilton82 indicated that the problem was on their side and it was resolved for them. If you're seeing the same problem, you can try some of the same things they tried, or open a new issue.

If you do that, please post a lot more details about what you're trying, what you're seeing, what your code is doing, etc. And please, post code examples and example requests and responses.
