### ISSUE TITLE
Create Accept Transaction: bad response

### ISSUE THREAD

**Issue by xinthose** [AuthorizeNet/sdk-php#210]
Hello.  I'm using Accept.js to feed PHP the data value, description, and payment amount.  I am using Sandbox and everything goes fine until I try to handle the response.  `serialize($response)` gives me `O:55:"net\authorize\api\contract\v1\CreateTransactionResponse":5:{s:76:"` which is not right.  What is the issue?  I cannot require the vendor autoload.php that I built with composer because the script fails to load it for some reason.  I am using Windows 7 and hosting the HTML5/JavaScript/CSS3/PHP on IIS 7 https.  Attached is my PHP script.

Thank you.
[send_payment.zip](https://github.com/AuthorizeNet/sdk-php/files/783371/send_payment.zip)

**Comment by chsriniv9** [comment]
Composer is mandatory for auto-loading classes, even if you are not using it for dependency management. 
As such, only current workaround we can suggest is to run composer on another system with the same version of PHP you intend to use on IIS, and upload the generated vendor folder to your server.

Closing issue, reopen in case of assistance required.
