### ISSUE TITLE
classmap.php incorrect class names for GetHostedPaymentPageRequest and GetHostedPaymentPageResponse

### ISSUE THREAD

**Issue by unholyknight** [AuthorizeNet/sdk-php#211]
I was hunting down a fatal class error and eventually traced it to the classmap.php file.

Lines 338-339 have .php in the class name key:
`net\authorize\api\contract\v1\GetHostedPaymentPageRequest.php' => $libDir . 'net/authorize/api/contract/v1/GetHostedPaymentPageRequest.php',
'net\authorize\api\contract\v1\GetHostedPaymentPageResponse.php' => $libDir . 'net/authorize/api/contract/v1/GetHostedPaymentPageResponse.php',`

These should be:
`net\authorize\api\contract\v1\GetHostedPaymentPageRequest' => $libDir . 'net/authorize/api/contract/v1/GetHostedPaymentPageRequest.php',
'net\authorize\api\contract\v1\GetHostedPaymentPageResponse' => $libDir . 'net/authorize/api/contract/v1/GetHostedPaymentPageResponse.php',`

**Comment by reboot-sequence** [comment]
I agree with unholyknight-- this is still wrong in my copy I downloaded on GitHub today. Please fix this.

**Comment by adavidw** [comment]
Fixed in PR https://github.com/AuthorizeNet/sdk-php/pull/233. This had somehow slipped on my to-do list, but should have stayed high priority. Thanks for bumping it up.

**Comment by FritzTGreen** [comment]
I hate to report this, but this bug seems to have found its way back into the code. The classmap.php file on this repository right now contains the same problem. I also noticed a few other class names in the map with '.php' still appended.
