### ISSUE TITLE
Magic Constants in Static Properties

### ISSUE THREAD

**Issue by WestTexasGuy** [AuthorizeNet/sdk-php#213]
In `vendor/composer/autoload_static.php` there are numerous magic constants being used within static properties.  This is making my IDE come up with 298 errors.  Is this file needed once composer has done its work?
Example:
```php
    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\Yaml\\' =>
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
        'GoetasWebservices\\Xsd\\XsdToPhpRuntime\\' =>
        array (
            0 => __DIR__ . '/..' . '/goetas-webservices/xsd2php-runtime/src',
        ),
        'Doctrine\\Instantiator\\' =>
        array (
            0 => __DIR__ . '/..' . '/doctrine/instantiator/src/Doctrine/Instantiator',
        ),
    );
```

**Comment by ashtru** [comment]
@WestTexasGuy Thank you raising the issue.
vendor/composer/autoload_static.php is required for any file using composer autoloader.
I am closing the issue, please comment in case of any queries.
