### ISSUE TITLE
Constant version for 1.9.2 reflects 1.9.1

### ISSUE THREAD

**Issue by heddn** [AuthorizeNet/sdk-php#214]
The constant for 1.9.2 shows i'm still running 1.9.1.

**Comment by heddn** [comment]
Packagist isn't updated then. Which is an issue.

**Comment by adavidw** [comment]
looking into it...

**Comment by adavidw** [comment]
Packagist targets a specific tag/release level, which makes sense. So, we'll either need to delete and recreate the release, or rev the release number to bring everything in sync. We'll have to figure out what to do on this end.

**Comment by heddn** [comment]
With packagist, and composer, there are enough caches and mirrors that you
are better off bumping the version.

**Comment by heddn** [comment]
Also, https://github.com/AuthorizeNet/sdk-php/blob/1.9.2/lib/net/authorize/api/constants/ANetEnvironment.php still shows 1.9.1. And doing a git force push is seriously frowned upon. I don't think you have any options but to roll a new version.

**Comment by adavidw** [comment]
closing since we've upped the version num since then
