### ISSUE TITLE
Is there any BC breaks in 1.x version. Do you follow semver?

### ISSUE THREAD

**Issue by makasim** [AuthorizeNet/sdk-php#216]
Right now Payum restricts Authorize.Net library Sdk to [~1.8](https://github.com/Payum/Payum/blob/master/src/Payum/AuthorizeNet/Aim/composer.json#L24). 

That is the version I did a real test for. 

Could I make the required version softer to allow all 1.x version without the fear that it breaks something?

for ref https://github.com/Payum/Payum/issues/630

**Comment by ashtru** [comment]
The support for PHP 5.5 has been removed, as PHP 5.6 is minimum required for TLS 1.2. Authorize.Net has already [removed support for TLS1.0 and TLS 1.1 in sandbox environment](https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/TLS-1-1-and-1-0-Disabled-in-Sandbox-on-April-30-2017-Updated-2X/ba-p/57726), and it will be removed from production by February 28, 2018. If you have not migrated to TLS 1.2 yet, you can verify if your code is still working by connecting to the Authorize.Net Sandbox endpoint. 
To migrate to TLS 1.2, your system needs to follow the requirements stated [here ](https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Request-for-Comments-API-Best-Practices/ba-p/53668).  To see the version of TLS being used by your system, you can execute the following php code. For running this code, save it as a file TLSTest.php anywhere in your system, followed by executing `php TLSTest.php` in the command prompt.
```

<?php 
$ch = curl_init('https://www.howsmyssl.com/a/check');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$data = curl_exec($ch);
curl_close($ch);

$json = json_decode($data);
echo $json->tls_version;
?>

```

It's not necessary to move to version 1.9 , as long as your system is using TLS 1.2 . The sdk does not follow semver,  there are frequent releases incorporating enhancements to API features.

**Comment by ashtru** [comment]
Thank you for raising this issue. We are closing this issue. Please raise a new issue, if you’re facing any problems due to TLS or otherwise, and we’ll look into it quickly.
