### ISSUE TITLE
reason code of failed payment in ARB   [question]

### ISSUE THREAD

**Issue by sarathvsgit** [AuthorizeNet/sdk-php#217]
Hi,
Is there is any method to get the reason code of a failed payment  in ARB method.
ie if a payment failed in a ARB subscription , is there any method to track the reason of that failed payment.? Can we trigger (reattempt) the failed payment in ARB?

**Comment by rahulrnitc** [comment]
Hi @sarathvsgit , I apologize for the delay in replying. I'm trying to investigate this issue. If the ARB transaction failed, you will be able to find more information in MINT by accessing `Recurring Billing` (on the left pane) and going to `View Transaction Status Report`.  For retrying failed payments there is an option to enable Automatic retry which you can find on the MINT Recurring Billing page under settings header.

**Comment by ashtru** [comment]
Thank you for raising this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.
