### ISSUE TITLE
When doing a credit card transaction with an account that has card present transactions enabled on same account as online transactions, the $response->transaction_id returns null

### ISSUE THREAD

**Issue by urbaitel** [AuthorizeNet/sdk-php#22]
It appears to be a new issue while using $authnetcp->authorizeAndCapture().

I did a workaround for this:

if (!$response->transaction_id && $response->card_code_response)
{
	$response->transaction_id = $response->card_code_response;
}

**Comment by brianmc** [comment]
Hi @urbaitel, are you still seeing this issue?

**Comment by brianmc** [comment]
Closing this as we haven't heard back since May
