### ISSUE TITLE
Authorize.Net plans to disable TLS 1.0 and TLS 1.1

### ISSUE THREAD

**Issue by meganathan89** [AuthorizeNet/sdk-php#222]
Authorize.Net plans to disable TLS 1.0 and TLS 1.1.
How to update to TLS 1.2?
Do we need to do any changes in our script(PHP) or just needs to make changes in server end only?
Please respond anyone ASAP

**Comment by mahngiel** [comment]
>  How to update to TLS 1.2?

This lib uses cURL for transport ( see: https://github.com/AuthorizeNet/sdk-php/blob/master/lib/net/authorize/util/HttpClient.php#L68 ). You'll need to ensure you're using a recent version of cURL. 

Try this at the command line:
`php -r '$ch = curl_init( "https://www.howsmyssl.com/a/check" ); curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true ); $data = curl_exec( $ch ); curl_close( $ch ); $json = json_decode( $data ); echo $json->tls_version;'`

**Comment by dawngreen** [comment]
Can you tell me how I can confirm we are okay on Heroku using ruby?

**Comment by adavidw** [comment]
@dawngreen,

Generally, you'd just try to make a transaction using the sandbox. If you can do that, you know everything works.
