### ISSUE TITLE
For fetching credit card number last 4 digits from authroize.net

### ISSUE THREAD

**Issue by venkatcerulean** [AuthorizeNet/sdk-php#224]
Hi Team,

I want to fetch last 4 digits of credit number using ARBSubscriptionId
Can you tell me which function i need to use for fetching those details

Thanks

**Comment by ramittal** [comment]
You can use ARBGetSubscription with subscriptionId.
Response->subscription->profile->paymentprofile->payment->creditcard->cardnumber will get you the masked card number, with last 4 in clear text.

You can also use the ARBGetSubscriptionList if you want a collection of subscriptions to look at:
Response->subscriptionDetails->subscriptionDetail->accountNumber will get you the masked card number, with last 4 in clear text.

Hope this helps.
