### ISSUE TITLE
Empty response

### ISSUE THREAD

**Issue by venkatcerulean** [AuthorizeNet/sdk-php#225]
Below is my code where i am doing wrong

<?php
require_once 'AuthorizeNet.php';
define("AUTHORIZENET_API_LOGIN_ID", "xxxxxx");
define("AUTHORIZENET_TRANSACTION_KEY", "xxxxxxxx");
define("AUTHORIZENET_SANDBOX", true);
$request = new AuthorizeNetARB;
$response = $request->cancelSubscription($subscriptionId);
print_r($response);
?>

o/p:
AuthorizeNetARB_Response Object ( [xml] => [response] => )

**Comment by NexWeb** [comment]
Your server configuration should have a trusted SSL authorities list.
If you don't have the ability to modify server configurations, you can download CA bundle from Mozilla at: http://curl.haxx.se/ca/cacert.pem and save it to ./anet_php_sdk/lib/ssl/cert.pem. 
 
Prior to saving your certificate file, you can verify it's a certificate issue by changing 
public $VERIFY_PEER = true;
to
public $VERIFY_PEER = false;
in /lib/shared/AuthorizeNetRequest.php.  But you should change it back for production use.
