### ISSUE TITLE
Update README file with the latest version

### ISSUE THREAD

**Issue by fer8a** [AuthorizeNet/sdk-php#226]
I was looking at the API today and saw this endpoint that I thought would be perfect for reporting:
http://developer.authorize.net/api/reference/#transaction-reporting-get-customer-profile-transaction-list

And saw the changes were added to the code 28 days ago, I ran `composer update` but no luck fetching the necessary files for that endpoint to work, I guess not in Composer yet? Anyway just letting you know.

I added the missing contract file manually to my vendor folder as well as the missing controller file:
`GetTransactionListForCustomerController.php`

But I'm getting this error response from the API:
```
error: true,
code: "E00004",
description: "The name of the requested API method is invalid."
```

Is this not working yet, am I doing something wrong?

**Comment by ashtru** [comment]
@fer8a
Please state the version of SDK in your composer.json.
Did you change the version to 1.9.3 before the composer update?

**Comment by fer8a** [comment]
Version is 1.9.2
I'm going to update the version and run `composer update` once again. I'll let you know if it works.

P.S. Please update the README if the right version should be 1.9.3

**Comment by ashtru** [comment]
Thanks @fer8a  for raising the issue and helping us improve our SDKs.

**Comment by rahulthakral38** [comment]
Hi Ashru

Does above issue is fixed or not yet.. Kindly suggest if there is an update.

Thanks
Rahul Thakral
