### ISSUE TITLE
## Recurring Billing ##  Get Subscription  issue

### ISSUE THREAD

**Issue by phpstudyOne** [AuthorizeNet/sdk-php#229]
in [recurring-billing-get-subscription](http://developer.authorize.net/api/reference/index.html#recurring-billing-get-subscription)   page,
## Recurring Billing ## 
**Get Subscription**
response  subscription->status 	format is "Values include: active, expired, suspended, **cancelled**, or terminated." . 
but I test api , response  subscription->status is "**canceled**";

**Comment by adavidw** [comment]
Good catch. We'll fix that in the API Reference in the next build of the web site.

For anyone else looking at this, this is an issue with the documentation on our website. This isn't an issue in this SDK specifically, so this GitHub issue should be closed.

**Comment by phpstudyOne** [comment]
Yea , look fine for me.
