### ISSUE TITLE
getPaymentProfiles() in PHP SDK not returning defaultPaymentProfile

### ISSUE THREAD

**Issue by amcoho** [AuthorizeNet/sdk-php#230]
GetDefaultPaymentProfile() returns NULL when called on payment profiles returned by a call to customerProfile->getPaymentProfiles(). It should return 1 or 0 (true/false). The script attached at the bottom of this post reproduces the problem. Copy it to /sample-code-php/CustomerProfiles and run it from there. It produces an output similar to the following:

`$ php CustomerProfiles/get-customer-payment-profiles.php

Succesfully created customer profile : 1501185315
Create Customer Payment Profile SUCCESS: 1500749818
Create Customer Payment Profile SUCCESS: 1500749819
GetCustomerProfile SUCCESS :
Profile Has 2 Payment Profiles
payment profile id: 1500749819 (NULL)
payment profile id: 1500749818 (NULL)`

Where you see (NULL) it should display true and false. On a separate note, the XML logged to phplog file does not show that both payment profiles are returned when customer profile is retrieved but they obviously are as GetPaymentProfiles() returns all their details. Looks like the log is not a true reflection of all that is crossing the wire. I would appreciate if authorize.net dev team looks into both of these issues and provides a response.

`<?php
require 'vendor/autoload.php';

use net\authorize\api\contract\v1 as AnetAPI;
use net\authorize\api\controller as AnetController;

define("AUTHORIZENET_LOG_FILE", "phplog");

$customerProfile = createCustomerProfile("123@test.com");
createPaymentProfile($customerProfile->getCustomerProfileId(), "000-000-0009", true);
createPaymentProfile($customerProfile->getCustomerProfileId(), "000-000-0008");
$customerProfile = getCustomerProfile($customerProfile->getCustomerProfileId());
$paymentProfiles = $customerProfile->getPaymentProfiles();

foreach ($paymentProfiles as $paymentProfile) {
	echo 'payment profile id: ' . $paymentProfile->getCustomerPaymentProfileId(); 
	echo ' (' . var_export($paymentProfile->getDefaultPaymentProfile(), true) . ")\n";
}

function createCustomerProfile($email) {
	$merchantAuthentication = new AnetAPI\MerchantAuthenticationType();
	$merchantAuthentication->setName(\SampleCode\Constants::MERCHANT_LOGIN_ID);
	$merchantAuthentication->setTransactionKey(\SampleCode\Constants::MERCHANT_TRANSACTION_KEY);
	$refId = 'ref' . time();
	
	$customerprofile = new AnetAPI\CustomerProfileType();
	$customerprofile->setDescription("Customer 2 Test PHP");

	$customerprofile->setMerchantCustomerId("M_".$email);
	$customerprofile->setEmail($email);
	
	$request = new AnetAPI\CreateCustomerProfileRequest();
	$request->setMerchantAuthentication($merchantAuthentication);
	$request->setRefId( $refId);
	$request->setProfile($customerprofile);
	$controller = new AnetController\CreateCustomerProfileController($request);
	
	$response = $controller->executeWithApiResponse(\net\authorize\api\constants\ANetEnvironment::SANDBOX);
	if (($response != null) && ($response->getMessages()->getResultCode() == "Ok") ) {
			echo "Succesfully created customer profile : " . $response->getCustomerProfileId() . "\n";
	} else {
			echo "ERROR :  Invalid response\n";
			$errorMessages = $response->getMessages()->getMessage();
			echo "Response : " . $errorMessages[0]->getCode() . "  " .$errorMessages[0]->getText() . "\n";
	}
	return $response;
}

function createPaymentProfile($customerProfileId, $phoneNumber, $isDefaultPaymentProfile=false) {
	$merchantAuthentication = new AnetAPI\MerchantAuthenticationType();
	$merchantAuthentication->setName(\SampleCode\Constants::MERCHANT_LOGIN_ID);
	$merchantAuthentication->setTransactionKey(\SampleCode\Constants::MERCHANT_TRANSACTION_KEY);
	$refId = 'ref' . time();
	
	$creditCard = new AnetAPI\CreditCardType();
	$creditCard->setCardNumber("4242424242424242");
	$creditCard->setExpirationDate("2038-12");
	$creditCard->setCardCode("142");
	$paymentCreditCard = new AnetAPI\PaymentType();
	$paymentCreditCard->setCreditCard($creditCard);

	$billto = new AnetAPI\CustomerAddressType();
	$billto->setFirstName("Ellen".$phoneNumber);
	$billto->setLastName("Johnson");
	$billto->setCompany("Souveniropolis");
	$billto->setAddress("14 Main Street");
	$billto->setCity("Pecan Springs");
	$billto->setState("TX");
	$billto->setZip("44628");
	$billto->setCountry("USA");
	$billto->setPhoneNumber($phoneNumber);
	$billto->setfaxNumber("999-999-9999");

	$paymentprofile = new AnetAPI\CustomerPaymentProfileType();
	$paymentprofile->setCustomerType('individual');
	$paymentprofile->setBillTo($billto);
	$paymentprofile->setPayment($paymentCreditCard);
	$paymentprofile->setDefaultPaymentProfile($isDefaultPaymentProfile);

	$paymentprofilerequest = new AnetAPI\CreateCustomerPaymentProfileRequest();
	$paymentprofilerequest->setMerchantAuthentication($merchantAuthentication);

	$paymentprofilerequest->setCustomerProfileId($customerProfileId);
	$paymentprofilerequest->setPaymentProfile($paymentprofile);

	// Create the controller and get the response
	$controller = new AnetController\CreateCustomerPaymentProfileController($paymentprofilerequest);
	$response = $controller->executeWithApiResponse(\net\authorize\api\constants\ANetEnvironment::SANDBOX);
	if (($response != null) && ($response->getMessages()->getResultCode() == "Ok") ) {
			echo "Create Customer Payment Profile SUCCESS: " . $response->getCustomerPaymentProfileId() . "\n";
	} else {
			echo "Create Customer Payment Profile: ERROR Invalid response\n";
			$errorMessages = $response->getMessages()->getMessage();
			echo "Response : " . $errorMessages[0]->getCode() . "  " .$errorMessages[0]->getText() . "\n";

	}
	
	return $response;
}

function getCustomerProfile($customerProfileId) {
	$merchantAuthentication = new AnetAPI\MerchantAuthenticationType();
	$merchantAuthentication->setName(\SampleCode\Constants::MERCHANT_LOGIN_ID);
	$merchantAuthentication->setTransactionKey(\SampleCode\Constants::MERCHANT_TRANSACTION_KEY);
	$refId = 'ref' . time();

	$request = new AnetAPI\GetCustomerProfileRequest();
	$request->setMerchantAuthentication($merchantAuthentication);
	$request->setCustomerProfileId($customerProfileId);
	$controller = new AnetController\GetCustomerProfileController($request);
	$response = $controller->executeWithApiResponse( \net\authorize\api\constants\ANetEnvironment::SANDBOX);
	if (($response != null) && ($response->getMessages()->getResultCode() == "Ok") )
	{
	echo "GetCustomerProfile SUCCESS : " .  "\n";
	$profileSelected = $response->getProfile();
	$paymentProfilesSelected = $profileSelected->getPaymentProfiles();
	echo "Profile Has " . count($paymentProfilesSelected). " Payment Profiles" . "\n";

	if($response->getSubscriptionIds() != null) 
	{
		if($response->getSubscriptionIds() != null)
		{

			echo "List of subscriptions:";
			foreach($response->getSubscriptionIds() as $subscriptionid)
				echo $subscriptionid . "\n";
		}
	}
	}
	else
	{
	echo "ERROR :  GetCustomerProfile: Invalid response\n";
	$errorMessages = $response->getMessages()->getMessage();
	echo "Response : " . $errorMessages[0]->getCode() . "  " .$errorMessages[0]->getText() . "\n";
	}
	return $response->getProfile();
}
?>`

**Comment by amcoho** [comment]
Also posted to community forum at: https://community.developer.authorize.net/t5/Integration-and-Testing/getPaymentProfiles-in-PHP-SDK-not-returning/td-p/58346

Unlike Github the community forums has properly formatted the code I pasted in so you may want to take the code from there.

**Comment by gnongsie** [comment]
Hi,
I'd like to clarify how the **`Get Customer Payment Profiles`** API works. A single customer profile can have **only one** default payment profile, which is set by the merchant. The API returns a **TRUE** value in a field **`defaultPaymentProfile`** within the payment profile, if that default payment profile has been set; otherwise it will not be present for the profile. It does not send **TRUE** or **FALSE** for all profiles.
Kindly refer to the documentation [here](http://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-payment-profile) for clarity.

**Comment by amcoho** [comment]
I do not see why getPaymentProfiles() cannot return TRUE when getDefaultPaymentProfile() is called on a profile that it returns and happens to be the default payment profile.

**Comment by gnongsie** [comment]
I'm sorry. I am a little confused.
I'll list out what I know. And you can tell me what you need.

1. [**`Get Customer Profile`** API](http://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-profile) returns you the customer profile along with the list of payment profiles. If a default payment profile has been set, it will state that payment profile as default. The rest will not have the **`defaultPaymentProfile`** tag.

2. [**`Get Customer Payment Profile List`** API](http://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-payment-profile-list) will return you all the customer payment profiles that match the submitted **`searchType`**. No tagging of default payment profiles here since they do not always correspond to a single customer profile.

3. [**`Get Customer Payment Profile`** API](http://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-payment-profile) will return the customer payment profile **specified** by the customer profile ID and the customer payment profile ID. Here again, if this payment profile is default, it will state that in the **`defaultPaymentProfile`** tag. Otherwise, there will be no such tag.

4. As stated in the documentation, 

> If the payment profile has previously been set as the default payment profile, you can submit this request using customerProfileId as the only parameter. Submitting this request with only the customer profile ID will cause the information for the default payment profile to be returned if a default payment profile has been previously designated. If no payment profile has been designated as the default payment profile, failing to specify a payment profile will result in an error.

I do not recall seeing a Get Default Payment Profile API.

**Comment by amcoho** [comment]
>> Get Customer Profile API returns you the customer profile along with the list of payment profiles. **_If a default payment profile has been set, it will state that payment profile as default._** The rest will not have the defaultPaymentProfile tag.

I cannot see where defaultPaymentProfile is indicated in payment profiles returned. Note that getPaymentProfiles() call does NOT return only payment profile ids, it returns payment profile objects.

On response returned by a call to GetCustomerProfileRequest() if you do call $response->getProfile()->getPaymentProfiles() it returns all profiles but does not indicate which one is the default.

You can find getDefaultPaymentProfile() in CustomerPaymentProfileType.php. I assume if you call that method on a profile object it should work but it doesn't.

**Comment by gnongsie** [comment]
The CustomerPaymentProfileType class is designed to hold the information of one payment profile. Included as part of this information is a boolean flag that denotes whether the payment profile is a default payment profile or not. Calling the getDefaultPaymentProfile() method will return this flag for this profile. 
The method does not operate on all the payment profiles for a customer profile. So it will not return the default payment profile bit rather **if** the current payment profile is the default one or not. 
Also, if you have set one of the payment profiles as default, this flag will be TRUE. And you should be able to see that as part of the object.

**Comment by amcoho** [comment]
Did you even run/look at the test script I attached? One of the payment profiles returned is the default payment profile but calling getDefaultPaymentProfile() on it does not return TRUE.

**Comment by gnongsie** [comment]
My apologies. The **`CreateCustomerProfile API`** does **not** allow you to set the default profile and the **`GetCustomerProfile API`** does **not** return the default profile. I have corrected my comments to reflect the same.

For setting the customer profile, you have to use
1. [**`CreateCustomerPaymentProfile API`**](http://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-payment-profile) or 
2. [**`UpdateCustomerPaymentProfile API`**](http://developer.authorize.net/api/reference/index.html#customer-profiles-update-customer-payment-profile) or 
3. [**`Create a Customer Profile from a Transaction API`**](http://developer.authorize.net/api/reference/index.html#customer-profiles-create-a-customer-profile-from-a-transaction)


For retrieving this same information, you have to use 
1. [**`Get Customer Payment Profile API`**](http://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-payment-profile) or
2. [**`Get Customer Payment Profile List API`**](http://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-payment-profile-list)

**Comment by amcoho** [comment]
I know how your current API works or doesn't work. I was drawing your attention to inconsistency in your API that you need to fix. To reiterate:

You have a payment profile object which has a number of methods on it. If you return this object from any call then it is imperative that all those methods are available to be called. That's just OOP 101.

Your Get Customer Profile API returns a "collection of payment profile objects" (via a call to its getPaymentProfiles() method as shown in the test script I provided above). 

Now the method getDefaultPaymentProfile() that is available on a payment profile object returned from a call to your Get Customer Payment Profile API is not available when a payment profile object returned in the collection above! This is a defect and a major one because it defeats the whole purpose of having a getPaymentProfiles() method on Get Customer Profile API: that of being able to retrieve and inspect all payment profiles for a customer with a single call (instead of multiple calls to Get Customer Payment Profile API)

If you still do not understand the problem, please assign to the person who understands this area or escalate to a higher level of support.

**Comment by gnongsie** [comment]
I do apologize for the inconvenience. This issue has been reported to the concerned team on June 5th. Steps are underway to address this.

**Comment by ashtru** [comment]
The default profile feature was extended to all remaining CIM APIs in May 2018.  Thus, GetPaymentProfiles will return the default payment profile now.

Closing this issue, please feel free to reopen in case of any queries.
