### ISSUE TITLE
The value '' is invalid according to its datatype

### ISSUE THREAD

**Issue by bhashkar007** [AuthorizeNet/sdk-php#234]
I am using the SDK recurring subscription but getting an error message - 

> ERROR : Invalid response Response : E00003 The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:startDate' element is invalid - The value '' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:date' - The string '' is not a valid Date value.

Could anyone please help me?

**Comment by gnongsie** [comment]
Can you tell us how you are providing this value in your request? It looks like the value is empty.

**Comment by bhashkar007** [comment]
@gnongsie please see my code as below - 

```
$today = date('Y-m-d');
$paymentSchedule = new AnetAPI\PaymentScheduleType();
$paymentSchedule->setInterval($interval);
$paymentSchedule->setStartDate(new DateTime( $today ));
```

**Comment by ashtru** [comment]
This error is not reproducible.

I tried using your code segment for [create subscription](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/create-subscription.php#L30) sample code, and it ran successfully.

Can you share your full code, excluding any sensitive information?

**Comment by bhashkar007** [comment]
Thanks @ashtru 

Actually, I am developing it for Craft CMS and creating an action which will accept the Credit Card details to create subscription for an user ... here is the full code wrap within a function - 

```
	function createSubscription()
	{
		/* Create a merchantAuthenticationType object with authentication details retrieved from the constants file */
		$merchantAuthentication = new AnetAPI\MerchantAuthenticationType();
		$merchantAuthentication->setName( $this->settings->merchantId );
		$merchantAuthentication->setTransactionKey( $this->settings->transactionKey );

		// Set the transaction's refId
		$refId = 'ref' . time();

		// Subscription Type Info
		$subscription = new AnetAPI\ARBSubscriptionType();
		$subscription->setName( $this->settings->subscriptionName );

		$interval = new AnetAPI\PaymentScheduleType\IntervalAType();
		$interval->setLength( $this->settings->subscriptionLength );
		$interval->setUnit( $this->settings->subscriptionUnit );

		$today = date('Y-m-d');


		$paymentSchedule = new AnetAPI\PaymentScheduleType();
		$paymentSchedule->setInterval($interval);
		$paymentSchedule->setStartDate(new DateTime( $today ));
		$paymentSchedule->setTotalOccurrences("9999"); // an ongoing subscription
		$paymentSchedule->setTrialOccurrences("0");

		$subscription->setPaymentSchedule($paymentSchedule);
		$subscription->setAmount( $this->settings->subscriptionAmount );
		$subscription->setTrialAmount("0.00");

		$creditCardNo  = craft()->request->getPost('creditCardNo');
		$expiryMonth  = craft()->request->getPost('expiryMonth');
		$expiryYear  = craft()->request->getPost('expiryYear');
		$cardCode  = craft()->request->getPost('cardCode');

		$creditCard = new AnetAPI\CreditCardType();
		$creditCard->setCardNumber( $creditCardNo );
		$creditCard->setExpirationDate("{$expiryYear}-{$expiryMonth}");
		$creditCard->setCardCode( $cardCode );

		$payment = new AnetAPI\PaymentType();
		$payment->setCreditCard( $creditCard );
		$subscription->setPayment( $payment );

		$order = new AnetAPI\OrderType();
		//$order->setInvoiceNumber("1234354");        
		$order->setDescription( $this->settings->subscriptionAmount ); 
		$subscription->setOrder( $order ); 

		$user = craft()->userSession->getUser();

		$billTo = new AnetAPI\NameAndAddressType();
		$billTo->setFirstName( $user->firstName );
		$billTo->setLastName( $user->lastName );
		//$billTo->setCompany("");
		$billTo->setAddress( $user->memberAddress );
		$billTo->setCity( $user->memberCity );
		$billTo->setCity( $user->memberCity );
		$billTo->setState( $user->memberState );
		$billTo->setZip( $user->zipcode );
		$billTo->setCountry( "USA" );

		$subscription->setBillTo($billTo);

		$request = new AnetAPI\ARBCreateSubscriptionRequest();
		$request->setmerchantAuthentication($merchantAuthentication);
		$request->setRefId($refId);
		$request->setSubscription($subscription);
		$controller = new AnetController\ARBCreateSubscriptionController($request);

		$response = $controller->executeWithApiResponse( \net\authorize\api\constants\ANetEnvironment::SANDBOX);

		if (($response != null) && ($response->getMessages()->getResultCode() == "Ok") )
		{
			//echo "SUCCESS: Subscription ID : " . $response->getSubscriptionId() . "\n";

			$subscriptionId = $response->getSubscriptionId();
			$user->getContent()->setAttribute( array('subscriptionId', $subscriptionId) );
		}
		else
		{
			echo "ERROR :  Invalid response\n";
			$errorMessages = $response->getMessages()->getMessage();
			echo "Response : " . $errorMessages[0]->getCode() . "  " .$errorMessages[0]->getText() . "\n";
			die;
		}

		return $response;
	}
```

**Comment by bhashkar007** [comment]
Can it be an issue due to timezome setting. I set it as UTC. Thanks

**Comment by bhashkar007** [comment]
Any help ???

**Comment by ashtru** [comment]
I was able to run your provided sample, replacing calls to craft() function and $this->settings object with simple values. I was able to create a subscription, with today's date as start date.
Setting the timezone as UTC also led to a subscription being created successfully.

**Comment by ashtru** [comment]
In the request code, after setting the start date, I am able to see the startDate set in the paymentSchedule:

```
        $paymentSchedule->setStartDate(new DateTime( $today ));	
        echo  "start date:";
        print_r ($paymentSchedule->getStartDate());
        echo "\n";
```
displays
start date:DateTime Object
```
(
    [date] => 2017-06-15 00:00:00.000000
    [timezone_type] => 3
    [timezone] => UTC
)

```
What is the output in your case? Right now, it seems like a php/environment issue.

**Comment by bhashkar007** [comment]
I am also getting the same output while printing `print_r ($paymentSchedule->getStartDate());`

**Comment by bhashkar007** [comment]
Could you please give some pointer on `it seems like a php/environment issue.`

**Comment by ashtru** [comment]
If its the same output, then I would be interested in the xml request being created.
Can you share the latest the request log in your `phplog` (present in root folder of sdk) file?

**Comment by bhashkar007** [comment]
Is it possible if I can send you that `phplog` personally?

**Comment by ashtru** [comment]
Email it to ashutosh41093@gmail.com.

**Comment by bhashkar007** [comment]
`Thu, 15 Jun 2017 09:01:08 -0400 INFO : [execute] (/plugins/authorizenet/controllers/sdk/lib/net/authorize/api/controller/base/ApiOperationBase.php : 118) - Request  Serialization End
 Thu, 15 Jun 2017 09:01:08 -0400 INFO : [_sendRequest] (/plugins/authorizenet/controllers/sdk/lib/net/authorize/util/HttpClient.php : 75) -  Url: https://apitest.authorize.net/xml/v1/request.api
 Thu, 15 Jun 2017 09:01:08 -0400 INFO : [_sendRequest] (/srv/users/serverpilot/apps/rhonerangers/craft/plugins/authorizenet/controllers/sdk/lib/net/authorize/util/HttpClient.php : 77) - Request to AnetApi: 
<?xml version="1.0" encoding="UTF-8"?>
<ARBCreateSubscriptionRequest xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
  <merchantAuthentication>
    <name><![CDATA[2LZ4tb83t6]]></name>
    <transactionKey>xxxx</transactionKey>
  </merchantAuthentication>
  <clientId><![CDATA[sdk-php-1.9.3]]></clientId>
  <refId><![CDATA[ref1497531668]]></refId>
  <subscription>
    <name><![CDATA[Rhone Rangers Events Subscription]]></name>
    <paymentSchedule>
      <interval>
        <length>1</length>
        <unit><![CDATA[days]]></unit>
      </interval>
      <startDate/>
      <totalOccurrences>9999</totalOccurrences>
      <trialOccurrences>0</trialOccurrences>
    </paymentSchedule>
    <amount>1</amount>
    <trialAmount>0.00</trialAmount>
    <payment>
      <creditCard>
        <expirationDate>xxxx</expirationDate>
      </creditCard>
    </payment>
    <order>
      <description><![CDATA[1]]></description>
    </order>
    <billTo>
      <firstName><![CDATA[Bhashkar]]></firstName>
      <lastName><![CDATA[Yadav]]></lastName>
      <state><![CDATA[]]></state>
      <country><![CDATA[USA]]></country>
    </billTo>
  </subscription>
</ARBCreateSubscriptionRequest>`

**Comment by bhashkar007** [comment]
Thanks. I emailed `phplog` to you.

**Comment by ashtru** [comment]
I see the _startDate_ set properly in your request object, but **not in the serialized xml** request sent - for which I am not able to identify a root cause yet.

However, in the request object, I see some other fields are not set:
- The `state` attribute in `billTo` - can you try sending in a string here, instead of an object? And see if the output changes.

- The sample subscription has an interval of 1 day, which should raise an error similar to:
```
ERROR :  Invalid response
Response : E00022  Interval Length must be a value from 7 through 365 for day based subscriptions.
```
Can you try changing interval to 7 days or 1 month?

- Also there is no card number and card code in the card information, only expiration date. This again, would raise an error. Try something like
``` 
                $creditCardNo = "4111111111111111";
                $expiryMonth  = "12";
                $expiryYear  = "2020";
                $cardCode  = "121";

                $creditCard = new AnetAPI\CreditCardType();
		$creditCard->setCardNumber( $creditCardNo );
		$creditCard->setExpirationDate("{$expiryYear}-{$expiryMonth}");
		$creditCard->setCardCode( $cardCode );
```

**Comment by ashtru** [comment]
1. Are you able to run the [sample create subscription](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/create-subscription.php) and get a valid response?
2. If (1) succeeds, can you try to change the [sample code](https://github.com/AuthorizeNet/sample-code-php/blob/master/RecurringBilling/create-subscription.php) only using today's date for startDate. Do you get the _invalid datatype_ error ?
3. Try making changes to YOUR request code for cardnumber etc., and see if we get a valid output?

**Comment by bhashkar007** [comment]
@ashtru 
Thanks for all your inputs. Yes, I made all those changes and tested the sample code locally and it worked fine while having issue on development server :(

**Comment by rahulrnitc** [comment]
Hi @bhashkar007,
Where you able to resolve the issue with the development server?

**Comment by asadcheema7860** [comment]
I have the same issue and it was about conversion of string to in, when i used (int)$prm; before sending it to authorize.net method, It solved my problem like charm.
Thanks for reading.
