### ISSUE TITLE
Installing PHP API fails

### ISSUE THREAD

**Issue by oakcanyonstone** [AuthorizeNet/sdk-php#238]
I ran the composer install, composer update using the composer.json included in the package. It does not create any directory named vendor that I can find. Where is the installation manual for this? I have spent 3 days trying to get it to work without success. Where is the PHP API package (the one without the composer crap)?

**Comment by phpstudyOne** [comment]
[SDK](https://packagist.org/packages/authorizenet/authorizenet) page

```sh
cd /your_php_project_path
composer require authorizenet/authorizenet
```

**Comment by ashtru** [comment]
Thanks for the response, @phpstudyOne.
