### ISSUE TITLE
problema en respuesta de aip

### ISSUE THREAD

**Issue by Goodfrey** [AuthorizeNet/sdk-php#239]
Good afternoon.

I have the following problem with the authorize.net version 1.9.2 api based on php 5.5.38. When using the test credentials the response of the api is correct, but when using authorized credentials used in an application, the api response is always null ...

Code with authorized credentials.

/var/www/html/luis.924/silex/src/Controllers/PagosController.php:489:
object(net\authorize\api\contract\v1\CreateTransactionResponse)[555]
  private 'transactionResponse' =>
    object(net\authorize\api\contract\v1\TransactionResponseType)[608]
      private 'responseCode' => null
      private 'rawResponseCode' => null
      private 'authCode' => null
      private 'avsResultCode' => null
      private 'cvvResultCode' => null
      private 'cavvResultCode' => null
      private 'transId' => null
      private 'refTransID' => null
      private 'transHash' => null
      private 'testRequest' => null
      private 'accountNumber' => null
      private 'entryMode' => null
      private 'accountType' => null
      private 'splitTenderId' => null
      private 'prePaidCard' => null
      private 'messages' =>
        array (size=0)
          empty
      private 'errors' =>
        array (size=0)
          empty
      private 'splitTenderPayments' =>
        array (size=0)
          empty
      private 'userFields' =>
        array (size=0)
          empty
      private 'shipTo' => null
      private 'secureAcceptance' => null
      private 'emvResponse' => null
      private 'transHashSha2' => null
  private 'profileResponse' => null
  private 'refId' (net\authorize\api\contract\v1\ANetApiResponseType) => string 'ref1498756705' (length=13)
  private 'messages' (net\authorize\api\contract\v1\ANetApiResponseType) =>
    object(net\authorize\api\contract\v1\MessagesType)[572]
      private 'resultCode' => string 'Error' (length=5)
      private 'message' =>
        array (size=1)
          0 =>
            object(net\authorize\api\contract\v1\MessagesType\MessageAType)[585]
              ...
  private 'sessionToken' (net\authorize\api\contract\v1\ANetApiResponseType) => null

Code with test credentials.

/var/www/html/luis.924/silex/src/Controllers/PagosController.php:489:
object(net\authorize\api\contract\v1\CreateTransactionResponse)[556]
  private 'transactionResponse' =>
    object(net\authorize\api\contract\v1\TransactionResponseType)[609]
      private 'responseCode' => string '1' (length=1)
      private 'rawResponseCode' => null
      private 'authCode' => string '9100HZ' (length=6)
      private 'avsResultCode' => string 'Y' (length=1)
      private 'cvvResultCode' => string 'P' (length=1)
      private 'cavvResultCode' => string '2' (length=1)
      private 'transId' => string '60025786802' (length=11)
      private 'refTransID' => string '' (length=0)
      private 'transHash' => string '4F50A3E2AA02DFC5F6529737A81240EA' (length=32)
      private 'testRequest' => string '0' (length=1)
      private 'accountNumber' => string 'XXXX6426' (length=8)
      private 'entryMode' => null
      private 'accountType' => string 'MasterCard' (length=10)
      private 'splitTenderId' => null
      private 'prePaidCard' => null
      private 'messages' =>
        array (size=1)
          0 =>
            object(net\authorize\api\contract\v1\TransactionResponseType\MessagesAType\MessageAType)[594]
              ...
      private 'errors' =>
        array (size=0)
          empty
      private 'splitTenderPayments' =>
        array (size=0)
          empty
      private 'userFields' =>
        array (size=0)
          empty
      private 'shipTo' => null
      private 'secureAcceptance' => null
      private 'emvResponse' => null
      private 'transHashSha2' => string '' (length=0)
  private 'profileResponse' => null
  private 'refId' (net\authorize\api\contract\v1\ANetApiResponseType) => string 'ref1498756913' (length=13)
  private 'messages' (net\authorize\api\contract\v1\ANetApiResponseType) =>
    object(net\authorize\api\contract\v1\MessagesType)[573]
      private 'resultCode' => string 'Ok' (length=2)
      private 'message' =>
        array (size=1)
          0 =>
            object(net\authorize\api\contract\v1\MessagesType\MessageAType)[586]
              ...
  private 'sessionToken' (net\authorize\api\contract\v1\ANetApiResponseType) => null

I await your observations

**Comment by adavidw** [comment]
When you switch away from using the test credentials, are you changing your code to connect to the production endpoints, as explained here: https://github.com/AuthorizeNet/sdk-php#setting-production-environment ?
