### ISSUE TITLE
syntax error when loaded to server

### ISSUE THREAD

**Issue by mpushpendra** [AuthorizeNet/sdk-php#248]
syntax error when loaded to server. works fine on my local machine using xampp.

[25-Jul-2017 16:56:25 Etc/GMT] PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in <*******>/public_html/demo/website3-1/vendor/symfony/yaml/Parser.php on line 39

**Comment by adavidw** [comment]
Can you provide any more information? For example:
* What are you doing when you get that error?
* What version of PHP is on the server?
* How did you install the sdk on the server?

This error that you're getting is likely due to incompatible version of PHP on the server, but without more information from you I can't tell.

**Comment by mpushpendra** [comment]
What are you doing when you get that error? - charge credit card call using sample code
What version of PHP is on the server? - 5.6
How did you install the sdk on the server? - Copied all the files from local install to the server

**Comment by adavidw** [comment]
Can you verify for sure that the PHP version is correct? I've seen several situations where the PHP version someone thinks is installed is not the version that's actually running from the command line.

Can you either run `php -v` from the same command line you run the sample code from, or just insert a `phpinfo();` command at the beginning of the charge credit card code?

**Comment by mpushpendra** [comment]
My local Php version: 

PHP Version | 5.6.30

At server:

PHP Version | 5.4.45

**Comment by mpushpendra** [comment]
I have updated the version of PHP to 7.0 and it's working now. Thank you :)
