### ISSUE TITLE
Response issue for ARB getSubscriptionStatus 

### ISSUE THREAD

**Issue by ad2joe** [AuthorizeNet/sdk-php#25]
getSubscriptionStatus reads "Status" with a capital "S", while it should read "status", see sdk-php//lib/AuthorizeNetARB.php

They're both being sent with the response and "Status" was always "active" on my tests, while "status" had the correct value.

**Comment by pzelnip** [comment]
This is *really* confusing and misleading, since using ```getSubscriptionstatus``` results in an error.  If getSubscriptionStatus in fact is not obsolete, why spit out the note about it being obsolete?

**Comment by brianmc** [comment]
Hi @pzelnip just to be clear it's the response element Status (uppercase S) that is obsoleted, not the method itself.  
Although we hope the new method GetSubscription (http://developer.authorize.net/api/reference/#recurring-billing-get-subscription) is more useful than GetSubscriptionStatus we will continue to support this method for some time and it should not be error-ing as you suggest.  What exactly are you seeing?

Brian
