### ISSUE TITLE
How to hide "Bank Account" option on Payment Form  ?

### ISSUE THREAD

**Issue by phpstudyOne** [AuthorizeNet/sdk-php#253]
I Using the Accept Customer Hosted Form and Authorize.Net Accept Hosted so that maintaining SAQ-A level PCI compliance 。
![image](https://user-images.githubusercontent.com/11455285/29104586-354fd6b8-7cf9-11e7-8532-e3cf38d5b683.png)
![image](https://user-images.githubusercontent.com/11455285/29104610-6c27c75e-7cf9-11e7-99f6-664dda5c79e5.png)

but i want to hide the "Bank Account "  option, Can you help me ?

**Comment by adavidw** [comment]
By default, all sandbox accounts include eCheck.Net. The hosted form loads based on whatever payment types are supported on your account. Currently the hosted form does not offer parameters to show/hide a payment type supported at the account level, but that will be added in a future release. 

In the meantime, you can request that eCheck.Net be disabled on your sandbox account either by using the contact us form on the website, or mailing developer@authorize.net. Be sure to specify which sandbox gateway ID.

**Comment by phpstudyOne** [comment]
What about Production Environment accounts?

**Comment by adavidw** [comment]
It's whatever the account is signed up for. If you're signed up for checking accounts, you'll have the bank account section.

**Comment by phpstudyOne** [comment]
thank you so much for your answers. I looked at my production account and it do has the bank account section. so is it the same way to disable bank account as my sandbox ?

**Comment by adavidw** [comment]
For configuration of your production account, please contact our support department.

**Comment by phpstudyOne** [comment]
Great.
