### ISSUE TITLE
Add develop branch

### ISSUE THREAD

**Issue by texdc** [AuthorizeNet/sdk-php#26]
@brianmc Please add a `develop` branch for me to pull my [namespacing feature](https://github.com/texdc/authorize.net-sdk-php/tree/feature-namespaces) into without affecting the `master` branch.

Thanks!

**Comment by brianmc** [comment]
Hi @texdc feel free to pull into our future branch, I've also created an ideas branch which is completely clean if you would prefer to pull in there.
BTW  I realize this is not exactly a timely response, more sdk support on its way!

Brian

**Comment by texdc** [comment]
Wow!  It's been a while... I'll need to review it before I send in a PR.  Thanks.
