### ISSUE TITLE
Does this work with PHP 7?

### ISSUE THREAD

**Issue by bowenac** [AuthorizeNet/sdk-php#260]
Moved a site to a new server and this is now hanging on.
$response = $sale->authorizeAndCapture();

Server meets all requiremenets and everything is installed that needs to be. Only thing different I believe is the PHP version. Using 7.1.9

**Comment by bowenac** [comment]
Rolled new server back to 5.6.3 and it works, so apparently this isn't working with PHP 7

**Comment by adavidw** [comment]
The SDK is compatible with PHP 7 in our testing. However, there can be problems if you have a different version of one of the dependencies installed that might not be compatible with PHP 7.

If you install the SDK under PHP 7, composer takes care of getting the right versions of each dependency installed. However, if you just move a whole installation from 5.6 to a server running 7, that might not be the case.

If you moved the SDK and its "vendor" subdirectory to the new server, that could be what happened. In that case, you could delete the vendor directory and run `composer update` to get a new one.

Or, if that's not what happened, we could probably figure out the problem and tell you what to update if you post what actual errors you receive.
