### ISSUE TITLE
Missing includeIssuerInfo flag in GetCustomerPaymentProfileRequest class

### ISSUE THREAD

**Issue by travisfisher** [AuthorizeNet/sdk-php#261]
I noticed the documentation mentions a request field called "includeIssuerInfo" that is missing from the GetCustomerPaymentProfileRequest class:

[https://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-payment-profile](url)

Is this something that can be added?

Thanks.

**Comment by travisfisher** [comment]
It looks like GetCustomerProfileRequest is also missing that request field:

https://developer.authorize.net/api/reference/index.html#customer-profiles-get-customer-profile

**Comment by brianmc** [comment]
Thanks for opening this issue, we should have a release coming up in the next few weeks to pick up recent API changes such as this one.

**Comment by travisfisher** [comment]
Awesome. We'll keep an eye out for it. Thank you!

**Comment by ashtru** [comment]
@travisfisher, Thanks a lot for the pull request! There were couple of more changes required, which were included in 59f7cc5 commit. IncludeIssuerInfo change has been released as part of SDK version 1.9.4.
