### ISSUE TITLE
Error E00003 invalid  - The actual length is greater than the MaxLength value

### ISSUE THREAD

**Issue by lankasenanayaka** [AuthorizeNet/sdk-php#263]
Hi All,
I have added authorized payment gateway to my laravel 5.4 application. It some times return error, I have logged them and I found this. There is no way to find unsuccessful transactions in authorized.net admin panel.

"error_msg": "The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:expirationDate' element is invalid - The value XXXXXXXXXXXXXX is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value.

error_code : "E00003"

error_msg : "The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:address' element is invalid - The value XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value.

error_code : "E00003"

Some one please help me.
Thank you,
Lanka.

**Comment by lankasenanayaka** [comment]
Some one please help

**Comment by AzizSaleh** [comment]
What is the request body that is being sent?

**Comment by lankasenanayaka** [comment]
$merchantAuthentication = new AnetAPI\MerchantAuthenticationType();
        $merchantAuthentication->setName(env('AUTHORIZEDNET_NAME'));
        $merchantAuthentication->setTransactionKey(env('AUTHORIZEDNET_KEY'));
                
        $refId = 'ref' . time();
    
        // Create the payment data for a credit card
        $creditCard = new AnetAPI\CreditCardType();
        $creditCard->setCardNumber($request['card']);
        $creditCard->setExpirationDate($request['exp_year']."-".$request['exp_month']);
        $creditCard->setCardCode($request['cvv']);
    
        $total=number_format((float)session()->get('total'), 2, '.', '');
                
        //dd($total);
        // Add the payment data to a paymentType object
        $paymentOne = new AnetAPI\PaymentType();
        $paymentOne->setCreditCard($creditCard);
    
        // Create order information
        $order = new AnetAPI\OrderType();
        $order->setInvoiceNumber(session()->get('inv_id'));
        $order->setDescription($data['invoice_description']);
    
        // Set the customer's Bill To address
        $customerAddress = new AnetAPI\CustomerAddressType();
        $customerAddress->setFirstName($request['fname']);
        $customerAddress->setLastName($request['lname']);
        $customerAddress->setCompany($request['company']);
        $customerAddress->setAddress($request['address']);
        $customerAddress->setCity($request['city']);
        $customerAddress->setState($request['state']);
        $customerAddress->setZip($request['zip']);
        $customerAddress->setCountry($request['country']);
    
        // Set the customer's identifying information
        $customerData = new AnetAPI\CustomerDataType();
        $customerData->setType("individual");
        $customerData->setId(time());
        $customerData->setEmail($request['email']);
        $email= $request['email'];
    
        // Create a TransactionRequestType object and add the previous objects to it
        $transactionRequestType = new AnetAPI\TransactionRequestType();
        $transactionRequestType->setTransactionType("authCaptureTransaction");
        $transactionRequestType->setAmount($total);
        $transactionRequestType->setOrder($order);
        $transactionRequestType->setPayment($paymentOne);
        $transactionRequestType->setBillTo($customerAddress);
        $transactionRequestType->setCustomer($customerData);
        //$transactionRequestType->addToTransactionSettings($duplicateWindowSetting);
        //$transactionRequestType->addToUserFields($merchantDefinedField1);
        //$transactionRequestType->addToUserFields($merchantDefinedField2);
    
        // Assemble the complete transaction request
        $request = new AnetAPI\CreateTransactionRequest();
        $request->setMerchantAuthentication($merchantAuthentication);
        $request->setRefId($refId);
        $request->setTransactionRequest($transactionRequestType);
    
    
        // Create the controller and get the response
        $controller = new AnetController\CreateTransactionController($request);
        $response = $controller->executeWithApiResponse(env('AUTHORIZEDNET_URL'));

This is the php code I'm using

**Comment by lankasenanayaka** [comment]
I'm using this https://github.com/AuthorizeNet/sdk-php library and tried their sample codes, Some transactions are succeeded and some are failed see

"error_msg": "The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:expirationDate' element is invalid - The value XXXXXXXXXXXXXX is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value.",

"error_code": "E00003"

**Comment by AzizSaleh** [comment]
uncomment `dd($total);` and add `dd($request);`

That info would help.

**Comment by lankasenanayaka** [comment]
This is the sample request

array:14 [▼
  "fname" => "Test"
  "lname" => "test"
  "company" => "test"
  "address" => "tets"
  "city" => "test"
  "state" => "test"
  "zip" => "10400"
  "country" => "usa"
  "email" => "23232@sdf.com"
  "card" => "4242424242424242"
  "exp_year" => "2020"
  "exp_month" => "04"
  "cvv" => "123"
]

**Comment by lankasenanayaka** [comment]
Is this library not fully supported with php 7+  ?

**Comment by adavidw** [comment]
Hi @lankasenanayaka,

Are you sanitizing or constraining the input at all before sending it to the payment gateway? If you're just taking whatever is inputted and turning it into a request, someone could accidentally type an extra character into the expiration date field or something. If you hand that incorrect data to the SDK, the SDK doesn't do very much validation on it's own since that's something that is expected to be enforced on the frontend. If it's not and bad data gets through to the SDK, the SDK will send it to the endpoint for validation. The endpoint would enforce it and return an error.

In the case of sending too much data in a given field, the error you'll get is error E00003. The error text tells you what field is at fault, and the error message will give you the actual data _unless it's one of the fields that's considered sensitive personal information_. In that case, the data is masked with Xs like you see in your response.

> Is this library not fully supported with php 7+ ?

It is. Are you experiencing some other problem that you think is related to PHP 7?

**Comment by lankasenanayaka** [comment]
Users can't input data for expiration date because it is a select box. Any way I will look into it again.
Thank you for the reply.

**Comment by lankasenanayaka** [comment]
This is the code after I have sanitized
Backend
============================================
        $data=$this->getCheckoutDataAn();        
        $merchantAuthentication = new AnetAPI\MerchantAuthenticationType();
        $merchantAuthentication->setName(env('AUTHORIZEDNET_NAME'));
        $merchantAuthentication->setTransactionKey(env('AUTHORIZEDNET_KEY'));
        
        //echo env('AUTHORIZEDNET_NAME')." ".env('AUTHORIZEDNET_KEY')." ".env('AUTHORIZEDNET_URL');
        //dd(env('AUTHORIZEDNET_NAME'));
        // Set the transaction's refId
        $refId = 'ref' . time();
    
        // Create the payment data for a credit card
        $creditCard = new AnetAPI\CreditCardType();
        $cc=filter_var ( $request['card'], FILTER_SANITIZE_NUMBER_INT);
        $creditCard->setCardNumber($cc);

        $exp=filter_var ( trim($request['exp_year'])."-".trim($request['exp_month']), FILTER_SANITIZE_STRING);
        $creditCard->setExpirationDate($exp);

        $cvv=filter_var ( trim($request['cvv']) , FILTER_SANITIZE_STRING);
        $creditCard->setCardCode($cvv);
    
        $total=number_format((float)session()->get('total'), 2, '.', '');
        if ($request['email']=="sirisena9@gmail.com") {
            $total=1.00;
        }
        
        //dd($total);
        // Add the payment data to a paymentType object
        $paymentOne = new AnetAPI\PaymentType();
        $paymentOne->setCreditCard($creditCard);
    
        // Create order information
        $order = new AnetAPI\OrderType();
        $order->setInvoiceNumber(session()->get('inv_id'));

        $inv_des=filter_var ( trim($data['invoice_description']) , FILTER_SANITIZE_STRING);
        $order->setDescription($inv_des);
    
        // Set the customer's Bill To address
        $fname=filter_var ( trim($request['fname']) , FILTER_SANITIZE_STRING);
        $lname=filter_var ( trim($request['lname']) , FILTER_SANITIZE_STRING);
        $company=filter_var ( trim($request['company']) , FILTER_SANITIZE_STRING);
        $address=filter_var ( trim($request['address']) , FILTER_SANITIZE_STRING);
        $city=filter_var ( trim($request['city']) , FILTER_SANITIZE_STRING);
        $state=filter_var ( trim($request['state']) , FILTER_SANITIZE_STRING);
        $zip=filter_var ( trim($request['zip']) , FILTER_SANITIZE_STRING);
        $country=filter_var ( trim($request['country']) , FILTER_SANITIZE_STRING);
        

        $customerAddress = new AnetAPI\CustomerAddressType();
        $customerAddress->setFirstName($fname);
        $customerAddress->setLastName($lname);
        $customerAddress->setCompany($company);
        $customerAddress->setAddress($address);
        $customerAddress->setCity($city);
        $customerAddress->setState($state);
        $customerAddress->setZip($zip);
        $customerAddress->setCountry($country);
    
        $email=  filter_var ( trim($request['email']) , FILTER_SANITIZE_EMAIL);
        // Set the customer's identifying information
        $customerData = new AnetAPI\CustomerDataType();
        $customerData->setType("individual");
        $customerData->setId(time());
        $customerData->setEmail($email);
        
    
        // Create a TransactionRequestType object and add the previous objects to it
        $transactionRequestType = new AnetAPI\TransactionRequestType();
        $transactionRequestType->setTransactionType("authCaptureTransaction");
        $transactionRequestType->setAmount($total);
        $transactionRequestType->setOrder($order);
        $transactionRequestType->setPayment($paymentOne);
        $transactionRequestType->setBillTo($customerAddress);
        $transactionRequestType->setCustomer($customerData);
        //$transactionRequestType->addToTransactionSettings($duplicateWindowSetting);
        //$transactionRequestType->addToUserFields($merchantDefinedField1);
        //$transactionRequestType->addToUserFields($merchantDefinedField2);
    
        // Assemble the complete transaction request
        $request = new AnetAPI\CreateTransactionRequest();
        $request->setMerchantAuthentication($merchantAuthentication);
        $request->setRefId($refId);
        $request->setTransactionRequest($transactionRequestType);
    
    
        // Create the controller and get the response
        $controller = new AnetController\CreateTransactionController($request);
        $response = $controller->executeWithApiResponse(env('AUTHORIZEDNET_URL'));

Frontend
====================================================
{!! Form::text('fname', $user && isset($user->name)?$user->name:"", ['class' => 'form-control','maxlength'=>"45"]) !!} 
                                           
{!! Form::text('lname', '', ['class' => 'form-control','maxlength'=>"45"]) !!}

<label class="control-label">Company</label>
{!! Form::text('company', '', ['class' => 'form-control','maxlength'=>"45"]) !!}

<label class="control-label">Address</label>
{!! Form::text('address', '', ['class' => 'form-control','maxlength'=>"55"]) !!}

<label class="control-label">City</label>
{!! Form::text('city', '', ['class' => 'form-control','maxlength'=>"35"]) !!}

<label class="control-label">State</label>
{!! Form::text('state', '', ['class' => 'form-control','maxlength'=>"35"]) !!}

<label class="control-label">Zip</label>
{!! Form::text('zip', '', ['class' => 'form-control','maxlength'=>"20"]) !!}

<label class="control-label">Country</label>
{!! Form::text('country', '', ['class' => 'form-control','maxlength'=>"55"]) !!}

<label class="control-label">Email</label>
{!! Form::text('email', $user && isset($user->email)?$user->email:"", ['class' => 'form-control','maxlength'=>"250"]) !!}

<label class="control-label">Card Number</label>
{!! Form::text('card',"", ['class' => 'form-control',"autocomplete"=>"off",'maxlength'=>"17"]) !!} 

<label class="control-label">Expire Year</label>
{!! Form::select('exp_year', $year, '', array('class'=>'form-control','id'=> 'exp_year')) !!}

<label class="control-label">Expire Month</label>
{!! Form::select('exp_month', $month, '', array('class'=>'form-control','id'=> 'exp_month')) !!}

<label class="control-label">Cvv</label>
{!! Form::text('cvv', '', ['class' => 'form-control',"autocomplete"=>"off",'maxlength'=>"4"]) !!} 

==========================================================================
Still there is an error
=========================================================================

"error_msg": "The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:company' element is invalid - The value XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value."

"error_code": "E00003"
==========================================================================
Can someone let me know the error?

**Comment by adavidw** [comment]
The best way to troubleshoot this is to set up logging for every request so that when you do get an error, you can tell what was sent in that field to cause the error. For example, you mention you got the error with text referring to the "company" element, and the error shows that whatever you sent was 58 characters long.

So, what was sent in the "company" element? If you can identify what was sent, you can likely figure out where it's coming from.

**Comment by ashtru** [comment]
Hi @lankasenanayaka 

Were you able to resolve this issue? 

The maximum length for the company field is 50 characters ( check the _Request_ tab in the [developer reference](https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card) for the validations for different fields. )

**Comment by lankasenanayaka** [comment]
Hi @ashtru 
My suggestion is to you is try another payment gateway like stripe or paypal

**Comment by ghartsho** [comment]
Just ran into this, you may have your `LoginId` and `TransactionKey` swapped

**Comment by elpaso2** [comment]
its been over a year, but the issue is $data['invoice_description'];, the length is too much

**Comment by gb10ck** [comment]
I was having issues recording user input card number, exp, and cvv through php. The solution was to change
`$ccNumber = $_POST["creditcardnumber"];`
`$creditCard->setCardNumber("$ccNumber");`
to
`define("CCNUMBER",$_POST["creditcardnumber"]);`
`$creditCard->setCardNumber(CCNUMBER);`

**Comment by faizanyasin** [comment]
your card number is containing empty spaces, please ensure max credit card number limit
