### ISSUE TITLE
CURL request time out while processing the transaction 

### ISSUE THREAD

**Issue by ankush-maherwal** [AuthorizeNet/sdk-php#269]
On line number 92 of the file specified below the CURL request time is specified as 45 seconds which is causing request timeout. If I change it to 90 seconds then it works fine. 
/sdk-php-master/lib/shared/AuthorizeNetRequest.php

can the CURL request time be increased?

**Comment by adavidw** [comment]
It probably could, but shouldn't need to be. I think the more important question is why you wouldn't be getting a response after 45 seconds? What percentage of the time is that happening? With all requests or just a certain type? Does the request still get executed on our side? With sandbox or production?

Any logs or anything you can post to illustrate whatever problem you're experiencing?

**Comment by ankush-maherwal** [comment]
I am not getting the response in 45 seconds also this happens every time I try to make payment.

I am using sandbox mode.

Following is the logged response

{  
   "approved":false,
   "declined":null,
   "error":true,
   "held":null,
   "response_code":null,
   "response_subcode":null,
   "response_reason_code":null,
   "response_reason_text":null,
   "authorization_code":null,
   "avs_response":null,
   "transaction_id":null,
   "invoice_number":null,
   "description":null,
   "amount":null,
   "method":null,
   "transaction_type":null,
   "customer_id":null,
   "first_name":null,
   "last_name":null,
   "company":null,
   "address":null,
   "city":null,
   "state":null,
   "zip_code":null,
   "country":null,
   "phone":null,
   "fax":null,
   "email_address":null,
   "ship_to_first_name":null,
   "ship_to_last_name":null,
   "ship_to_company":null,
   "ship_to_address":null,
   "ship_to_city":null,
   "ship_to_state":null,
   "ship_to_zip_code":null,
   "ship_to_country":null,
   "tax":null,
   "duty":null,
   "freight":null,
   "tax_exempt":null,
   "purchase_order_number":null,
   "md5_hash":null,
   "card_code_response":null,
   "cavv_response":null,
   "account_number":null,
   "card_type":null,
   "split_tender_id":null,
   "requested_amount":null,
   "balance_on_card":null,
   "response":null,
   "error_message":"Error connecting to AuthorizeNet"
}

**Comment by adavidw** [comment]
It seems as if you're not making a connection at all. What version of PHP are you using? What version of OpenSSL? What version of cURL/libcurl? Are you capable of making a TLS 1.2 connection from PHP?

**Comment by adavidw** [comment]
Have you looked at the code for testing TLS 1.2 in the README?

**Comment by ankush-maherwal** [comment]
PHP Version - 7.0.24
SSL version - OpenSSL/1.0.2k
Version of cURL - 7.54.0
tlsv1.2

Also, i have tested the code provided in README file and got the response as given below.
**Connection uses TLS 1.2**

I think the connection is getting established as it works fine if I increase the CURLOPT_TIMEOUT

**Comment by ashtru** [comment]
@ankush-maherwal It seems you were able to resolve, so we are closing this issue, Please feel free to reach out in case of any other issues.

Thanks
