### ISSUE TITLE
Convert request and response to json

### ISSUE THREAD

**Issue by navneetgarggate6** [AuthorizeNet/sdk-php#270]
Is there any way to convert request or response object to JSON. So we can store it in DB or in the file for a log.

One more thing is there any way to send custom parameter to the API like product id so we can track order.

**Comment by adavidw** [comment]
Hi, there's no quick function to get the response as JSON without modifying the SDK. However, you can send and receive requests directly to our API in JSON format, so you may not even need the SDK.

See the [API Reference Guide](https://developer.authorize.net/api/reference/index.html) (particularly the "Try It" tabs).

Also in the API Reference, you can see fields to send things like invoice number which may be what you're looking for to connect to orders on your side.
