### ISSUE TITLE
ARB Subscription Request API Call missing option

### ISSUE THREAD

**Issue by zenphp** [AuthorizeNet/sdk-php#280]
Working with the recurring billing portions of the API, I am trying to retrieve recent transactions related to a subscription.  The documentation (https://developer.authorize.net/api/reference/#recurring-billing-get-subscription-status) for ARBGetSubscriptionRequest states that there is an optional parameter ```includeTransactions``` that will return recent transactions associated with the subscription.

This does not seem to be present in the PHP SDK.  Looking in the code (https://github.com/AuthorizeNet/sdk-php/blob/master/lib/net/authorize/api/contract/v1/ARBGetSubscriptionRequest.php) there is no property to store the value nor any accessors to set/retrieve the value.

Manually adding them, and updating the YML definition (https://github.com/AuthorizeNet/sdk-php/blob/master/lib/net/authorize/api/yml/v1/ARBGetSubscriptionRequest.yml) to define the property allows it to be set and transmitted, but no data appears to be returned to the client in the response.

The appropriate section of my application code:

```
        $subscription = new AnetAPI\ARBGetSubscriptionRequest();
        $subscription->setSubscriptionId($subid);
        $subscription->setRefId($refId);
        $subscription->setMerchantAuthentication($merchantAuthentication);
        $subscription->setIncludeTransactions(true);

        $controller = new AnetController\ARBGetSubscriptionController($subscription);
        $target = self::getAuthNetEnvTarget();
        $response = $controller->executeWithApiResponse($target);
```

Am I missing something?  Or is the API missing something?

**Comment by adavidw** [comment]
Looks like you'd also need to add a getter to get the `arbTransactions` element out of the `ARBSubscriptionMaskedType` in ARBSubscriptionMaskedType.php and ARBSubscriptionMaskedType.yml

**Comment by enterlight** [comment]
@zenphp did you get this to work?  Would you share your code please? I need help.  Did you create a arbTransactionsListType class and a arbTransactionType?

**Comment by zenphp** [comment]
@enterlight I have not had a chance to circle back on this.  Will try to do so this weekend and let you know where I end up.

**Comment by sjordan1975** [comment]
I suspect that includeTransactions support has been implemented in the underlying Authorize.net API; however, the PHP SDK is woefully out of date. And no sample code has been forthcoming from Authorize.net (earliest request is from June 2016)

So, For my purposes, I forked the PHP SDK:
https://github.com/sjordan1975/sdk-php

I implemented get ARB Transaction from Get Subscription sufficient for what I needed.

Specifically, I modified the following 4 files:
lib/net/authorize/api/contract/v1/ARBGetSubscriptionRequest.php
lib/net/authorize/api/contract/v1/ARBSubscriptionMaskedType.php
lib/net/authorize/api/yml/v1/ARBGetSubscriptionRequest.yml
lib/net/authorize/api/yml/v1/ARBSubscriptionMaskedType.yml

Note: I have used TransactionDetailsType whereas I suspect the actual type should be something like ARBTransactionType, but the yaml definition is missing and I have not defined it

The result is for now is not all transaction data is populated; HOWEVER, transId IS populated and this is good enough to make an additional API call to get Transaction Details.



Feel free to have at it. Code provided AS IS to the Community. YMMV

**Comment by zenphp** [comment]
I've finally worked with  what @sjordan1975 provided and cleaned things up.  I am using this code in production right now, and have submitted a PR to have it included in the base api.

https://github.com/CGX-Development/sdk-php/tree/dev-1.9.4

**Comment by ashtru** [comment]
includeTransactions has been added to the ARBGetSubscription request as part of the latest release!
Kindly change your composer.json to use version 1.9.5 of authorizenet/authorizenet similar to the sample code composer.

**Comment by enterlight** [comment]
This is great news!! Thanks
