### ISSUE TITLE
class AuthorizeNetPayment issue?

### ISSUE THREAD

**Issue by abolabo** [AuthorizeNet/sdk-php#283]
Hi guys.
Can you suggest how to send opaqueData as described here https://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-payment-profile
from AuthorizeNetPayment class? https://github.com/AuthorizeNet/sdk-php/blob/46df374abdf2dffa7b5935086f0ca3e7123b0585/lib/shared/AuthorizeNetTypes.php#L84

As i see your class do not supports opaqueData at all but manual says it must

**Comment by brianmc** [comment]
@HeathNaylor  is correct.  This example in the PHP sample code shows the usage of opaqueData to create a customer profile:  https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/create-customer-profile-with-accept-nonce.php 

We get that documentation fixed as well.
