### ISSUE TITLE
Incorrectly formatted amount throws connection error

### ISSUE THREAD

**Issue by pavelsc** [AuthorizeNet/sdk-php#285]
When passing amount like this `[amount] => '10.416666666667'` SDK throws an error message _Error connecting to AuthorizeNet_ which is quite confusing.

    AuthorizeNetAIM_Response Object
    (
    [_response_array:AuthorizeNetAIM_Response:private] => Array
        (
        )
    [approved] => 
    [declined] => 
    [error] => 1
    [held] => 
    [response_code] => 
    [response_subcode] => 
    [response_reason_code] => 
    [response_reason_text] => 
    [authorization_code] => 
    [avs_response] => 
    [transaction_id] => 
    [invoice_number] => 
    [description] => 
    [amount] => 
    [method] => 
    [transaction_type] => 
    [customer_id] => 
    [first_name] => 
    [last_name] => 
    [company] => 
    [address] => 
    [city] => 
    [state] => 
    [zip_code] => 
    [country] => 
    [phone] => 
    [fax] => 
    [email_address] => 
    [ship_to_first_name] => 
    [ship_to_last_name] => 
    [ship_to_company] => 
    [ship_to_address] => 
    [ship_to_city] => 
    [ship_to_state] => 
    [ship_to_zip_code] => 
    [ship_to_country] => 
    [tax] => 
    [duty] => 
    [freight] => 
    [tax_exempt] => 
    [purchase_order_number] => 
    [md5_hash] => 
    [card_code_response] => 
    [cavv_response] => 
    [account_number] => 
    [card_type] => 
    [split_tender_id] => 
    [requested_amount] => 
    [balance_on_card] => 
    [response] => 
    [error_message] => Error connecting to AuthorizeNet
    )

**Comment by ashtru** [comment]
It seems you were not able to connect to the Authoize.Net endpoint.

1. Is it happening only in case of certain amount?
2. Please share the log in your **phplog file** which will be in the root folder of your SDK, as it would provide further details.

**Comment by ashtru** [comment]
Hi @pavelsc 
Apologies for not being able to reply to the issue.

It seems you were not able to connect to the Authoize.Net endpoint.

1. Is it happening only in case of certain amount?
2. Please share the log in your **phplog file** which will be in the root folder of your SDK, as it would provide further details.

**Comment by chsriniv9** [comment]
Hi @pavelsc 

Could you please share the details of the request in addition to ashtru

Thanks,

**Comment by chsriniv9** [comment]
Closing this as there are no further updates from @pavelsc
