### ISSUE TITLE
Incompatible with symfony v4, using abandoned xsd2php package

### ISSUE THREAD

**Issue by jdavidbakr** [AuthorizeNet/sdk-php#286]
I am upgrading an existing Laravel project to version 5.6 which requires Symfony 4.0 instead of 3.2.  There is a dependency in this package for `goetas/xsd2php:^2.0` which in turn requires symfony 2.1 or 3.0.  I do see that the `xsd2php` package doesn't have a current version to support Symfony 4.0, so not sure how easy of a fix this is, but the lack of support for this is hampering my ability to update my systems.

**Comment by jdavidbakr** [comment]
`Package goetas/xsd2php is abandoned, you should avoid using it. Use goetas-webservices/xsd2php instead.`

**Comment by jdavidbakr** [comment]
Is Authorize.net still maintaining this package?

**Comment by jdavidbakr** [comment]
My bad, issue was with another package. 🤦‍♂️

**Comment by ashtru** [comment]
We are glad that you were able to resolve the issue, @jdavidbakr .

Can you also share the package that was causing this issue, so that it can help other developers who might have a similar issue in the future?

Thanks
Ashutosh
