### ISSUE TITLE
Line items invalid

### ISSUE THREAD

**Issue by jdavidbakr** [AuthorizeNet/sdk-php#297]
Getting "Line item 1 is invalid" when using AuthorizeNetAIM::addLineItem().  The preg_replace needs to have the pipe character escaped.  Fixed in https://github.com/AuthorizeNet/sdk-php/pull/296

**Comment by ashtru** [comment]
Thank you for raising the issue , @jdavidbakr. We will look into the PR soon.

**Comment by gauthierm** [comment]
This has been broken since July -> https://github.com/AuthorizeNet/sdk-php/commit/272c21d904dcac0c8147a5bbddd68578b4dee9b1#diff-646beabfcc1cbcd6e7daaa3e9e8abe38

**Comment by gauthierm** [comment]
Referenced PR can be improved by using str_replace instead of preg_replace.

**Comment by gauthierm** [comment]
The AIM tests included in the repo should have caught this since they use `addLineItem()`. Are the tests run before making a release?

Some unit tests for the generated AIM request would be a great addition.

**Comment by rhldr** [comment]
@jdavidbakr  The AIM integration method is deprecated which is why these older files are not maintained.

**Comment by ashtru** [comment]
Fixed with #312 . Again, thanks for your inputs and pull request, @jdavidbakr  👍

**Comment by kuflievskiy** [comment]
@ashtru, great news! Could you please tell when do you plan to release version 1.9.7? Thank you in advance.

**Comment by ashtru** [comment]
@kuflievskiy Version 1.9.7 is released today!

One more thing I wanted to add was that [AuthorizeNetAIM.php](https://github.com/AuthorizeNet/sdk-php/blob/master/lib/AuthorizeNetAIM.php) is the old method of integrating to the APIs. This method will soon be deprecated, and won't have newer updates released after 1.9.7.

You can check our [sample codes](https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-credit-card.php) repository to see the latest method provided by SDKs which are fully in sync with the latest updates to our APIs (refer: [API reference](https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card)). The [controller ](https://github.com/AuthorizeNet/sdk-php/tree/master/lib/net/authorize/api/controller)and [contract ](https://github.com/AuthorizeNet/sdk-php/tree/master/lib/net/authorize/api/contract/v1)classes, being autogenerated, have less errors and are actively supported by us.
