### ISSUE TITLE
Empty API responses: bundled cert.pem is invalid for new sandbox SSL certificate

### ISSUE THREAD

**Issue by schmich** [AuthorizeNet/sdk-php#301]
All sandbox Authorize.net API requests (at least those using `AuthorizeNetCIM`) are failing and returning empty responses:

```php
object(AuthorizeNetCIM_Response)#631 (2) {
  ["xml"]=>
  NULL
  ["response"]=>
  bool(false)
}
```

I tracked this down to a cURL error in [`AuthorizeNetRequest.php`](https://github.com/AuthorizeNet/sdk-php/blob/60cf943cc68772e01164d527c47a8f7f394ab0d6/lib/shared/AuthorizeNetRequest.php#L113): "Peer's Certificate issuer is not recognized." with the endpoint being `https://apitest.authorize.net/xml/v1/request.api`.

It appears the SSL cert for `apitest.authorize.net` was updated recently:

![image](https://user-images.githubusercontent.com/1562839/37859195-c28f0dd8-2ecd-11e8-8da7-1e91d5594410.png)

The issuing CA, GeoTrust RSA CA 2018, is not included in this library's [`cert.pem`](https://github.com/AuthorizeNet/sdk-php/blob/60cf943cc68772e01164d527c47a8f7f394ab0d6/lib/ssl/cert.pem), which is used to [configure cURL](https://github.com/AuthorizeNet/sdk-php/blob/60cf943cc68772e01164d527c47a8f7f394ab0d6/lib/shared/AuthorizeNetRequest.php#L97). Because of this, host verification fails, so requests are failing.

I saw this issue was also brought up on the [developer support forum](https://community.developer.authorize.net/t5/Integration-and-Testing/SSL-Certificate-Problem-Another-Authorize-net-Outage/td-p/62246). It appears the [temporary workaround](https://community.developer.authorize.net/t5/Integration-and-Testing/SSL-Certificate-Problem-Another-Authorize-net-Outage/m-p/62281#M36637) is to copy [cURL's cert.pem](http://curl.haxx.se/ca/cacert.pem) over the library's version.

Unfortunately, I haven't seen an official response from any Authorize.net folks.

If possible, I would like to see the following:

1. An acknowledgement of this problem, ideally along with an ETA on when you will publish a fixed version of this library.
2. Updates to [`AuthorizeNetRequest.php`](https://github.com/AuthorizeNet/sdk-php/blob/60cf943cc68772e01164d527c47a8f7f394ab0d6/lib/shared/AuthorizeNetRequest.php) to fail with more information than just `["xml"]=> NULL ["response"]=> bool(false)`. I realize you have logging there, but including and propagating cURL error information to the API consumer can only help users that hit issues.
3. Internal process improvements to prevent this from happening again. Apparently, a [similar problem happened in 2015](https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Authorize-Net-Begins-Infrastructure-and-SHA-2-Certificate/bc-p/50150#M438) resulting in similar confusion and frustration.

I'm sincerely not trying to be a jerk, but I do expect much more from an organization like Authorize.net. I (and likely others) burned far too much time today debugging and diagnosing something that should have never been an issue.

**Comment by ashtru** [comment]
We apologize for the serious inconvenience faced by all the Sandbox developers.

1. The issues is caused by the change in the certificate used for verification. We will release a fix for the SDK by 25th March.
2. This is a great suggestion, we will look into adding this information.
3. We will surely put in a process for any certificate updates and release them in time, so that no such issues occur in future.
 
Thanks again for your useful suggestions @schmich

**Comment by ashtru** [comment]
The issue has been fixed in latest release of the **PHP SDK (version [ 1.9.6](https://github.com/AuthorizeNet/sdk-php/tree/))** .

_Join the [Authorize.Net developer forum](https://community.developer.authorize.net/) to keep abreast with latest features and contribute ideas.
Thanks
Ashutosh_

**Comment by schmich** [comment]
Thanks, Ashutosh, for the quick turnaround, and on the weekend, no less. I appreciate the support and the response!

**Comment by phpstudyOne** [comment]
@ashtru 你好,我注意到发布的新版本 (version 1.9.6) 需要的 php 版本为 5.6   .

**Comment by ashtru** [comment]
@phpstudyOne , for this change, you can replace your lb/ssl/cert.pem with the latest [cert.pem](https://github.com/AuthorizeNet/sdk-php/blob/master/lib/ssl/cert.pem) manually. 

But for TLS 1.2, you will need to upgrade your PHP version to at least 5.6. 
**Kindly verify your integration works with the sandbox endpoint as soon as possible. Follow the steps in [TLS section](https://github.com/AuthorizeNet/sdk-php#tls-12) in the README. TLS below 1.2 is already disabled in sandbox, and will be soon disabled in production for all merchants.**

The minimum software requirements are as follows, you might need to upgrade all of them:
```
PHP >= 5.6
OpenSSL >= 1.0.1
CURL >= 7.34.0
```
You can go through the forum [thread](https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Request-for-Comments-API-Best-Practices/ba-p/53668) and the [news](https://support.authorize.net/s/article/Authorize-Net-Support-for-SSL-TLS-FAQ#API) for reference.

Feel free to open a new issue, if you need any more TLS 1.2 related assistance or clarification.

**Comment by phpstudyOne** [comment]
@ashtru  This is my test result : 

![image](https://user-images.githubusercontent.com/11455285/37952155-76bb16b6-31d1-11e8-9755-0979520eff36.png)


Also, when I do not replace the 'lib/ssl/cert.pem' file with a new cert.pem file, if my cert and domain name match, sanbox can be used normally. Otherwise, the error `CURL ERROR: SSL certificate problem: unable to get local issuer certificate` will occur.

**Comment by ashtru** [comment]
@phpstudyOne  
**It is good** that the connection is using TLS 1.2.
Just for some additional information, can you share the version for PHP, Openssl and curl as well?

**Comment by phpstudyOne** [comment]
@ashtru  sure.

this is `phpinfo()` result:

![image](https://user-images.githubusercontent.com/11455285/38016780-a7b87cd2-32a2-11e8-9051-38c3812d18ec.png)

![image](https://user-images.githubusercontent.com/11455285/38016800-bae77d1c-32a2-11e8-9f82-8bea5e5e3be3.png)

![image](https://user-images.githubusercontent.com/11455285/38016818-cfd6c368-32a2-11e8-92ea-5af571b0b747.png)
