### ISSUE TITLE
Error getting Valid response from API. Check log file for error details

### ISSUE THREAD

**Issue by vishalpawar-tudip** [AuthorizeNet/sdk-php#308]
Hello Team,

I am using authorizenet/authorizenet : 1.8.4 library. On the production server, we are getting the "Error getting Valid response from API. Check log file for error details" at ApiOperationBase.php line 122.

It was working good till yesterday, but now I am getting above error.

Please help me out from this issue.

Thanks.

**Comment by AndyNicholls** [comment]
I am getting the same issue. My site was working until this morning. I re-downloaded 1.9.6, but it still doesn't work.

Error details - Error getting valid response from api. Check log file for error details in /home/rwaxi2gjqbhq/public_html/sdk-php-master/lib/net/authorize/api/controller/base/ApiOperationBase.php at Line 126

Trace: #0 /home/rwaxi2gjqbhq/public_html/sdk-php-master/lib/net/authorize/api/controller/base/ApiOperationBase.php(104): net\authorize\api\controller\base\ApiOperationBase->execute('https://api.aut...') #1 /home/rwaxi2gjqbhq/public_html/app/AuthorizeNet.php(141): net\authorize\api\controller\base\ApiOperationBase->executeWithApiResponse('https://api.aut...') #2 /home/rwaxi2gjqbhq/public_html/app/CheckoutController.php(94): AuthorizeNet->chargeCreditCard('30.00') #3 /home/rwaxi2gjqbhq/public_html/app/CheckoutController.php(118): CheckoutController->processPayment() #4

**Comment by cooleydw494** [comment]
Same here. I am just starting to integrate though so I can't say if it was working before like several other people with this problem. There are a few other threads that suggest the issue has to do with TLS 1.2, and possibly firewalls blocking it. I have not resolved my own issue yet though.

**Comment by kkew** [comment]
I am also receiving this same issue.  Was there any resolution other than upgrading to 1.9.6?

**Comment by cooleydw494** [comment]
I finally got around it. For me it was an issue of the environment in the examples not working. Instead I found these on the API Reference.

Sandbox API Endpoint: https://apitest.authorize.net/xml/v1/request.api

Production API Endpoint: https://api.authorize.net/xml/v1/request.api

worked like a charm. I don't know why the examples have outdated environment constants.
(something like \net\something\constants\something::SANDBOX is in the examples, and points to a different address)

**Comment by kkew** [comment]
I found that if I adjust the PRODUCTION constant from https://api.authorize.net to https://api2.authorize.net it appears to work.  I also tried adjusting to the cooleydw494 suggestion of https://api.authorize.net/xml/v1/request.api and that didn't work either.  I'm confused as the documentation in authroize.net clearly states that the suggested url should work.

**Comment by cooleydw494** [comment]
Ahhh, I am using sandbox right now so I can't confirm that would have worked in my case either. It did for sandbox though!

**Comment by vishalpawar-tudip** [comment]
Hey @cooleydw494,

Can you please check it using production environment and please let us know?

Using sandbox it works well on our end as well but not with production endpoint.

Thanks.

**Comment by anuragg29** [comment]
Please check the below post 

https://community.developer.authorize.net/t5/News-and-Announcements/SSL-Certificate-Updates-for-Legacy-SDKs/m-p/62935#M207

**Comment by AndyNicholls** [comment]
I fixed the issue by copying all the certificate information from https://github.com/activemerchant/active_merchant/blob/master/lib/certs/cacert.pem and using it to replace lib/ssl/cert.pem in the SDK.

@anuragg29 - Why does the post refer to the PHP SDK as a "legacy" SDK?

**Comment by chsriniv9** [comment]
As older version of sdk refers to the endpoints mentioned in the post where newer certificates were needed, hence term legacy was used.
