### ISSUE TITLE
Class net\authorize\api\contract\v1\ArbTransactionType does not exist

### ISSUE THREAD

**Issue by PauloPeres** [AuthorizeNet/sdk-php#318]
When you add the  `includeTransactions` on the `ARBGetSubscriptionRequest`, and there is an existing arbTransactions related to the Subscription i get the error.
`Class net\authorize\api\contract\v1\ArbTransactionType does not exist`
Updated to latest version of the SDK, and checked the file is corrected placed and exists, are any of you having the same problem?

**Comment by PauloPeres** [comment]
Sorry guys.... For some reason my Autoloader was not finding the file, i did some update on the composer and worked, sorry for the trouble.

**Comment by ashtru** [comment]
That's good to hear.
FYI, we are deprecating the custom autoload.php. 
Always , use the `vendor/autoload.php` **generated** from composer, and 
run `composer update` if there are any changes to 
 - SDK,
 - PHP version being used locally, or
 - New namespaces added by you in your client code.
