### ISSUE TITLE
Getter and setter inconsistencies

### ISSUE THREAD

**Issue by bjcullinan** [AuthorizeNet/sdk-php#32]
This project is incredibly inconsistent.  For the AuthorizeNetAIM class, properties can be set magically or using the setField() function.  On the response properties are accessed directly without getter functions.

On the AuthorizeNet_Subscription() class, properties are set directly without setters.  On the AuthorizeNetARB_Response class, there are getter methods for all the properties.

Can you please unify and standardize this across all classes?

**Comment by brianmc** [comment]
Hi @bjcullinan, our new model should be very consistent, between request/response, across methods and with the API itself.  We have sacrificed some language features but we feel like the increased consistency with the API & reduction in SDK logic will ultimately make for a better developer experience.  You can check out our complete sample code repo here : https://github.com/AuthorizeNet/sample-code-php

Thank-you again for the feedback,

Brian
