### ISSUE TITLE
Check valid card details

### ISSUE THREAD

**Issue by suneel11** [AuthorizeNet/sdk-php#326]
hello 
How can I check weather the  card number and cvv is valid or not, with the anet api.

**Comment by ashtru** [comment]
Hi @suneel11 
Are you using this info for a one time transaction or creating a subscription?

**Comment by suneel11** [comment]
I am using it for one time transaction
I just want to check the card details at the time when I type the number not at the time of transaction.

**Comment by ashtru** [comment]
One way to do this is to take the card information and billing address, and **create a customer profile** in **_liveMode_**.
Sample Request:
```
<createCustomerProfileRequest xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"> 
   <merchantAuthentication>
     <name>78BZ5Xprry</name>
     <transactionKey>8s2F95Q7brhHd7Tn</transactionKey>
    </merchantAuthentication>
   <profile>
     <merchantCustomerId>Merchant_Customer_ID</merchantCustomerId>
     <description>Profile description here</description>
     <email>customer-profile-email1011@here.com</email>
     <paymentProfiles>
       <customerType>individual</customerType>
       <billTo>
             <firstName>John</firstName>
             <lastName>Doe</lastName>
             <company></company>
             <address>123 Main St.</address>
             <city>Bellevue</city>
             <state>WA</state>
             <zip>98004</zip>
             <country>USA</country>
             <phoneNumber>000-000-0000</phoneNumber>
             <faxNumber></faxNumber>
        </billTo> 
        <payment>
          <creditCard>
            <cardNumber>4111111111111111</cardNumber>
            <expirationDate>2020-12</expirationDate>
          </creditCard>
         </payment>
      </paymentProfiles>
    </profile>
	<validationMode>liveMode</validationMode>
  </createCustomerProfileRequest>
```
LiveMode does a _zero dollar auth_ against the card info. Please note that **billTo** must be passed for liveMode.

**Comment by xcelance** [comment]
hello @ashtru

I have checked but it use to provide me the authentication only if I proceed to pay. 
But I need to check the details of the card before the payment. And for that It is not authenticating cvv no and the expiry date. I am currently implementing it with the Laravel framework.

**Comment by ashtru** [comment]
Instead of the _Pay_ button in your UI, you can have a _Check credit card_ button
On click of which:
1.  Create a customerprofile with validationMode set to _liveMode_ . 
     This only creates a customer profile, **does not do a transaction**.

2. Delete the create customer profile (since, you are not save the card details yet)

For the code, refer [create-customer-profile sample](https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/create-customer-profile.php) . In this code, you have to set the validationMode by adding something like:
`$request->setValidationMode("liveMode");`
in **[line 88](https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/create-customer-profile.php#L88)**.


**Have you tried testing the xml given above in the _Try It_ tab of the [API Reference](https://developer.authorize.net/api/reference/#customer-profiles-create-customer-profile), and using your merchant credentials for _merchantAuthentication_ field?**

**Comment by suneel11** [comment]
Hello Ashutosh

Greetings of the day!!


Is there any way in the Authorize Net api to check weather the card has
sufficient funds or not.
I have to check that weather the card has sufficient amount in first step
and if it does not then it will not proceed to the next step. And if the
card has sufficient funds then it can charge the amount.

I am stuck in this process as I am not getting any idea how to check this.


Thanks & Regards.

**Comment by suneel11** [comment]
Hello any one there please help me with this.

**Comment by gnongsie** [comment]
Hi @suneel11 ,

To answer your original question, you **cannot** check if a credit card number and/or CVV is valid or not.

For your subsequent question, you can check if a card has sufficient balance or not by [creating an AuthorizedOnly transaction](https://developer.authorize.net/api/reference/index.html#payment-transactions-authorize-a-credit-card) which you can capture later using the [Capture A Previously Authorized Amount API](https://developer.authorize.net/api/reference/index.html#payment-transactions-capture-a-previously-authorized-amount).

**Comment by chsriniv9** [comment]
@suneel11 
Based on the inputs provided by @gnongsie closing this issue. Please feel free to re-open if you need any further assistance.
