### ISSUE TITLE
Leftover test merchant auth credentials

### ISSUE THREAD

**Issue by arkamax2k** [AuthorizeNet/sdk-php#331]
It would be good to remove them from the future releases as well but now that those are leaked out, they better be disabled. 

https://github.com/AuthorizeNet/sdk-php/blob/0cb549416580900e12df984ccf6731ba710397c0/lib/net/authorize/api/controller/base/ApiOperationBase.php#L120

**Comment by ashtru** [comment]
These are test credentials, they are supposed to public. 
This line only shows an example of _xmlRequest_ returned from the api.

**Comment by arkamax2k** [comment]
OK, I'm not familiar with Auth.net SDK per se, but usually test creds are provided on a per-user basis and are specific to that user's sandbox - so this just looked different from my past experience with other SDKs and sandboxes. Feel free to close the case if this is by design.

**Comment by ashtru** [comment]
These are **default credentials**, that work in **Sandbox** environment.
These are just for testing out the APIs, before the merchant has registered, and doesn't have production or sandbox credentials yet.

You can check out the `Try It` /`API Live Console` tab for any API in the API Reference [here ](https://developer.authorize.net/api/reference/index.html#payment-transactions-debit-a-bank-account).
