### ISSUE TITLE
check for the sufficient funds / set payment in pending state

### ISSUE THREAD

**Issue by xcelance** [AuthorizeNet/sdk-php#334]
Hello,

I just want to know that weather the AuthorizeNet api provide any option to check weather the card has sufficient balance or not. If so please let me know I am not getting any way for that.

And also how I can set the payment in pending process and can be approved when the client approve it. And till it is not approved the payment will not be made from card and if declined there will be no deduction of amount from card.
Please help me with these issues.

Thanks & Regards

**Comment by gnongsie** [comment]
Hi @xcelance 

Thank you for coming to us with this question.

To answer you, you can check if a card has sufficient balance or not by [creating an AuthorizedOnly transaction](https://developer.authorize.net/api/reference/index.html#payment-transactions-authorize-a-credit-card) which you can capture later using the [Capture A Previously Authorized Amount API](https://developer.authorize.net/api/reference/index.html#payment-transactions-capture-a-previously-authorized-amount). 

This will work for most of your requirements. But we do not have the functionality to capture the amount based on approval from a client.

**Comment by chsriniv9** [comment]
@xcelance 
Based on the inputs provided by @gnongsie closing this issue. Please feel free to re-open if you need any further assistance.
