### ISSUE TITLE
HostedProfileIFrameCommunicatorUrl is not working any more?

### ISSUE THREAD

**Issue by tylertesting1** [AuthorizeNet/sdk-php#336]
Hi there,

I had a problem with API today: 

https://developer.authorize.net/api/reference/features/customer_profiles.html#Payment_Profiles

It used to work fine. But it failed to redirect to HostedProfileIFrameCommunicatorUrl today!

Can anyone help me?

Thanks,
Tyler Deng

**Comment by glo-arandazzo** [comment]
I have the same issues

**Comment by glo-arandazzo** [comment]
I am using the popup.js code, and have been for a couple of years. Sometime last night or this morning, it stopped working. The iFrame comes up blank and doesn't give any errors either in the frame or within my javascript console. I can see it loading a bunch of assets from secure.authorize.net without any errors. Any ideas?

<img width="464" alt="screen shot 2018-09-20 at 2 29 17 pm" src="https://user-images.githubusercontent.com/29925771/45839247-d448bb80-bce1-11e8-9eaf-3339c3cbb867.png">


<img width="667" alt="screen shot 2018-09-20 at 2 30 44 pm" src="https://user-images.githubusercontent.com/29925771/45839240-cf840780-bce1-11e8-99dc-390dd59a2bd0.png">

**Comment by glo-arandazzo** [comment]
I did try change from secure.authorize.net to accept.authorize.net and the same issues persist. Here is output from the authorize.net server. IT appears to be missing the form code. 
<img width="1032" alt="screen shot 2018-09-20 at 2 43 51 pm" src="https://user-images.githubusercontent.com/29925771/45839993-d6137e80-bce3-11e8-8129-b58783ad969f.png">

**Comment by phpstudyone** [comment]
Hi, @ashtru I have the same problem as them.  @tylertesting1  @glo-arandazzo 
hostedProfileIFrameCommunicatorUrl:
```js
function callParentFunction(str) {
            var referrer = document.referrer;
            var s = {qstr : str , parent : referrer};
            if(str == 'action=cancel'){
                //TODO....
            }

            if(str == 'action=successfulSave'){
               //TODO....
            }
        }

function receiveMessage(event) {
    console.log(event);
     if (event && event.data) {
          callParentFunction(event.data);
     }
}
```
**_Expected behavior_**: 

![image](https://user-images.githubusercontent.com/11455285/45865809-463c0600-bdb1-11e8-872e-aa744e812a30.png)

**_Actual behavior_**:

![image](https://user-images.githubusercontent.com/11455285/45865843-68358880-bdb1-11e8-81f2-7495e887d497.png)

**Comment by tylertesting1** [comment]
Hi @ashtru , the screenshot above is just the same case I have.
Don't know why the response data is empty instead of `action=sucessfulSave`.
Tell me if you need any other detail information from me.

Thank you.

**Comment by glo-arandazzo** [comment]
Anyone have any news on this?

**Comment by glo-arandazzo** [comment]
Anyone?? Any updates?

**Comment by jfkrueger** [comment]
I'm using the .NET Hosted Accept solution and have the exact same issue with the addPayment not populating the shadowbox. I get the exact same blank white box as the other users. Nothing changed in our code and it has been working for years, it just stopped working recently (i'm guessing at the same time as everyone else). 

We get the blank white box in IE & Edge but in chrome the form comes back but the shadowbox is not sized correctly.

We really need a solution (IE Authorize.Net needs to fix this). This is a huge problem.

**Comment by glo-arandazzo** [comment]
Just curious if anyone has gotten this working.

**Comment by glo-arandazzo** [comment]
Hey @jfkrueger @tylertesting1 @phpstudyone  -- have any of you guys gotten this working?

Thanks,

Adam

**Comment by chsriniv9** [comment]
Hi @jfkrueger @tylertesting1 @phpstudyone @glo-arandazzo 

Based on earlier post closing this issue for now, please feel free to re-open for any support needed on this issue.

Thanks,
