### ISSUE TITLE
When will new certs be used on production?

### ISSUE THREAD

**Issue by HeathNaylor** [AuthorizeNet/sdk-php#339]
According to [this post](https://community.developer.authorize.net/t5/News-and-Announcements/SSL-Certificate-Updates-for-Legacy-SDKs/m-p/62935/highlight/true#M207), a new set of certs is required for legacy SDKs. I am wondering what is considered Legacy SDK's, is it anything prior to [this commit](https://github.com/AuthorizeNet/sdk-php/commit/444aeb818f02cc27cf56bfe1493f531c3ba56e0c)?

Additionally, according to [this post](https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Important-Authorize-Net-Networking-Change/ba-p/51272) we started using `api2.authorize.net` for our endpoints, which contradicts with the [official documentation](https://developer.authorize.net/api/reference/index.html).

If we are using `api2.authorize.net` instead of `api.authorize.net` and we are ok _not_ to update these certs, please let me know. If that is the case, then there is another issue. Due to the most current version of the library [using](https://github.com/AuthorizeNet/sdk-php/blob/master/lib/net/authorize/api/constants/ANetEnvironment.php#L7) `apitest.authorize.net`, it seems that the certs would need to be updated anyway for anyone using the official Sandbox API Endpoint.

Please let me know if you need anymore details or if you can shed some light on the situation. Thank you.

**Comment by gnongsie** [comment]
Hi @HeathNaylor ,

Thanks for coming to us with these doubts.

The "Legacy SDKs" referred in [the post](https://community.developer.authorize.net/t5/News-and-Announcements/SSL-Certificate-Updates-for-Legacy-SDKs/m-p/62935/highlight/true#M207) means SDKs with version 1.9.6 or older, which were using `api.authorize.net` as the endpoint. 

Basically, what this implies is that, if you are using an older version of the PHP SDK with your application, you will need to update to the latest `cert.pem` file from the repository.

If, however, you are using the newer versions of the SDK (version 1.9.7 or above), then the SDK already has the latest `cert.pem` file packaged with it.

**Comment by ashtru** [comment]
Closing this issue based on the answer from @gnongsie . Please reopen in case of any further queries.
