### ISSUE TITLE
Looking for /ssl folder that does not exist now that class is in /deprecated/shared folder

### ISSUE THREAD

**Issue by lorienorman** [AuthorizeNet/sdk-php#340]
When I updated from version 1.9.7 to version 1.9.8 my AuthorizeNet unit tests started failing.   After tracing the code I found the problem to be with the fact that some classes were now deprecated and in the `/deprecated/shared` folder.  The `AuthorizeNetRequest.php` class has the following line: 

`curl_setopt($curl_request, CURLOPT_CAINFO, dirname(dirname(__FILE__)) . '/ssl/cert.pem');`

but reference to the `/ssl` folder causes curl_execute to throw an exception because the `/ssl` folder does not exist in the new `/deprecated` folder. Moving the `/ssl` folder to the `/deprecated` folder solved the problem and allowed the tests to complete successfully. 

https://github.com/AuthorizeNet/sdk-php/blob/bdb5577074ab7a8fb69592f4866477d935d82b8d/lib/deprecated/shared/AuthorizeNetRequest.php#L105

**Comment by gnongsie** [comment]
Hi @lorienorman ,

We have a fix for this issue in place (#341), which is currently being reviewed and will be released soon in the next version.

**Comment by gnongsie** [comment]
Hi,

This has been released as part of v1.9.9. 

I'll be closing this issue. Kindly reopen if the issue still persists.
