### ISSUE TITLE
ReflectionObject::__construct() expects parameter 1 to be object, string given

### ISSUE THREAD

**Issue by TomDedels** [AuthorizeNet/sdk-php#346]
Two weeks ago I was ready to roll out this code (yes I know, not recommended for live). Everything was working perfectly on my live system (still using sandbox), then, when creating a customer and payment profile this error started:

ReflectionObject::__construct() expects parameter 1 to be object, string given in C:\Program Files (x86)\PHP\v5.6\includes\vendor\lib\net\authorize\util\Log.php on line 180 Fatal error: ReflectionClass::getProperties(): Internal error: Failed to retrieve the reflection object in C:\Program Files (x86)\PHP\v5.6\includes\vendor\lib\net\authorize\util\Log.php on line 125

It was returning the customerProfileId as a string while trying to create the payment profile.
I went back to my dev system, tried the same thing and got the same error. 

Any clues would be appreciated.

+nx
+0m

**Comment by ashtru** [comment]
@TomDedels 

Can you share the **details of the class** for which the reflection is failing, by adding an output in the Log.php for the [getPropertiesInclBase() method before line 125](https://github.com/AuthorizeNet/sdk-php/blob/master/lib/net/authorize/util/Log.php#L120)?

Or if you are not actively using logging, you can _disable logging_, by removing/commenting the[ line for setting the log file ](https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/create-customer-profile.php#L7).

**Comment by TomDedels** [comment]
I scaled back the logging and then I was able to find my coding error. It was passing an array where the object expected a customerProfileId. Duh.

 

Because of the “no dependencies” this is by far the best version of the Authorize PHP code.

 

Keep it going!

 

+nx

+0m
