### ISSUE TITLE
Missing "transHashSha2" in Charge a Customer Profile Response Body

### ISSUE THREAD

**Issue by mahima1990** [AuthorizeNet/sdk-php#365]
We are getting empty **transHashSha2** in response body while trying to make payment using **"Charge a Customer Profile"** method. The same is working properly while using "Charge a Credit Card" method. Any Idea?

**Comment by gnongsie** [comment]
Hi,
Can I ask which environment this is happening on? I will start my investigation on this in the meantime.

**Comment by mahima1990** [comment]
Following are my Request & Response Data:

**Request Data:**
`Array
(
    [createTransactionRequest] => Array
        (
            [merchantAuthentication] => Array
                (
                    [name] => 3CL476bmn
                    [transactionKey] => 7fc6V5cfV5ML2u7Z
                )

            [refId] => 1552990635
            [transactionRequest] => Array
                (
                    [transactionType] => authCaptureTransaction
                    [amount] => 1
                    [profile] => Array
                        (
                            [customerProfileId] => 1507044603
                            [paymentProfile] => Array
                                (
                                    [paymentProfileId] => 1506419104
                                )

                        )

                )

        )

)
`

**Resonse Data:**
`Array
(
    [transactionResponse] => Array
        (
            [responseCode] => 1
            [authCode] => FQJI85
            [avsResultCode] => Y
            [cvvResultCode] => P
            [cavvResultCode] => 2
            [transId] => 40026927430
            [refTransID] => 
            [transHash] => 
            [testRequest] => 0
            [accountNumber] => XXXX0002
            [accountType] => AmericanExpress
            [messages] => Array
                (
                    [0] => Array
                        (
                            [code] => 1
                            [description] => This transaction has been approved.
                        )

                )

            [transHashSha2] => 
            [profile] => Array
                (
                    [customerProfileId] => 1507044603
                    [customerPaymentProfileId] => 1506419104
                )

            [SupplementalDataQualificationIndicator] => 0
            [isAuthorized] => 0
            [transactionHash] => 
        )

    [refId] => 1552990786
    [messages] => Array
        (
            [resultCode] => Ok
            [message] => Array
                (
                    [0] => Array
                        (
                            [code] => I00001
                            [text] => Successful.
                        )

                )

        )

)
`

**Comment by gnongsie** [comment]
I've escalated this issue to the relevant team. Please be patient and I will update you with the progress.

**Comment by mahima1990** [comment]
@gnongsie  Any update on this?

**Comment by gnongsie** [comment]
Hi @mahima1990 ,

Apologies for this. I have not received any reply from the team on this. I will update you as and when the updates come in.

**Comment by gnongsie** [comment]
Hi @mahima1990 ,
As per the [official notification](https://support.authorize.net/s/article/MD5-Hash-End-of-Life-Signature-Key-Replacement), 

> For CIM createTransaction the SHA2 field and value will not be provided in the response (including Silent Post for this specific call).

I had a discussion on this with the relevant team and they said that this decision was taken beforehand.
