### ISSUE TITLE
"A valid amount is required" error when creating transactions

### ISSUE THREAD

**Issue by jaredtking** [AuthorizeNet/sdk-php#366]
When we are creating transactions (a sale transaction in our case) we are seeing that they intermittently fail with this error message: `A valid amount is required.`

We are using this code to set the amount (intentionally left out the unrelated code):
```php
$amount = 457.32;
$transactionRequestType = new TransactionRequestType();
$transactionRequestType->setAmount(number_format($amount, 2, '.', ''));
// rest of request here...
```

What we are seeing happening is that the amount is converted into a floating point number and not rounding correctly. In the above example the SDK is taking `457.32` and converting it into `457.31999999999999`, which is then rejected by the gateway with the `A valid amount is required.` error message.

I believe this is due to the SDK type-casting the amount as a float here: https://github.com/AuthorizeNet/sdk-php/blob/master/lib/net/authorize/api/yml/v1/TransactionRequestType.yml#L13

We've tried with and without `number_format` and are still getting the same error message. How do we fix this?

### SDK Version

`1.9.9`

### Request generated by the SDK

(details intentionally masked)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<createTransactionRequest xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
  <merchantAuthentication>
    <name><![CDATA[xxxx]]></name>
    <transactionKey><![CDATA[xxxxxxxxxxxxxxxx]]></transactionKey>
  </merchantAuthentication>
  <clientId><![CDATA[sdk-php-1.9.9]]></clientId>
  <refId><![CDATA[ref1554302668]]></refId>
  <transactionRequest>
    <transactionType><![CDATA[authCaptureTransaction]]></transactionType>
    <amount>457.31999999999999</amount>
    <currencyCode><![CDATA[usd]]></currencyCode>
    <profile>
      <customerProfileId><![CDATA[xxxxx]]></customerProfileId>
      <paymentProfile>
        <paymentProfileId><![CDATA[xxxxx]]></paymentProfileId>
      </paymentProfile>
    </profile>
    <solution>
      <id><![CDATA[xxxxx]]></id>
    </solution>
    <order>
      <invoiceNumber><![CDATA[xxxx]]></invoiceNumber>
      <description><![CDATA[xxxxx]]></description>
    </order>
    <customer>
      <id><![CDATA[xxxxx]]></id>
      <email><![CDATA[xxxx]]></email>
    </customer>
    <transactionSettings>
      <setting>
        <settingName><![CDATA[allowPartialAuth]]></settingName>
        <settingValue><![CDATA[0]]></settingValue>
      </setting>
    </transactionSettings>
  </transactionRequest>
</createTransactionRequest>
```

#### The error response from the gateway

```xml
<?xml version="1.0" encoding="UTF-8"?>
<createTransactionResponse xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
  <refId><![CDATA[ref1554302668]]></refId>
  <messages>
    <resultCode><![CDATA[Error]]></resultCode>
    <message>
      <code><![CDATA[E00027]]></code>
      <text><![CDATA[The transaction was unsuccessful.]]></text>
    </message>
  </messages>
  <transactionResponse>
    <responseCode><![CDATA[3]]></responseCode>
    <authCode><![CDATA[]]></authCode>
    <avsResultCode><![CDATA[P]]></avsResultCode>
    <cvvResultCode><![CDATA[]]></cvvResultCode>
    <cavvResultCode><![CDATA[]]></cavvResultCode>
    <transId><![CDATA[0]]></transId>
    <refTransID><![CDATA[]]></refTransID>
    <transHash><![CDATA[F68A9C87C1E1472521704EF38C21F647]]></transHash>
    <testRequest><![CDATA[0]]></testRequest>
    <accountNumber><![CDATA[]]></accountNumber>
    <accountType><![CDATA[]]></accountType>
    <errors>
      <error>
        <errorCode><![CDATA[5]]></errorCode>
        <errorText><![CDATA[A valid amount is required.]]></errorText>
      </error>
    </errors>
    <transHashSha2><![CDATA[]]></transHashSha2>
  </transactionResponse>
</createTransactionResponse>
```

**Comment by ppone** [comment]
I would add that is is resulting in the `E00027` error.  Any updates Authorize.net?

**Comment by Fieldla** [comment]
I would really like this addressed so my customers can start paying again.  The testing shows whole dollars process thru Authorized with no issue, any cents on the transaction gets rejected.

**Comment by gnongsie** [comment]
Hi,
I've tried out the scenario that you have provided. But I'm not able to reproduce this issue.
```
$amount = 457.32;
$transactionRequestType->setAmount(number_format($amount, 2, '.', ''));
```

Response:
```
 Successfully created transaction with Transaction ID: 6011XXXXXXX
 Transaction Response Code: 1
 Message Code: 1
 Auth Code: IGOXXX
 Description: This transaction has been approved.
```

Can you provide the PHP version as well?

**Comment by jaredtking** [comment]
The problem is that this happens intermittently. Sometimes the requests do work, however, since the SDK seems to be casting the amount to a floating point without applying any rounding it can also generate amounts in the XML like `457.31999999999999`.

We use PHP 7.2.16 and were able to produce this issue with 7.2.14 as well.

Can the SDK round the decimal points on the amount to a certain precision in order to prevent this error from happening?

**Comment by jaredtking** [comment]
I figured out what's happened. Our serialize_precision PHP INI setting was set to `17`. When you call `var_export(1.1)`, as an example, then you get `1.1000000000000001` as the value. Since PHP 7.1 the recommended setting is `-1`. This [PHP RFC](https://wiki.php.net/rfc/precise_float_value) explains what happens when serialize_precision is not set to `-1` and var_export is used.

The reason this is an issue is because jms/serializer v2.2 changed how float values are serialized into XML. Previously it was just casting the float to a string. The new version started using var_export() which was affected by our serialize_precision setting. Here's the [commit changing the float serialization logic](https://github.com/schmittjoh/serializer/pull/1042/files).

If this problem happens to anyone else with PHP 7.1+ the solution is to set serialize_precision to `-1` in your php.ini file. You can close this issue now.

**Comment by gnongsie** [comment]
Hi,
Thank you for your diligence and for sharing your investigation.

**Comment by yehudahkay** [comment]
Occurred to us after after running composer update and using shared hosting

**Comment by bridgesense** [comment]
What I've found too is that there are several libraries out there that run ini_set on serialize_precision.  The workaround that helped in my case was to convert the float into a string before dropping it into setAmount().  There could be a bit more flexibility in the SDK for this.

`
$transactionRequestType->setAmount($your_float_amount . "");
`

PHP 7.2.24-1+0~20191026.31+debian9~1.gbpbbacde

**Comment by shrimpwagon** [comment]
This is still an issue and none of the fix suggestions has solved the problem. Please reopen!

**Comment by bilal1102** [comment]
transactionRequestType.setAmount(amount.toFixed(2));

This fixed my problem
nest.js 8.1.1, node.js v14.17.3

**Comment by nilocrasta** [comment]
Ended up creating a .user.ini with "serialize_precision = -1" in it, in the directory where I was having this trouble and it solved my problem.  Thanks for sharing! was definitely a huge learning experience for me, spent a few hours trying to go around making changes to the main ini file.
