### ISSUE TITLE
CURL ERROR: Peer certificate cannot be authenticated with known CA certificates

### ISSUE THREAD

**Issue by multicore-association** [AuthorizeNet/sdk-php#384]
All of a sudden I am getting this error. Any ideas what is wrong?

 Mon, 09 Mar 2020 15:10:46 -0700 ERROR : [_sendRequest] (/home2/elks901/public_html/includes/authorize.net/lib/net/authorize/util/HttpClient.php : 106) - CURL ERROR: Peer certificate cannot be authenticated with known CA certificates

I am running an olded version of the api, not sure what the version is, here is what is in the readme file:
  "php": ">=5.2.0",
  "ext-curl": "*",
  "authorizenet/authorizenet": "1.8.8",
  "jms/serializer": "xsd2php-dev as 0.18.0"

I tried to turn CURLOPT_SSL_VERIFYHOST off but it still failed.

Thank you for your help.

**Comment by NaderCHASER** [comment]
I'm having the same issue which seems to coincide with Phase 4b at https://support.authorize.net/s/article/Authorize-Net-Network-Change-FAQ.

I've tried updating lib/ssl/cert.pem but that didn't fix things either.

**Comment by NaderCHASER** [comment]
@multicore-association you need to update authorizenet/authorizenet to 1.9.9 for lib/ssl/cert.pem to be updated to a working version.

Use `composer update`.

**Comment by multicore-association** [comment]
I updated to the latest and everything is back to normal.

Thank you.
