### ISSUE TITLE
Multiple payment profile IDS 

### ISSUE THREAD

**Issue by shahariaazam** [AuthorizeNet/sdk-php#40]
```php
$an = new AuthorizeNetCIM();
$result = $an->getCustomerProfile(xxxxxx);    //xxxxxx is customer profile ID
var_dump($result->getCustomerPaymentProfileIds());
```

And I discovered there is no `numericStrings` when I am calling getCustomerProfile(xxxxxx) in the response. So either the response is different or the extraction of ids are wrong! (just for deep digging purpose)

`getCustomerPaymentProfileIds` is returning **null** all the time when this customer has multiple payment profile

**Comment by brianmc** [comment]
Hi @shahariaazam, try this sample https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/get-customer-profile-ids.php
