### ISSUE TITLE
response types incorrect in 2.0.2

### ISSUE THREAD

**Issue by Craig-CyberNY** [AuthorizeNet/sdk-php#416]
The change in 2.0.2 to lib/net/authorize/api/controller/CreateCustomerProfileFromTransactionController.php changed the response type from:

'net\authorize\api\contract\v1\CreateCustomerProfileResponse'; 

to 

'net\authorize\api\contract\v1\CreateCustomerProfileFromTransactionResponse'; 

but 'net\authorize\api\contract\v1\CreateCustomerProfileFromTransactionResponse'; doesn't exist. 

You will see the same problem in lib/net/authorize/api/controller/GetTransactionListForCustomerController.php 

$responseType = 'net\authorize\api\contract\v1\GetTransactionListResponse';

changed to:

$responseType = 'net\authorize\api\contract\v1\GetTransactionListForCustomerResponse';

but GetTransactionListForCustomerResponse doesn't exist.

**Comment by krabsheva** [comment]
Seeing this as well. Seems like a simple oversight when some of the classes were renamed and a lack of testing of at least the PHP CreateCustomerProfileFromTransactionController class. Don't see how it is usable at all. 

Surprised this has not been addressed in months. Had to skip the 2.0.2 version of the code.

**Comment by gnongsie** [comment]
This has been corrected in the latest version.
Closing this issue based on that.
