### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by jymboche** [AuthorizeNet/sdk-php#42]
Do the certificates need to be updated? I've been unable to connect with ssl the last 2 days (for sandbox).  I went to test.authorize.net and downloaded the certs and it appears to be working with the downloaded ones.

**Comment by sunerandgarcia** [comment]
do you think i can get those certificates?

**Comment by jymboche** [comment]
Just put this in lib/ssl/cert.pem

-----BEGIN CERTIFICATE-----
MIIDVDCCAjygAwIBAgIDAjRWMA0GCSqGSIb3DQEBBQUAMEIxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9i
YWwgQ0EwHhcNMDIwNTIxMDQwMDAwWhcNMjIwNTIxMDQwMDAwWjBCMQswCQYDVQQG
EwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEbMBkGA1UEAxMSR2VvVHJ1c3Qg
R2xvYmFsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2swYYzD9
9BcjGlZ+W988bDjkcbd4kdS8odhM+KhDtgPpTSEHCIjaWC9mOSm9BXiLnTjoBbdq
fnGk5sRgprDvgOSJKA+eJdbtg/OtppHHmMlCGDUUna2YRpIuT8rxh0PBFpVXLVDv
iS2Aelet8u5fa9IAjbkU+BQVNdnARqN7csiRv8lVK83Qlz6cJmTM386DGXHKTubU
1XupGc1V3sjs0l44U+VcT4wt/lAjNvxm5suOpDkZALeVAjmRCw7+OC7RHQWa9k0+
bw8HHa8sHo9gOeL6NlMTOdReJivbPagUvTLrGAMoUgRx5aszPeE4uwc2hGKceeoW
MPRfwCvocWvk+QIDAQABo1MwUTAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTA
ephojYn7qwVkDBF9qn1luMrMTjAfBgNVHSMEGDAWgBTAephojYn7qwVkDBF9qn1l
uMrMTjANBgkqhkiG9w0BAQUFAAOCAQEANeMpauUvXVSOKVCUn5kaFOSPeCpilKIn
Z57QzxpeR+nBsqTP3UEaBU6bS+5Kb1VSsyShNwrrZHYqLizz/Tt1kL/6cdjHPTfS
tQWVYrmm3ok9Nns4d0iXrKYgjy6myQzCsplFAMfOEVEiIuCl6rYVSAlk6l5PdPcF
PseKUgzbFbS9bZvlxrFUaKnjaZC2mqUPuLk/IH2uSrW4nOQdtqvmlKXBx4Ot2/Un
hw4EbNX/3aBd7YdStysVAq45pmp06drE57xNNB6pXE0zX5IJL4hmXXeXxx12E6nV
5fEWCRE11azbJHFwLJhWC9kXtNHjUStedejV0NxPNO3CBWaAocvmMw==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEIjCCAwqgAwIBAgIDAjp5MA0GCSqGSIb3DQEBCwUAMEIxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9i
YWwgQ0EwHhcNMTQwOTA4MjA0MTEwWhcNMjIwNTIwMjA0MTEwWjBEMQswCQYDVQQG
EwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEdMBsGA1UEAxMUR2VvVHJ1c3Qg
U1NMIENBIC0gRzQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCafZho
EUDBX3LsVbOxY/MyInKRxhYFuwiCMbT27tQYOREvLtpH/lExblvyqQrrL7v1YVll
VwLNgP/HcDJUif3brply1E8MJrkuYzB93hRbatdSeCH5v7xQ1VQSWdi1NtkhR7g/
algdjHLhl5XT4UWo8Vrlvv7jU3yl8FLgzzmUDBlx8sAlB0h9HObxOSUvmHlD6Bhy
9GWGmFoABEfaS1gefIaxSzWmIAAczRs7Il3RkygzEiOUCKrDOvXRxox+mdMYoK2d
GM9JrRAD95kzJoZGmi+gumxuyIgCt276ep6YSu6aMX0ZFGAM7I8gIzzalya26oBs
ileeIO5vFyVKMq01AgMBAAGjggEdMIIBGTAfBgNVHSMEGDAWgBTAephojYn7qwVk
DBF9qn1luMrMTjAdBgNVHQ4EFgQUrDLtWsng3jCckFhVJmP2cqZUX+MwEgYDVR0T
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwNQYDVR0fBC4wLDAqoCigJoYk
aHR0cDovL2cuc3ltY2IuY29tL2NybHMvZ3RnbG9iYWwuY3JsMC4GCCsGAQUFBwEB
BCIwIDAeBggrBgEFBQcwAYYSaHR0cDovL2cuc3ltY2QuY29tMEwGA1UdIARFMEMw
QQYKYIZIAYb4RQEHNjAzMDEGCCsGAQUFBwIBFiVodHRwOi8vd3d3Lmdlb3RydXN0
LmNvbS9yZXNvdXJjZXMvY3BzMA0GCSqGSIb3DQEBCwUAA4IBAQBhQK0hDwO7ldyJ
/KPLBXHpHFmXNcL6awWkFsZWRjd0GxvxPizoNxm3lNIPDsW/FAcrNM1btI3HVp0Z
/AK0npAx+qRExnXd3R8lVKMwTKzb/sSI9zEmGEeuTCAZGseuPpgKFj3SwqZdDS4p
fbKdx0EyF8qdrjm/kZje50TilZyUXGxCG1nJe2gTqJYJdO5AFKTV18l7M6MPWmmc
GvpvEkcc3x5McE5t3f4ch7Wd4VQHCYrNvqqoRnhuFvLnkQ7Dr9p2ANHYokYkA6Ua
hYFWg2MnupCO+WIRuqd8kKkaZrTFvI8pQavrjZmmzJFkutzGpkyztCMmUXJW+fN0
VZ8ldU8r
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFQDCCBCigAwIBAgICBiswDQYJKoZIhvcNAQELBQAwRDELMAkGA1UEBhMCVVMx
FjAUBgNVBAoTDUdlb1RydXN0IEluYy4xHTAbBgNVBAMTFEdlb1RydXN0IFNTTCBD
QSAtIEc0MB4XDTE1MDMxODIyMjgwNVoXDTE2MDMyMTE3NTAyMFowgYIxCzAJBgNV
BAYTAlVTMQ0wCwYDVQQIEwRVdGFoMRYwFAYDVQQHEw1BbWVyaWNhbiBGb3JrMRow
GAYDVQQKExFBdXRob3JpemUuTmV0IExMQzETMBEGA1UECxMKT3BlcmF0aW9uczEb
MBkGA1UEAxMSdGVzdC5hdXRob3JpemUubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEA2223S+ljw16xfEBnIPsYt2OjLfw4+pVgezJzyE2foWYdlYhI
RBSY3HKxG+Ht0gIEVeHISjdSxFN3BCsDVGTyi96rt0L8wkOOhA8ewjVcyA9JexrU
RWaHYpOXO4k6exwMxKBLBzNTx1/Ignfza/lgIbgk6N4tnu4POUBsGI9zMbUvufSj
aowJIiuLG46ArLmD3vKSldnPvHZ4jCi2YPPni/ZOBvsyRvO1uCR+K+DXxlJPsWUf
zlIFhBxd8I1Lbvycy2tX4NM/P0/H8ANQl+0sFVh1PG/xNpEwFIb/EwF7HbuLxG1O
QBzSLZKeOqovc+VaDzY3LKncv84z3k+/YE79BQIDAQABo4IB+zCCAfcwHwYDVR0j
BBgwFoAUrDLtWsng3jCckFhVJmP2cqZUX+MwVwYIKwYBBQUHAQEESzBJMB8GCCsG
AQUFBzABhhNodHRwOi8vZ3cuc3ltY2QuY29tMCYGCCsGAQUFBzAChhpodHRwOi8v
Z3cuc3ltY2IuY29tL2d3LmNydDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMIG0BgNVHREEgawwgamCFXNjb3Rlc3QuYXV0aG9y
aXplLm5ldIIZdGVzdGNvbnRlbnQuYXV0aG9yaXplLm5ldIIYdGVzdHZlcmlmeS5h
dXRob3JpemUubmV0ghl0ZXN0Y2FwdGNoYS5hdXRob3JpemUubmV0ghVzYW5kYm94
LmF1dGhvcml6ZS5uZXSCFWFwaXRlc3QuYXV0aG9yaXplLm5ldIISdGVzdC5hdXRo
b3JpemUubmV0MCsGA1UdHwQkMCIwIKAeoByGGmh0dHA6Ly9ndy5zeW1jYi5jb20v
Z3cuY3JsMAwGA1UdEwEB/wQCMAAwWgYDVR0gBFMwUTBPBgpghkgBhvhFAQc2MEEw
PwYIKwYBBQUHAgEWM2h0dHBzOi8vd3d3Lmdlb3RydXN0LmNvbS9yZXNvdXJjZXMv
cmVwb3NpdG9yeS9sZWdhbDANBgkqhkiG9w0BAQsFAAOCAQEAZvsq0fokgN6j+FMr
F/xBqogF2LeXxBqKOnDY/s387FDHDpvnf09XSPEegUXJ15OFpiT6z0jZ88DpaJHX
RgrD5oTaT3W4H+/+KbOPryjEU30KveoY8wR5Yp8bksB8aKSC74Acr74E1brDvcu8
uPm/YMAxOPj69ppeNPt6FiPiaTub1kwV6rwHI767LFfrYHUKpZybrdGax6i+N3zN
yr+QGWyPYszLZM4oWrzQ65ZvsppbBYZBWpZKPMKkAjEqVorkOMqCyJ5NO+oLEEeq
gxJaQ/HwgtMZnoPpA1J4RE42mi7utc2pUV9sYnBVyYg7EDnPYazj+cavjoWD+5r8
99tutg==
-----END CERTIFICATE-----

**Comment by brianmc** [comment]
Cert file just updated in Master https://github.com/AuthorizeNet/sdk-php/commit/47bcacfb5190b91196bcbd842cc03cebcf4e7f1b
