### ISSUE TITLE
net\authorize\api\contract\v1\CreateCustomerProfileFromTransactionResponse does not exist

### ISSUE THREAD

**Issue by efitz16** [AuthorizeNet/sdk-php#423]
The file `lib/net/authorize/api/controller/CreateCustomerProfileFromTransactionController.php` uses the response type `net\authorize\api\contract\v1\CreateCustomerProfileFromTransactionResponse`, but a corresponding file does not exist in lib/net/authorize/api/contract/v1. 

Changing the line `$responseType = 'net\authorize\api\contract\v1\CreateCustomerProfileFromTransactionResponse';` to `$responseType = 'net\authorize\api\contract\v1\CreateCustomerProfileResponse';` fixes the issue. I cannot submit a pull request for this file according to your [contributors's guide](https://github.com/AuthorizeNet/sdk-php/blob/master/CONTRIBUTING.md).

I found this error by trying to implement the code found in [your sample code](https://github.com/AuthorizeNet/sample-code-php/blob/2fd4492e49ccd635c7bdf6a530e5dd33c6ac1750/CustomerProfiles/create-customer-profile-from-transaction.php). `$controller = new AnetController\CreateCustomerProfileFromTransactionController($request);` throws an error: `Fatal error: Class 'net\authorize\api\contract\v1\CreateCustomerProfileFromTransactionResponse' not found`. This was previously discussed in a [closed issue](https://github.com/AuthorizeNet/sdk-php/issues/105).

Thank you.

**Comment by bearinaustin** [comment]
Bumping we are experiencing this same issue. We are freezing our updates for this package in composer and using the manual fix mentioned [https://github.com/AuthorizeNet/sdk-php/issues/105](here) as a temporary workaround.. 

Wondering when this will be made available in an approved branch??

**Comment by BFunk86** [comment]
So it is now November 2022 and this is still not fixed. Do they plan on ever fixing this? It has been an [issue](https://github.com/AuthorizeNet/sdk-php/issues/105) since February 2016. All they need to do is merge pull request #424

**Comment by gnongsie** [comment]
This has been corrected in the latest version.
Closing this issue based on that.
