### ISSUE TITLE
authorize SDK and PHP74 compatibility warnings and errors from PHP_CodeSniffer-3.6.1 and PHPCompatibility-9.3.5 

### ISSUE THREAD

**Issue by webservant316** [AuthorizeNet/sdk-php#425]
I am upgrading PHP71 to PHP74 or PHP80. So I am running PHP_CodeSniffer-3.6.1 and PHPCompatibility-9.3.5 to test for issues.

Following are the errors and warnings reported.

/authorizenet/lib/net/authorize/api/contract/v1/TransactionRequestType/UserFieldsAType.php	104	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/KeyManagementSchemeType/DUKPTAType.php	166	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/KeyManagementSchemeType/DUKPTAType/DeviceInfoAType.php	70	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/KeyManagementSchemeType/DUKPTAType/EncryptedDataAType.php	70	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/KeyManagementSchemeType/DUKPTAType/ModeAType.php	97	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/HeldTransactionRequestType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/EmvTagType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ARBGetSubscriptionListSortingType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CcAuthenticationType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ProcessingOptionsType.php	154	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TokenMaskedType.php	154	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CardArtType.php	181	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ProcessorType.php	161	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/FraudInformationType.php	134	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/MessagesAType.php	111	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/SplitTenderPaymentsAType.php	111	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/ErrorsAType/ErrorAType.php	97	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/MessagesAType/MessageAType.php	97	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/SecureAcceptanceAType.php	124	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/ErrorsAType.php	111	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/PrePaidCardAType.php	124	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/EmvResponseAType.php	131	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/EmvResponseAType/TagsAType.php	104	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/UserFieldsAType.php	104	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType/SplitTenderPaymentsAType/SplitTenderPaymentAType.php	286	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ProfileTransVoidType.php	154	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/BatchStatisticType.php	613	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PermissionType.php	73	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PaymentType.php	263	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ProfileTransAmountType.php	215	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionDetailsType/EmvDetailsAType/TagAType.php	97	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionDetailsType/EmvDetailsAType.php	111	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/KeyBlockType.php	73	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/DriversLicenseMaskedType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/OtherTaxType.php	208	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/SolutionType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/AuResponseType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/FingerPrintType.php	181	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ANetApiResponseType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/DriversLicenseType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CreateProfileResponseType.php	222	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/WebCheckOutDataType.php	154	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ListOfAUDetailsType.php	168	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PaymentEmvType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ImpersonationAuthenticationType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ExtendedAmountType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CreditCardMaskedType.php	208	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CustomerType.php	235	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ArrayOfSettingType.php	107	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionSummaryType.php	505	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PaymentMaskedType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PaymentProfileType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CustomerProfilePaymentType.php	154	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PaymentDetailsType.php	316	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionDetailsType.php	1485	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/SubscriptionDetailType.php	478	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CustomerPaymentProfileListItemType.php	181	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/UserFieldType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PaymentScheduleType/IntervalAType.php	97	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PaymentScheduleType.php	157	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/MobileDeviceType.php	181	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/WebCheckOutDataTypeTokenType.php	181	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CustomerProfileIdType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/EncryptedTrackDataType.php	73	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransRetailInfoType.php	154	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/SubsequentAuthInformationType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CustomerDataType.php	181	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ARBSubscriptionMaskedType.php	297	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/FDSFilterType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CreditCardTrackType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ANetApiRequestType.php	129	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/MerchantAuthenticationType.php	291	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/KeyValueType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/SubMerchantType.php	343	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/SecurePaymentContainerErrorType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/OpaqueDataType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/MessagesType.php	134	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/OrderType.php	532	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ARBSubscriptionType.php	316	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionListSortingType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/MerchantContactType.php	208	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PagingType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/BankAccountMaskedType.php	208	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionRequestType.php	1122	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/MessagesType/MessageAType.php	97	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CustomerProfileBaseType.php	127	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/SubscriptionPaymentType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/BankAccountType.php	235	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/BatchDetailsType.php	296	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/AuDetailsType.php	235	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CustomerPaymentProfileBaseType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ArbTransactionType.php	181	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PayPalType.php	208	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/KeyManagementSchemeType.php	74	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/TransactionResponseType.php	889	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ProfileTransactionType.php	217	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/SettingType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CustomerPaymentProfileSortingType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/NameAndAddressType.php	262	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/PaymentSimpleType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/LineItemType.php	748	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CustomerProfileSummaryType.php	181	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/CreditCardSimpleType.php	100	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/ReturnedItemType.php	181	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/api/contract/v1/IsAliveRequest.php	70	32	error	Using \parent\" inside a class without parent is deprecated since PHP 7.4"
/authorizenet/lib/net/authorize/util/Log.php	259	23	error	Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter \$logMessage\" was changed on line 253."

**Comment by webservant316** [comment]
The errors above are from version 2.0.  Do the later version of 2.0.1 or 2.0.2 fix this?

**Comment by gnongsie** [comment]
This issue does not appear in the latest version, as evidenced by recent commits and CI runs.
Closing this issue based on this.
