### ISSUE TITLE
Big Issue

### ISSUE THREAD

**Issue by sunerandgarcia** [AuthorizeNet/sdk-php#43]
My whole system is not charging, Do you know if there is a know issue with this class?

**Comment by brianmc** [comment]
You should be able to resolve this issue with the latest cacerts bundle for curllib.  We have also updated the cert file in this SDK https://github.com/AuthorizeNet/sdk-php/commit/47bcacfb5190b91196bcbd842cc03cebcf4e7f1b

Replacing that file will also fix the issue.
