### ISSUE TITLE
Incorrect responseType in CreateCustomerProfileFromTransactionController

### ISSUE THREAD

**Issue by it-all** [AuthorizeNet/sdk-php#435]
CreateCustomerProfileFromTransactionResponse does not exist. {An older SDK version used CreateCustomerProfileResponse.}

This problem causes CreateCustomerProfileFromTransactionRequest to fail upon execution.

**Comment by Rbtsv2** [comment]
CreateCustomerProfileFromTransactionResponse does not exist same problem = >"vendor/authorizenet/authorizenet/lib/net/authorize/api/controller/CreateCustomerProfileFromTransactionController.php" needs to be replaced by "net/authorize/api/contract/v1/CreateCustomerPaymentProfileResponse.php" ?

**Comment by it-all** [comment]
$responseType = 'net\authorize\api\contract\v1\CreateCustomerProfileResponse'; seems to work also.

**Comment by Rbtsv2** [comment]
yes but .. in the response : 
object(net\authorize\api\contract\v1\CreateCustomerPaymentProfileResponse)#2044 (6) { ["customerProfileId":"net\authorize\api\contract\v1\CreateCustomerPaymentProfileResponse":private]=> string(9) "906645000" 
["customerPaymentProfileId":"net\authorize\api\contract\v1\CreateCustomerPaymentProfileResponse":private]=> NULL 
["validationDirectResponse":"net\authorize\api\contract\v1\CreateCustomerPaymentProfileResponse":private]=> NULL ["refId":"net\authorize\api\contract\v1\ANetApiResponseType":private]=> NULL
["messages":"net\authorize\api\contract\v1\ANetApiResponseType":private]=> object(net\authorize\api\contract\v1\MessagesType)#2042 (2) { ["resultCode":"net\authorize\api\contract\v1\MessagesType":private]=> string(2) "Ok" ["message":"net\authorize\api\contract\v1\MessagesType":private]=> array(1) { [0]=> object(net\authorize\api\contract\v1\MessagesType\MessageAType)#2034 (2) { ["code":"net\authorize\api\contract\v1\MessagesType\MessageAType":private]=> string(6) "I00001" ["text":"net\authorize\api\contract\v1\MessagesType\MessageAType":private]=> string(11) "Successful." } } } ["sessionToken":"net\authorize\api\contract\v1\ANetApiResponseType":private]=> NULL }


no customerPaymentProfileId.. response NULL for futur transaction its necessary

**Comment by Rbtsv2** [comment]
CreateCustomerProfileResponse !!! yes thanks 

response : 
["customerPaymentProfileIdList":"net\authorize\api\contract\v1\CreateCustomerProfileResponse":private]=> array(1) { [0]=> string(9) "906414742" }

**Comment by gnongsie** [comment]
This has been corrected in the latest version.
Closing this issue based on that.
