### ISSUE TITLE
PHP notice for empty CMI customers

### ISSUE THREAD

**Issue by sp00n** [AuthorizeNet/sdk-php#45]
When querying CMI in sandbox mode (and probably also if no customers exist yet), I receive a PHP notice.

```PHP
$request = new AuthorizeNetCIM;
$response = $request->getCustomerProfileIds();
$customers = $response->getCustomerProfileIds();
```

    A PHP Error was encountered
    Severity: Notice
    Message: Undefined index: numericString
    Filename: lib/AuthorizeNetCIM.php
    Line Number: 491

The `$this->xml->ids` property is empty if there are no customers, and hence it can't access the "numericString" values.

**Comment by sneakyimp** [comment]
I'm also having this problem with AuthorizeNetCIM_Response::getCustomerPaymentProfileIds():
```
Notice: Undefined index: numericString in /var/www/erep-v3/html/erp_php/authorizenet/lib/AuthorizeNetCIM.php on line 475
```

**Comment by brianmc** [comment]
The fix is pending and will be merged in our future release branch shortly.  Thanks

**Comment by sneakyimp** [comment]
Um, unless I'm mistaken, you have replaced the old code entirely. That's hardly "fixing" this problem. That's introducing a bigger problem. I have to replace all my code to use your entirely different, newer objects with namespaces and different object names, etc.

**Comment by brianmc** [comment]
In this case the fix was made to the reported issue so no need to replace any code.
