### ISSUE TITLE
Possible deprecated error when logging is enabled, sending a card object 

### ISSUE THREAD

**Issue by RickKukiela** [AuthorizeNet/sdk-php#458]
Regarding this line: https://github.com/AuthorizeNet/sdk-php/blob/e1acf55c9cb22bef1852b1e494502973ade11cce/lib/net/authorize/util/Log.php#L163

Previously, attempting to omit the `cardCode` value on "Stored Card" transaction (because the card code was not known / not obtained from the user), while SDK logging is enabled, would cause the referenced line to attempt to perform `preg_replace()` on a `NULL` value when parsing the card code value. (I guess in the above scenario, when `$prop->getValue()` returns `NULL` when the `cardCode` value was not set.)

Since passing `NULL` to the 3rd argument of `preg_replace()` is deprecated, it throws the error.

My fix was to simply cast the return value of `$prop->getValue()` as a string to ensure an empty string is passed instead of `NULL`.

Is this something that has been resolved elsewhere in the codebase and no longer needs to force the string? IE, is something changed were attempting to process a property that was not set, would now return an empty string rather than `NULL`?

Since this comes directly from a built-in reflection class, it seems, I don't think this is resolved in the current version.

To that end, I just published a PR that fixes this issue.
PR: https://github.com/AuthorizeNet/sdk-php/pull/459

I'm OK using my fork, but it would be better for everyone if this gets merged to the main codebase.

**Comment by gnongsie** [comment]
Closing this PR as the fix has been added as part of a different commit.
Also, I am not using type casting, in the event that it causes issues later on.
Instead, I will check for null and provide an empty string if the object is null.
