### ISSUE TITLE
Using Logging Mechanism inadvertently Storing CC info

### ISSUE THREAD

**Issue by fogeytron** [AuthorizeNet/sdk-php#48]
Hi,

We are using CIM and are using Auth.net to handle storing all of our CC info.

We are also using the built in logging mechanisms in the SDK to troubleshoot any issues we have.

The problem is that when you make a createCustomerPaymentProfileRequest, one of the fields is the CC number so that is stored in plain text in the log file.

Is there anyway you could update the logging to mask the actual CC number and cvv code so we can continue to use the logging, but also not have access to the sensitive data?

**Comment by brianmc** [comment]
We're on it, thanks @fogeytron

**Comment by gRegorLove** [comment]
Any progress on this? This is a pretty crucial bug. I'm holding off switching from AIM to Authorize.net API at the moment due to this.

**Comment by brianmc** [comment]
This was fixed in the last release: 1.8.6.2, apologies for not updating the issue.
