### ISSUE TITLE
No examples for createCustomerPaymentProfile that provide more than basic parameters

### ISSUE THREAD

**Issue by sneakyimp** [AuthorizeNet/sdk-php#51]
I've scoured the internet looking for PHP code examples that use this sdk to create a payment profile (createCustomerPaymentProfile) and have yet to find one that provides more than just customerType, cardNumber, and expirationDate. That's barely a fraction of the perhaps two dozen inputs described on page 24 of the CIM XML guide:
http://www.authorize.net/support/CIM_XML_guide.pdf

Given that this SDK uses irregular nested object structures and doesn't have any javadoc comments to elucidate what they are for (or to even standardize what methods and properties an instance of AuthorizeNetPaymentProfile->payment->creditCard might have), it would be most helpful if your project were to provide an example of how to create a payment profile while supplying this additional information.

**Comment by IslandUsurper** [comment]
I found https://github.com/AuthorizeNet/sdk-php/blob/master/lib/shared/AuthorizeNetTypes.php to be very helpful. Basically, just set the properties of the various objects and pass it to createCustomerPaymentProfile(). That's where the classes are defined, so you know what it expects. It's still hard to know what's optional, though.

**Comment by brianmc** [comment]
We've just done a major overhaul of our sample code and included it right there in our API Reference :  http://developer.authorize.net/api/reference/index.html#customer-profiles

Here's the Customer Profiles samples for PHP https://github.com/AuthorizeNet/sample-code-php/tree/master/CustomerProfiles 

Hope this helps,

Brian
