### ISSUE TITLE
Create Customer Profile From Transaction Request

### ISSUE THREAD

**Issue by mattgartz** [AuthorizeNet/sdk-php#52]
It appears that there is no functionality for createCustomerProfileFromTransactionRequest, available in the API but not here.

**Comment by rbmedia** [comment]
Sadly, I could not find anything either in the PHP SDK

**Comment by rbmedia** [comment]
this is working for me
Add it to /lib/AuthorizeNetCIM.php

/**
  * Create a customer profile from transaction.
  *
  * @param string               $transId
  *
  * @return AuthorizeNetCIM_Response
  */
    public function createCustomerProfileFromTransaction($transId)
    {
        $this->_constructXml("createCustomerProfileFromTransactionRequest");
	$this->_xml->addChild("transId", $transId);
        return $this->_sendRequest();
    }

**Comment by brianmc** [comment]
Check out this sample, using the new controller model:  https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/create-profile-from-transaction.php

NOTE You need the latest version of the SDK - 1.8.4.1

**Comment by rbmedia** [comment]
Thanks
