### ISSUE TITLE
New Model suggestions

### ISSUE THREAD

**Issue by w0rd-driven** [AuthorizeNet/sdk-php#56]
We've recently run into the requirement of using CIM profiles through transactions. I believe the "old" AIM approach doesn't cover this so that's the primary motivation for my switch to the new model.

I have a few suggestions:
- Utilize constructors with null/default values
  - This lets me know what parameters are required
  - It turns multiple line set calls into a single line constructor
  - The "old model" utilized this on almost all types and it makes the transition much easier as statements become almost 1:1
- Expose internal properties as public, leaving getters and setters for sensitive information
  - payment->creditCard->cardNumber is easier to read than getPayment()->getCreditCard()->getCardNumber()
  - Exposing the internal types allows things like json_encode() to just work. I encode the entire response->xml object, trimming sensitive information for logging purposes (and to replay the conditions of the call).
- HttpClient gives a warning on file_put_contents if you don't have a log file set
  - I'm either required to set it or turn off error reporting and I'd rather do neither of those. I'd rather it just not matter if it couldn't log information I don't care to log.

Overall, I really do prefer this approach once I got through some of the transition. I feel it follows http://developer.authorize.net/api/reference/index.html much more closely. The few tweaks above should make the transition from the old model to the new much easier.

**Comment by w0rd-driven** [comment]
For logging response objects, I just realized I could use the controller's public serializer object like this:
$controller->serializer->serialize($response, 'json');

That handles the response types perfectly. It won't handle the other types used as parameters for each request method. I like logging both to make sure both sides, the request and response, can be replayed later. This is a good workaround for one pain point but I still find dealing with the internal types much easier than getters and setters.

**Comment by brianmc** [comment]
Thanks for the feedback @w0rd-driven , we really appreciate you taking the time to suggest these changes.  These will absolutely help with usability and we're going to be looking incorporating some of these changes in the next release.

Thanks again,

Brian

**Comment by ashtru** [comment]
We assessed the different suggestions. We have incorporate some of them as changes.
Thanks for the feedback @w0rd-driven . This was helpful.
