### ISSUE TITLE
Akamai URLs

### ISSUE THREAD

**Issue by milesj** [AuthorizeNet/sdk-php#60]
Just received an email about the new Akamai URLs.

* https://api2.authorize.net/xml/v1/request.api
* https://api2.authorize.net/soap/v1/Service.asmx
* https://secure2.authorize.net/gateway/transact.dll

Should we expect this change in the SDK anytime soon?

**Comment by justbeez** [comment]
:+1:

We're using Composer, so it would be much better for us to be able to roll out this change by updating our target version than rolling one-off updates on every server.

**Comment by brianmc** [comment]
This update is coming soon, I do want to assure you that the current URLs are working and will continue to work.

Thanks,

Brian

**Comment by brianmc** [comment]
New release 1.8.5 contains the new Akamai endpoints

**Comment by milesj** [comment]
Awesome, thanks!
