### ISSUE TITLE
Autoload.php echo

### ISSUE THREAD

**Issue by inet2800** [AuthorizeNet/sdk-php#62]
The autoload.php echo's a class not found message when it does not find a class

"
 } else {
        echo 'Class not loaded: ' . $className;
"

That's OK. However when used with a AJAX within a framework such as Wordpress or Joomla it corrupts  the output with class not found messages.  This output conflicts with the intended output of the class that instantiates the A.NET class. So, if the php program being called by a jQuery script via $.post and the php returns die(json_encode($output)); the return contains all the echo from the autoload, which are not relevant.

**Comment by bradberger** [comment]
Agreed, having similar problems here. [Added a PR](https://github.com/AuthorizeNet/sdk-php/pull/69) to fix that before noticing there [was already a PR](https://github.com/AuthorizeNet/sdk-php/pull/53). This really needs to get fixed. It's no doubt a relic of some development debugging. Please fix it ASAP.

**Comment by brianmc** [comment]
Hey @bradberger I'm hoping to merge thus PR in the next hour or so.

Brian

**Comment by brianmc** [comment]
Done

**Comment by bradberger** [comment]
Awesome, thanks so much!
