### ISSUE TITLE
CIM.markdown lacks examples to supply billing address or CCV number

### ISSUE THREAD

**Issue by sneakyimp** [AuthorizeNet/sdk-php#63]
This documentation is hardly detailed:
https://github.com/AuthorizeNet/sdk-php/blob/master/doc/CIM.markdown

How does one supply the CCV card number when creating a payment profile? How about a billing address?

Also, who does this?
```php
$this->tax = (object)array();
```
Have you never heard of stdClass?
QV: http://php.net/manual/en/reserved.classes.php

Finally, why a generic object in this case? Too lazy to define an actual object with proper JavaDoc comments?  And how about some validation?  This SDK needs a lot of work.

**Comment by sneakyimp** [comment]
Nice to see all the effort being made to remedy this situation after a month has passed :-1:

**Comment by brianmc** [comment]
Hi @sneakyimp We really should have removed or labelled these MD files as deprecated.

Here's an example of supplying a card code and billing address when you create a payment profile:  https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/create-customer-payment-profile.php

Interested to hear your feedback on the new controller model for our SDKs, it may sacrifice some language efficiencies but the benefit is that it should be very consistent with our API and as such should require less interpretation by developers.

Thanks,  Brian
