### ISSUE TITLE
Getting error while run composer update command

### ISSUE THREAD

**Issue by rahul7777yadav** [AuthorizeNet/sdk-php#64]
Error is following : 

swati@swati-pc:/opt/lampp/htdocs/sdk-php-master$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)  
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package authorizenet/authorizenet No version set (parsed as 1.0.0) could not be found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by OhedAli** [comment]
Problem 1
    - The requested package authorizenet/authorizenet No version set (parsed as 1.0.0) is satisfiable by authorizenet/authorizenet[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

i am getting the above error, Can anyone please suggest me.

**Comment by ashtru** [comment]
Kindly share the contents of your `composer.json` file.
Which version of the Authorize.NET SDK are you trying to use?

**Comment by OhedAli** [comment]
Composer version: 1.6.1
However, I have tried with diffrent machine and it's worked.

Thanks for your quick reply

**Comment by ashtru** [comment]
Thanks for your feedback @OhedAli . I am closing the issue.

Happy Coding!
Ashutosh Singh
Authorize.NET Team
