### ISSUE TITLE
AuthorizeNet_Subscription is not escaping values for inclusion in XML

### ISSUE THREAD

**Issue by JustAHappyKid** [AuthorizeNet/sdk-php#67]
If one needs to create a subscription for a credit-card registered to "Jim & Jane Plain", for example, this is problematic; invalid XML will be produced. The escaping should probably extend to every field that could conceivably have an ampersand, which would easily include company, address -- probably even country (though usually it's best to just escape everything for good measure).

For my purposes I only needed the name fields escaped (for now), so I patched my local copy of `AuthorizeNetTypes.php`, adding a method to `AuthorizeNet_Subscription` like this:

    /**
     * Escape the given string for inclusion in XML.
     */
    private function escape($s) {
        return htmlspecialchars($s, ENT_QUOTES | ENT_XML1);
    }

Then I escape the values like this:

    <firstName>{$this->escape($this->billToFirstName)}</firstName>
    <lastName>{$this->escape($this->billToLastName)}</lastName>

**Comment by schmich** [comment]
I hit this issue as well. The onus of escaping input data should not be on clients of the library. It should be built into the library itself since the transport format (XML) is an implementation detail.

The workaround @JustAHappyKid mentions works, but it shouldn't be necessary. It would be good to see a fix here.

**Comment by brianmc** [comment]
Thanks for the issue guys, perfectly valid and we're looking at this.

**Comment by brianmc** [comment]
This issue was fixed with the Nov Release 1.8.6.2 https://github.com/AuthorizeNet/sdk-php/releases

**Comment by jdavidbakr** [comment]
@brianmc - was this fix global across the entire SDK?  I'm getting this same issue if I create a CIM payment profile where the company name has an ampersand in it using version 1.9.0
