### ISSUE TITLE
AuthorizeNetCIM_Response::getTransactionResponse returns spurious connection error

### ISSUE THREAD

**Issue by sneakyimp** [AuthorizeNet/sdk-php#68]
If one uses a CIM request to charge a non-existent user, your gateway responds with a well-formed response:
```xml
<?xml version="1.0" encoding="utf-8"?><createCustomerProfileTransactionResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd"><messages><resultCode>Error</resultCode><message><code>E00040</code><text>Customer Profile ID or Customer Payment Profile ID not found.</text></message></messages></createCustomerProfileTransactionResponse>

```

HOWEVER, your code returns an AuthorizeNetAIM_Response object that says there was a connection problem. This problem would apparently be due to the fact that the getTransactionResponse function is trying to parse a non-existent XML element, directResponse:
```php
    public function getTransactionResponse()
    {
        return new AuthorizeNetAIM_Response($this->_getElementContents("directResponse"), ",", "|", array());
    }
```
See https://github.com/AuthorizeNet/sdk-php/blob/master/lib/AuthorizeNetCIM.php#L459

Your code should be at least intelligent enough to recognize that it has in fact connected the gateway successfully and parse out the appropriate error message. Jeeze.

**Comment by brianmc** [comment]
Hi @sneakyimp, We've never been that happy with the charging of a profile with this method, so we're recommending that developers move over to the standard createTransaction request and in that way there will be no need for directResponse and a consistent error handling pattern:  http://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile  

In the PHP SDK you can now do this pretty easily, here's a sample:  https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/charge-customer-profile.php

I'm closing this one but please give us your feedback if this doesn't seem like a reasonable solution.  Thanks,

Brian
