### ISSUE TITLE
missing createCustomerProfileFromTransaction

### ISSUE THREAD

**Issue by webrevllc** [AuthorizeNet/sdk-php#70]
I use this function ALL THE TIME, I also push everything to my server with git autodeploy webhook that does a composer install (Envoyer.io). I have to SSH into my server every time I deploy to add this function to AuthorizeNetCIM.php

/**
     * @param $transId
     * @return AuthorizeNetCIM_Response
     */
    public function createCustomerProfileFromTransaction($transId)
    {
        $this->_constructXml("createCustomerProfileFromTransactionRequest");
        $this->_xml->addChild("transId", $transId);
        return $this->_sendRequest();
    }

**Comment by brianmc** [comment]
Hi @webrevllc It's most likely we will not add this to the old model SDK objects but we have a sample for using this in new model:  https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/create-profile-from-transaction.php

Let us know what you think.
