### ISSUE TITLE
Update API URL too use the Akamai URLS

### ISSUE THREAD

**Issue by Prefinem** [AuthorizeNet/sdk-php#71]
The new Akamai transaction URLs that are available now are: 

- https://api2.authorize.net/xml/v1/request.api 
- https://api2.authorize.net/soap/v1/Service.asmx 
- https://secure2.authorize.net/gateway/transact.dll

**Comment by brianmc** [comment]
SDK was updated to use these URLS.  See https://github.com/AuthorizeNet/sdk-php/releases/tag/1.8.5
