### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by blakemckeeby** [AuthorizeNet/sdk-php#73]
In tag 1.8.3 the composer.json file indicated a dependency on "jms/serializer": “*”. In subsequent versions, your composer file indicates a dependency on "jms/serializer": "xsd2php-dev as 0.18.0" but it does not seem like that version of serializer package is available? 

https://packagist.org/packages/jms/serializer

 authorizenet/authorizenet 1.8.5.1 requires jms/serializer xsd2php-dev as 0
.18.0 -> no matching package found.

**Comment by TrevorW** [comment]
This line in the composer file is actually indicating that we are using the xsd2php-dev fork in place of the main serializer packages. You can find this on packagist at https://packagist.org/packages/goetas/xsd2php

This fork addresses a bug that has not yet been addressed in the main serializer packages.

**Comment by danmcadams** [comment]
I'm having the same issue. I added a comment in the composer.json file here, this probably would have been a better place, so, here I am. 

So, we need to add https://packagist.org/packages/goetas/xsd2php in order to install 1.8.5.1?

**Comment by danmcadams** [comment]
@blakemckeeby Did you ever get it working? I'm still stuck :-/

**Comment by mixnetworks** [comment]
@danmcadams I was helping a remote developer who sent me this error message. I never actually experienced myself. When I went to deploy the code I didn't have the issue so I wasn't able to troubleshoot further. Sorry :(

**Comment by gRegorLove** [comment]
I was able to get this working by changing my composer.json from the basic `{"require": {"authorizenet/authorizenet": "~1.8"} }` to the one [listed further down in the readme](https://github.com/AuthorizeNet/sdk-php#new-model)

```
{

  "require": {
  "php": ">=5.2.0",
  "ext-curl": "*",
  "authorizenet/authorizenet": "1.8.3",
  "jms/serializer": "xsd2php-dev as 0.18.0"
},
"require-dev": {
  "goetas/xsd2php": "2.*@dev",
  "goetas/xsd-reader": "2.*@dev"
},
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/goetas/serializer.git"
    }]

}
```

The only thing I changed was the authorizenet version to 1.8.5.1 and PHP to 5.3.

Another important caveat is that the `require-dev` must be installed as well (composer default behavior). I was trying to `composer install --no-dev` and still running into issues, but it worked fine with `composer install`.

**Comment by steveperrito** [comment]
Thanks @gRegorLove! After pasting the above to composer.json and updating both the PHP and authorize.net versions, I ran `composer update`. This worked for me.

**Comment by texdc** [comment]
@gRegorLove Yes, the `xsd` libraries should be moved out of `require-dev` and into `require`.  Good catch!

**Comment by danmcadams** [comment]
@gRegorLove Hey, thanks! Got it working. I was missing 

```
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/goetas/serializer.git"
    }]
```

**Comment by macagua** [comment]
@gRegorLove thanks!

**Comment by Wardevour** [comment]
It'd be nice, for those of us who don't or can't use composer, if the README.md listed the jms/serialzer under the requirements section...

**Comment by hswest** [comment]
that file should be a text file with the md extension on it. I’ve always seen it that way and practiced that even back when I was on github three years ago.

--
Blake D. Hoffman
Sr. Systems Engineer homesite.com
blake.hoffman@homesite.com | M: 425-442-1039

**Comment by arleslie** [comment]
That repository should be added to the package's composer.json

**Comment by bassrock** [comment]
it would be great to lose the new dependency on jms serializer or work with the owner to get ti merged, as I already use a customized version of JMS Serializer.

**Comment by SirMontu** [comment]
It would be great if the directions here got updated or the package to install got updated. I've just downloaded everything from here and I can't make heads or tails to which configuration I should be using to resolve the Yaml dependency that throws an error as not being found.

**Comment by yuriitvardyi** [comment]
AuthorizeNet library size is 2.4 MB, but it loads about 30 dependencies with overall size over 60 MB. It is too much. The library size should be as small as possible. Please, make library without dependencies (in ideal) or find alternatives with smaller size.

**Comment by goetas** [comment]
this new release https://github.com/goetas/xsd2php/releases/tag/2.1.0 should be interesting for you

**Comment by chsriniv9** [comment]
Closing this issue, feel free to reopen in case of any queries.
_Closing note:_ Issues related to _goetas_ repositories moving to _goetas-webservices_, have been resolved. As such jms-serializer version concluded by `composer update ` will work. Use the latest version of the PHP SDK.
