### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by diemuzi** [AuthorizeNet/sdk-php#78]
We are currently testing PHP 7 Support using the current RC5 to try to get ahead of the curve. However when installing the Authorize.net PHP SDK with composer we're stuck:

authorizenet/authorizenet dev-master requires php ~5.3 -> your PHP version (7.0.0RC5) or "config.platform.php" value does not satisfy that requirement.

Could we get the PHP version changed in the composer.json file to something like >=5.3 instead of ~5.3? I'll make the PR is needed, that's no big deal. I don't see anything in the code base that would cause problems unless I've missed something.

**Comment by texdc** [comment]
The only change necessary is to add the `v7` requirement:
```json
{
    "require":  {
        "php": "~5.4 || ~7.0"
    }
}
```

**Comment by SimonSonar** [comment]
Adding my +1 here, this is a big issue for us. Holding us back from PHP7 updates. Any news? It's a very simple fix and the library works fine with PHP7.

**Comment by reket** [comment]
ping @brianmc

**Comment by brianmc** [comment]
This didn't go as smoothly as we expected, we hit some issues with the travis build against v7 (see commit https://github.com/AuthorizeNet/sdk-php/commit/a06111e523c557d4c9061b8fa5d6dfb763a8f029) 
We'll have an update later this week, apologies for the delays.

**Comment by SonarSoftware** [comment]
Sounds good, thanks for the update. FWIW, I forked the SDK just so I could have PHP7 support for now, and all the CIM functions work perfectly fine, although I don't use much else.

**Comment by swvjeff** [comment]
@brianmc Waiting patiently for PHP 7 support. Any updates?

**Comment by jdavidbakr** [comment]
@brianmc Just tried an update to PHP 7 on my system and am also getting this same error.  It's been a little more thane a week, any eta on when it will get updated?

**Comment by gitsundar** [comment]
@jdavidbakr 
Use the below command as a workaround
composer update --ignore-platform-reqs

**Comment by brianmc** [comment]
Sorry for the delays guys, we're now including PHP 7 in our Travis CI and have updated composer.json.

Thanks for your patience,

Brian
