### ISSUE TITLE
Fatal Error Class 'Symfony\Component\Yaml\Yaml' not found in

### ISSUE THREAD

**Issue by DevinWalker** [AuthorizeNet/sdk-php#86]
I'm running into a this fatal error:

`Fatal error: Class 'Symfony\Component\Yaml\Yaml' not found in ...includes\gateways\authorize-sdk-php\vendor\jms\serializer\src\JMS\Serializer\Metadata\Driver\YamlDriver.php on line 35`

I've run `composer update` and am not sure what the issue is...

**Comment by twvm** [comment]
I see this issue as well. Does anyone have an update on this?

**Comment by vovik64** [comment]
you can download it from github  + add references to classmap.php
......
    'Symfony\Component\Yaml\Yaml' => $vendorDir . '/symfony/src/Symfony/Component/Yaml/Yaml.php',
    'Symfony\Component\Yaml\Parser' => $vendorDir . '/symfony/src/Symfony/Component/Yaml/Parser.php',
    'Symfony\Component\Yaml\Inline' => $vendorDir . '/symfony/src/Symfony/Component/Yaml/Inline.php',		
.......

**Comment by vovik64** [comment]
https://github.com/symfony/yaml

**Comment by brianmc** [comment]
Hi guys, should be fixed in our latest 1.8.7 release.  Thank-you for opening the issue.

**Comment by HealingRooms** [comment]
Hey Brian (@brianmc),

This problem is still happening.

**Comment by BenGeocth** [comment]
I fixed this by running in console composer require symfony/yaml

**Comment by HealingRooms** [comment]
Hi @BenGeocth ,

I had tried that method as well, but to no avail.

`composer require symfony/yaml`

While the process appeared to be successful in its installation / update of Yaml, the error message generated in the error_log file remained the same.

This is a sample of the error message (with a directory name removed):

`PHP Fatal error:  Class 'Symfony\Component\Yaml\Yaml' not found in /home/h____s/public_html/vendor/jms/serializer/src/JMS/Serializer/Metadata/Driver/YamlDriver.php on line 35`

**Comment by BenGeocth** [comment]
What does your composer.json look like? Here's mine:

```{
  "require": {
  "php": ">=5.5",
  "ext-curl": "*",
  "authorizenet/authorizenet": "^1.9",
  "jms/serializer": "serializer-master-dev as 1.0",
    "symfony/yaml": "^3.1"
  },
  "repositories": [{
       "type": "vcs",
       "url": "https://github.com/goetas/serializer.git"
  }]
}
```

**Comment by HealingRooms** [comment]
My composer file looks almost identical, although with a slightly more recent authorize.net version, with the symfony line, without the jms line, and without the repositories section.

To update the issue, I manually removed each of those three folders via FTP and reinstalled authorize.net via the puTTY command prompt, then installed the authorize.net test folder as well (although it already existed).  Progress was made.
