### ISSUE TITLE
authorizenet 1.8.5 requires jms/serializer xsd2php-dev as 0.18.0

### ISSUE THREAD

**Issue by Prefinem** [AuthorizeNet/sdk-php#87]
I get this error when I try and update the SDK to the latest version (happens on 1.8.5.1)

Problem 1
* Installation request for authorizenet/authorizenet 1.8.5 -> satisfiable by authorizenet/authorizenet[1.8.5].
* authorizenet/authorizenet 1.8.5 requires jms/serializer xsd2php-dev as 0.18.0 -> no matching package found.

Merge was from here: https://github.com/AuthorizeNet/sdk-php/commit/c43a42535c27357d50092131423d4671cbb84988

**Comment by KerryJones** [comment]
I got this while trying to install as well "compose require ..."

**Comment by chris-schmitz** [comment]
Yep, I got this too:

![screen shot 2015-11-16 at 11 47 06 am](https://cloud.githubusercontent.com/assets/2437424/11189824/f522ff2c-8c57-11e5-9038-a047f9cc1296.png)

I got this error when trying to add the package via the `composer require` cli command and when trying to add the requirements directly into my composer.json file per [the hello world walkthrough](http://developer.authorize.net/hello_world/):

![screen shot 2015-11-16 at 11 49 05 am](https://cloud.githubusercontent.com/assets/2437424/11189889/6c7d757a-8c58-11e5-97e1-7059bcfd88a2.png)

**Comment by chris-schmitz** [comment]
Hey @Prefinem and @KerryJones. I don't know if you've figured this out already or not, but for you if you haven't and for anyone else who may run into the same error:

If you (like me) are following the [Getting Started](http://developer.authorize.net/hello_world/) instructions on developer.authorize.net then the problem you're running into is that the instructions on authorize.net are out of date. 

The [autoloading section of the readme](https://github.com/AuthorizeNet/sdk-php#autoloading) for the project has the up-to-date instructions for installing the package. After I updated my composer.json file it worked. 

That said, it's worth reading about the Man in [the composer Middle vulnerability](https://github.com/composer/composer/issues/1074) that the contributors reference in the the readme is apparently still open (news to me). Right now I'm working through the sandbox to understand the API so I'm not concerned at the moment, but I'm definitely going to look into it and the autoloader that Authorize.net provides instead before incorporating anything into my production project.

**Comment by Prefinem** [comment]
@chris-schmitz Thanks for that info!

I do know about the MITM vulnerability and use composer locally and then push up the files after testing. Hopefully they will get if fixed soon.

**Comment by chris-schmitz** [comment]
@Prefinem No prob. 

Yeah, I hadn't even heard of the venerability and was surprised to read about it. I don't really know anything about it outside of scanning the thread yet, but it's sounds like something that can be coped with. 

>Hopefully they will get if fixed soon.

Definitely.

**Comment by texdc** [comment]
> Hopefully they will get if fixed soon.

We've been saying that for a couple years now.  Their recommended solution is to set up a private, secure package repo that mirrors packagist, i.e. `https://packages.authorize.net`

https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md

**Comment by brianmc** [comment]
Getting Started instructions (http://developer.authorize.net/hello_world/) have been updated to reflect the SDK Readme on GitHub and the composer file from Sample Code project (https://github.com/AuthorizeNet/sample-code-php).
