### ISSUE TITLE
Subscriptions (ARB) are created without CC validation

### ISSUE THREAD

**Issue by Critter** [AuthorizeNet/sdk-php#92]
If I send this in for a subscription to a production account:

	$subscription = new AuthorizeNet_Subscription;
	$subscription->name = "Short subscription";
	$subscription->intervalLength = "12";
	$subscription->intervalUnit = "months";
	$subscription->startDate = "2015-11-20";
	$subscription->totalOccurrences = "9999";
	$subscription->amount = 235;
	$subscription->creditCardCardNumber = "5551766170335085";
	$subscription->creditCardExpirationDate = "2018-03";
	$subscription->creditCardCardCode = "897";
	$subscription->billToFirstName = "Happy";
	$subscription->billToLastName = "Gilmore";

The CC info is bogus, but it does validate as a proper card number.

This is my response:

    AuthorizeNetARB_Response Object
    (
        [xml] => SimpleXMLElement Object
            (
                [messages] => SimpleXMLElement Object
                    (
                        [resultCode] => Ok
                        [message] => SimpleXMLElement Object
                            (
                                [code] => I00001
                                [text] => Successful.
                            )

                    )

                [subscriptionId] => 26519381
            )

        [response] => ï»¿OkI00001Successful.26519381
        [xpath_xml] => SimpleXMLElement Object
            (
                [messages] => SimpleXMLElement Object
                    (
                        [resultCode] => Ok
                        [message] => SimpleXMLElement Object
                            (
                                [code] => I00001
                                [text] => Successful.
                            )

                    )

                [subscriptionId] => 26519381
            )

    )

From what I've gathered subscriptions are processed in batch at 2am or something, but is there no type of validation done on the information submitted prior to that batch processing?

**Comment by brianmc** [comment]
Now that our subscriptions are based on customer profiles we will soon be adding the ability to validate the card on a createSubscription in the same way you can for profile creation (see validationMode parameter) http://developer.authorize.net/api/reference/#customer-profiles-create-customer-profile 

Right now the default validation mode is testMode for subscription create which is a simple card number check (Luhn) but not a network card validation.  

Thanks for the feedback.
