### ISSUE TITLE
file_put_contents(phplog): failed to open stream: Permission denied

### ISSUE THREAD

**Issue by peppeocchi** [AuthorizeNet/sdk-php#93]
There is a weird issue that was not happening few days/weeks ago.

It keeps looking for `phplog` file, I've defined (as for the [php-samples](https://github.com/AuthorizeNet/sample-code-php/blob/master/CustomerProfiles/create-customer-profile.php#L5)) my `AUTHORIZENET_LOG_FILE` but it looks like it's not being used.

Looking at the source or the error, [here](https://github.com/AuthorizeNet/sdk-php/blob/master/lib/net/authorize/util/Log.php#L7) is where is being defined `ANET_LOG_FILE` with `phplog`.

Deleting/changing that line from that file solves the issue.
I've personally deleted that line and defined `ANET_LOG_FILE` when I set the credentials (instead of `AUTHORIZENET_LOG_FILE`), it works like a charm.

**Comment by apropos** [comment]
This should be resolved by [this commit](https://github.com/apropos/sdk-php/commit/ce348787337c7a6f9213a484681d155d4218ab8a)

**Comment by brianmc** [comment]
Hi @apropos, this should be fixed in our latest 1.8.7 release.  Thanks for opening the issue.
