### ISSUE TITLE
PayPal Express Checkout  problem with  "lineItems" and "shipTo"

### ISSUE THREAD

**Issue by vovik64** [AuthorizeNet/sdk-php#98]
PayPal transactions works good on our website but we have one problem with "Authorization and Capture Request" 

according to http://developer.authorize.net/api/reference/index.html#paypal-express-checkout-authorization-and-capture

this request has  "lineItems"  (you can see it under "Try It"/XML tab) 
and  "shipTo"  (you can see it under "Request")

as you can see first problem with doc  - "Request" tab has one set of fields but "Try It"/XML tab another set of fields
second problem - "lineItems" and "shipTo"  dont works and dont shows in PayPal and authorize merchant and in "Authorize Receipt Email" (which is very important to us)

below you can see XML which was sent to authorize: 

    <?xml version="1.0" encoding="UTF-8"?>
    <createTransactionRequest xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
      <merchantAuthentication>
        <name><![CDATA[XXXXXXXXXX]]></name>
        <transactionKey>xxxxx</transactionKey>
      </merchantAuthentication>
      <transactionRequest>
        <transactionType><![CDATA[authCaptureTransaction]]></transactionType>
        <amount>40</amount>
        <payment>
          <payPal>
            <successUrl><![CDATA[http://www.hereourdomainname.com/paypalsuccess/b5668c83aadb17/]]></successUrl>
            <cancelUrl><![CDATA[http://www.hereourdomainname.com/paypalfail/]]></cancelUrl>
            <paypalHdrImg><![CDATA[http://www.hereourdomainname.com/logo.png]]>        </paypalHdrImg>
                <paypalPayflowcolor><![CDATA[7f267f]]></paypalPayflowcolor>
          </payPal>
        </payment>
        <lineItems>
          <lineItem>
            <itemId><![CDATA[100]]></itemId>
            <name><![CDATA[hereproducttitle]]></name>
            <description><![CDATA[12/31/2015-8:00 am]]></description>
            <quantity>1</quantity>
            <unitPrice>40</unitPrice>
          </lineItem>
        </lineItems>
      </transactionRequest>
    </createTransactionRequest>

**Comment by brianmc** [comment]
We're looking into this one, thanks for submitting the issue.

**Comment by brianmc** [comment]
Both lineitems and shipTo are supported but the validation by PayPal is more strict than the Authorize.Net validation.  The lineItems totals must match the amount field in the request.  The address must be a valid postal address.

Thanks again for raising this issue, we will update the documentation.
